/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.util.concurrent.ThreadFactoryBuilder
 *  com.mojang.datafixers.DSL
 *  com.mojang.datafixers.DSL$TypeReference
 *  com.mojang.datafixers.DataFix
 *  com.mojang.datafixers.DataFixer
 *  com.mojang.datafixers.DataFixerBuilder
 *  com.mojang.datafixers.DataFixerBuilder$Result
 *  com.mojang.datafixers.OpticFinder
 *  com.mojang.datafixers.TypeRewriteRule
 *  com.mojang.datafixers.schemas.Schema
 *  com.mojang.datafixers.types.Type
 *  com.mojang.serialization.Dynamic
 *  it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap
 */
import com.google.common.collect.ImmutableMap;
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFix;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.OpticFinder;
import com.mojang.datafixers.TypeRewriteRule;
import com.mojang.datafixers.schemas.Schema;
import com.mojang.datafixers.types.Type;
import com.mojang.serialization.Dynamic;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class bia {
    private static final BiFunction<Integer, Schema, Schema> b = Schema::new;
    private static final BiFunction<Integer, Schema, Schema> c = bsh::new;
    private static final DataFixerBuilder.Result d = bia.b();
    public static final int a = 4295;

    private bia() {
    }

    public static DataFixer a() {
        return d.fixer();
    }

    private static DataFixerBuilder.Result b() {
        DataFixerBuilder $$0 = new DataFixerBuilder(w.b().a().b());
        bia.a($$0);
        return $$0.build();
    }

    public static CompletableFuture<?> a(Set<DSL.TypeReference> $$0) {
        if ($$0.isEmpty()) {
            return CompletableFuture.completedFuture(null);
        }
        ExecutorService $$1 = Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("Datafixer Bootstrap").setDaemon(true).setPriority(1).build());
        return d.optimize($$0, (Executor)$$1);
    }

    /*
     * WARNING - void declaration
     */
    private static void a(DataFixerBuilder $$02) {
        void $$295;
        void $$294;
        void $$293;
        void $$292;
        void $$291;
        void $$290;
        void $$289;
        void $$288;
        void $$287;
        void $$286;
        void $$285;
        void $$284;
        void $$283;
        void $$282;
        void $$281;
        void $$280;
        void $$279;
        void $$278;
        void $$277;
        void $$276;
        void $$275;
        void $$274;
        void $$273;
        void $$272;
        void $$271;
        void $$270;
        void $$269;
        void $$268;
        void $$267;
        void $$266;
        void $$265;
        void $$264;
        void $$263;
        void $$262;
        void $$261;
        void $$260;
        void $$259;
        void $$258;
        void $$257;
        void $$256;
        $$02.addSchema(99, bwr::new);
        Schema $$12 = $$02.addSchema(100, bsi::new);
        $$02.addFixer((DataFix)new bli($$12));
        Schema $$2 = $$02.addSchema(101, b);
        $$02.addFixer((DataFix)new brt($$2));
        Schema $$3 = $$02.addSchema(102, bsj::new);
        $$02.addFixer((DataFix)new bnl($$3, true));
        $$02.addFixer((DataFix)new bnn($$3, false));
        Schema $$4 = $$02.addSchema(105, b);
        $$02.addFixer((DataFix)new bnq($$4, true));
        Schema $$5 = $$02.addSchema(106, bsl::new);
        $$02.addFixer((DataFix)new bou($$5, true));
        Schema $$6 = $$02.addSchema(107, bsm::new);
        $$02.addFixer((DataFix)new blr($$6));
        Schema $$7 = $$02.addSchema(108, b);
        $$02.addFixer((DataFix)new bmf($$7, true));
        Schema $$8 = $$02.addSchema(109, b);
        $$02.addFixer((DataFix)new blm($$8, true));
        Schema $$9 = $$02.addSchema(110, b);
        $$02.addFixer((DataFix)new bln($$9, true));
        Schema $$10 = $$02.addSchema(111, b);
        $$02.addFixer((DataFix)new bls($$10, true));
        Schema $$11 = $$02.addSchema(113, b);
        $$02.addFixer((DataFix)new blx($$11, true));
        Schema $$122 = $$02.addSchema(135, bso::new);
        $$02.addFixer((DataFix)new blz($$122, true));
        Schema $$13 = $$02.addSchema(143, bsp::new);
        $$02.addFixer((DataFix)new bmh($$13, true));
        Schema $$14 = $$02.addSchema(147, b);
        $$02.addFixer((DataFix)new bla($$14, true));
        Schema $$15 = $$02.addSchema(165, b);
        $$02.addFixer((DataFix)new bqv($$15));
        $$02.addFixer((DataFix)new bsd($$15));
        Schema $$16 = $$02.addSchema(501, bwj::new);
        $$02.addFixer((DataFix)new bik($$16, "Add 1.10 entities fix", bqh.H));
        Schema $$17 = $$02.addSchema(502, b);
        $$02.addFixer(bno.a($$17, "cooked_fished item renamer", (String $$0) -> Objects.equals(bsh.a($$0), "minecraft:cooked_fished") ? "minecraft:cooked_fish" : $$0));
        $$02.addFixer((DataFix)new bmm($$17, false));
        Schema $$18 = $$02.addSchema(505, b);
        $$02.addFixer((DataFix)new bpi($$18, false));
        Schema $$19 = $$02.addSchema(700, bwk::new);
        $$02.addFixer((DataFix)new blh($$19, true));
        Schema $$20 = $$02.addSchema(701, bwl::new);
        $$02.addFixer((DataFix)new bmd($$20, true));
        Schema $$21 = $$02.addSchema(702, bwm::new);
        $$02.addFixer((DataFix)new bml($$21));
        Schema $$22 = $$02.addSchema(703, bwn::new);
        $$02.addFixer((DataFix)new blo($$22, true));
        Schema $$23 = $$02.addSchema(704, bwo::new);
        $$02.addFixer((DataFix)new bjf($$23, true));
        Schema $$24 = $$02.addSchema(705, bwp::new);
        $$02.addFixer((DataFix)new blp($$24, true));
        Schema $$25 = $$02.addSchema(804, c);
        $$02.addFixer((DataFix)new bnj($$25, true));
        Schema $$26 = $$02.addSchema(806, c);
        $$02.addFixer((DataFix)new boa($$26, false));
        Schema $$27 = $$02.addSchema(808, bwq::new);
        $$02.addFixer((DataFix)new bik($$27, "added shulker box", bqh.w));
        Schema $$28 = $$02.addSchema(808, 1, c);
        $$02.addFixer((DataFix)new bmb($$28, false));
        Schema $$29 = $$02.addSchema(813, c);
        $$02.addFixer((DataFix)new bnp($$29, false));
        $$02.addFixer((DataFix)new bjj($$29, false));
        Schema $$30 = $$02.addSchema(816, c);
        $$02.addFixer((DataFix)new bpm($$30, false));
        Schema $$31 = $$02.addSchema(820, c);
        $$02.addFixer(bno.a($$31, "totem item renamer", bia.a("minecraft:totem", "minecraft:totem_of_undying")));
        Schema $$32 = $$02.addSchema(1022, bsk::new);
        $$02.addFixer((DataFix)new bsc($$32, "added shoulder entities to players", bqh.c));
        Schema $$33 = $$02.addSchema(1125, bsn::new);
        $$02.addFixer((DataFix)new bjy($$33, true));
        $$02.addFixer((DataFix)new biv($$33, false));
        Schema $$34 = $$02.addSchema(1344, c);
        $$02.addFixer((DataFix)new bpk($$34, false));
        Schema $$35 = $$02.addSchema(1446, c);
        $$02.addFixer((DataFix)new bpl($$35, false));
        Schema $$36 = $$02.addSchema(1450, c);
        $$02.addFixer((DataFix)new bjr($$36, false));
        Schema $$37 = $$02.addSchema(1451, bsq::new);
        $$02.addFixer((DataFix)new bik($$37, "AddTrappedChestFix", bqh.w));
        Schema $$38 = $$02.addSchema(1451, 1, bsr::new);
        $$02.addFixer((DataFix)new bke($$38, true));
        Schema $$39 = $$02.addSchema(1451, 2, bss::new);
        $$02.addFixer((DataFix)new bjc($$39, true));
        Schema $$40 = $$02.addSchema(1451, 3, bst::new);
        $$02.addFixer((DataFix)new blc($$40, true));
        $$02.addFixer((DataFix)new bnu($$40, false));
        Schema $$41 = $$02.addSchema(1451, 4, bsu::new);
        $$02.addFixer((DataFix)new bjm($$41, true));
        $$02.addFixer((DataFix)new bny($$41, false));
        Schema $$42 = $$02.addSchema(1451, 5, bsv::new);
        $$02.addFixer((DataFix)new bqj($$42, Set.of("minecraft:noteblock", "minecraft:flower_pot")));
        $$02.addFixer((DataFix)new bnv($$42, false, "minecraft:spawn_egg"));
        $$02.addFixer((DataFix)new bmk($$42, false));
        $$02.addFixer((DataFix)new bjb($$42, false));
        $$02.addFixer((DataFix)new bok($$42, false));
        Schema $$43 = $$02.addSchema(1451, 6, bsw::new);
        $$02.addFixer((DataFix)new bqz($$43, true));
        $$02.addFixer((DataFix)new bjg($$43, false));
        Schema $$44 = $$02.addSchema(1451, 7, c);
        $$02.addFixer((DataFix)new bru($$44));
        Schema $$45 = $$02.addSchema(1456, c);
        $$02.addFixer((DataFix)new blq($$45, false));
        Schema $$46 = $$02.addSchema(1458, bsx::new);
        $$02.addFixer((DataFix)new blg($$46));
        $$02.addFixer((DataFix)new bnk($$46));
        $$02.addFixer((DataFix)new bjd($$46));
        Schema $$47 = $$02.addSchema(1460, bsy::new);
        $$02.addFixer((DataFix)new blt($$47, false));
        Schema $$48 = $$02.addSchema(1466, bsz::new);
        $$02.addFixer((DataFix)new bik($$48, "Add DUMMY block entity", bqh.w));
        $$02.addFixer((DataFix)new bkl($$48, true));
        Schema $$49 = $$02.addSchema(1470, bta::new);
        $$02.addFixer((DataFix)new bik($$49, "Add 1.13 entities fix", bqh.H));
        Schema $$50 = $$02.addSchema(1474, c);
        $$02.addFixer((DataFix)new bkm($$50, false));
        $$02.addFixer(bjp.a($$50, "Colorless shulker block fixer", (String $$0) -> Objects.equals(bsh.a($$0), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : $$0));
        $$02.addFixer(bno.a($$50, "Colorless shulker item fixer", (String $$0) -> Objects.equals(bsh.a($$0), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : $$0));
        Schema $$51 = $$02.addSchema(1475, c);
        $$02.addFixer(bjp.a($$51, "Flowing fixer", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:flowing_water", (Object)"minecraft:water", (Object)"minecraft:flowing_lava", (Object)"minecraft:lava"))));
        Schema $$52 = $$02.addSchema(1480, c);
        $$02.addFixer(bjp.a($$52, "Rename coral blocks", bia.b(bqo.a)));
        $$02.addFixer(bno.a($$52, "Rename coral items", bia.b(bqo.a)));
        Schema $$53 = $$02.addSchema(1481, btb::new);
        $$02.addFixer((DataFix)new bik($$53, "Add conduit", bqh.w));
        Schema $$54 = $$02.addSchema(1483, btc::new);
        $$02.addFixer((DataFix)new blv($$54, true));
        $$02.addFixer(bno.a($$54, "Rename pufferfish egg item", bia.b(blv.a)));
        Schema $$55 = $$02.addSchema(1484, c);
        $$02.addFixer(bno.a($$55, "Rename seagrass items", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:sea_grass", (Object)"minecraft:seagrass", (Object)"minecraft:tall_sea_grass", (Object)"minecraft:tall_seagrass"))));
        $$02.addFixer(bjp.a($$55, "Rename seagrass blocks", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:sea_grass", (Object)"minecraft:seagrass", (Object)"minecraft:tall_sea_grass", (Object)"minecraft:tall_seagrass"))));
        $$02.addFixer((DataFix)new bnd($$55, false));
        Schema $$56 = $$02.addSchema(1486, btd::new);
        $$02.addFixer((DataFix)new blf($$56, true));
        $$02.addFixer(bno.a($$56, "Rename cod/salmon egg items", bia.b(blf.b)));
        Schema $$57 = $$02.addSchema(1487, c);
        $$02.addFixer(bno.a($$57, "Rename prismarine_brick(s)_* blocks", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:prismarine_bricks_slab", (Object)"minecraft:prismarine_brick_slab", (Object)"minecraft:prismarine_bricks_stairs", (Object)"minecraft:prismarine_brick_stairs"))));
        $$02.addFixer(bjp.a($$57, "Rename prismarine_brick(s)_* items", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:prismarine_bricks_slab", (Object)"minecraft:prismarine_brick_slab", (Object)"minecraft:prismarine_bricks_stairs", (Object)"minecraft:prismarine_brick_stairs"))));
        Schema $$58 = $$02.addSchema(1488, bte::new);
        $$02.addFixer(bjp.a($$58, "Rename kelp/kelptop", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:kelp_top", (Object)"minecraft:kelp", (Object)"minecraft:kelp", (Object)"minecraft:kelp_plant"))));
        $$02.addFixer(bno.a($$58, "Rename kelptop", bia.a("minecraft:kelp_top", "minecraft:kelp")));
        $$02.addFixer((DataFix)new box($$58, true, "Command block block entity custom name fix", bqh.w, "minecraft:command_block"){

            @Override
            protected <T> Dynamic<T> a(Dynamic<T> $$0) {
                return bjd.a($$0);
            }
        });
        $$02.addFixer(new DataFix($$58, false){

            protected TypeRewriteRule makeRule() {
                Type $$0 = this.getInputSchema().getType(bqh.H);
                OpticFinder $$1 = DSL.fieldFinder((String)"id", bsh.a());
                OpticFinder $$2 = $$0.findField("CustomName");
                OpticFinder $$32 = DSL.typeFinder((Type)this.getInputSchema().getType(bqh.D));
                return this.fixTypeEverywhereTyped("Command block minecart custom name fix", $$0, $$3 -> {
                    String $$4 = $$3.getOptional($$1).orElse("");
                    if (!"minecraft:commandblock_minecart".equals($$4)) {
                        return $$3;
                    }
                    return $$3.updateTyped($$2, $$1 -> $$1.update($$32, $$0 -> $$0.mapSecond(bic::a)));
                });
            }
        });
        $$02.addFixer((DataFix)new bnf($$58, false));
        Schema $$59 = $$02.addSchema(1490, c);
        $$02.addFixer(bjp.a($$59, "Rename melon_block", bia.a("minecraft:melon_block", "minecraft:melon")));
        $$02.addFixer(bno.a($$59, "Rename melon_block/melon/speckled_melon", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:melon_block", (Object)"minecraft:melon", (Object)"minecraft:melon", (Object)"minecraft:melon_slice", (Object)"minecraft:speckled_melon", (Object)"minecraft:glistering_melon_slice"))));
        Schema $$60 = $$02.addSchema(1492, c);
        $$02.addFixer((DataFix)new bkj($$60, false));
        Schema $$61 = $$02.addSchema(1494, c);
        $$02.addFixer((DataFix)new bnt($$61, false));
        Schema $$62 = $$02.addSchema(1496, c);
        $$02.addFixer((DataFix)new boe($$62, false));
        Schema $$63 = $$02.addSchema(1500, c);
        $$02.addFixer((DataFix)new bjh($$63, false));
        Schema $$64 = $$02.addSchema(1501, c);
        $$02.addFixer((DataFix)new bil($$64, false));
        Schema $$65 = $$02.addSchema(1502, c);
        $$02.addFixer((DataFix)new boy($$65, "Recipes fix", bqh.P, bia.b(bqe.a)));
        Schema $$66 = $$02.addSchema(1506, c);
        $$02.addFixer((DataFix)new boj($$66, false));
        Schema $$67 = $$02.addSchema(1510, btf::new);
        $$02.addFixer(bjp.a($$67, "Block renamening fix", bia.b(bmg.b)));
        $$02.addFixer(bno.a($$67, "Item renamening fix", bia.b(bmg.c)));
        $$02.addFixer((DataFix)new boy($$67, "Recipes renamening fix", bqh.P, bia.b(bqf.a)));
        $$02.addFixer((DataFix)new bmg($$67, true));
        $$02.addFixer((DataFix)new bra($$67, "SwimStatsRenameFix", (Map<String, String>)ImmutableMap.of((Object)"minecraft:swim_one_cm", (Object)"minecraft:walk_on_water_one_cm", (Object)"minecraft:dive_one_cm", (Object)"minecraft:walk_under_water_one_cm")));
        Schema $$68 = $$02.addSchema(1514, c);
        $$02.addFixer((DataFix)new bqt($$68, "ObjectiveDisplayNameFix", bqh.N));
        $$02.addFixer((DataFix)new bqt($$68, "TeamDisplayNameFix", bqh.O));
        $$02.addFixer((DataFix)new bpa($$68));
        Schema $$69 = $$02.addSchema(1515, c);
        $$02.addFixer(bjp.a($$69, "Rename coral fan blocks", bia.b(bqn.a)));
        Schema $$70 = $$02.addSchema(1624, c);
        $$02.addFixer((DataFix)new brk($$70, false));
        Schema $$71 = $$02.addSchema(1800, btg::new);
        $$02.addFixer((DataFix)new bik($$71, "Added 1.14 mobs fix", bqh.H));
        $$02.addFixer(bno.a($$71, "Rename dye items", bia.b(bkw.a)));
        Schema $$72 = $$02.addSchema(1801, bth::new);
        $$02.addFixer((DataFix)new bik($$72, "Added Illager Beast", bqh.H));
        Schema $$73 = $$02.addSchema(1802, c);
        $$02.addFixer(bjp.a($$73, "Rename sign blocks & stone slabs", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:stone_slab", (Object)"minecraft:smooth_stone_slab", (Object)"minecraft:sign", (Object)"minecraft:oak_sign", (Object)"minecraft:wall_sign", (Object)"minecraft:oak_wall_sign"))));
        $$02.addFixer(bno.a($$73, "Rename sign item & stone slabs", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:stone_slab", (Object)"minecraft:smooth_stone_slab", (Object)"minecraft:sign", (Object)"minecraft:oak_sign"))));
        Schema $$74 = $$02.addSchema(1803, c);
        $$02.addFixer((DataFix)new bnm($$74));
        Schema $$75 = $$02.addSchema(1904, bti::new);
        $$02.addFixer((DataFix)new bik($$75, "Added Cats", bqh.H));
        $$02.addFixer((DataFix)new ble($$75, false));
        Schema $$76 = $$02.addSchema(1905, c);
        $$02.addFixer((DataFix)new bkh($$76, false));
        Schema $$77 = $$02.addSchema(1906, btj::new);
        $$02.addFixer((DataFix)new bik($$77, "Add POI Blocks", bqh.w));
        Schema $$78 = $$02.addSchema(1909, btk::new);
        $$02.addFixer((DataFix)new bik($$78, "Add jigsaw", bqh.w));
        Schema $$79 = $$02.addSchema(1911, c);
        $$02.addFixer((DataFix)new bki($$79, false));
        Schema $$80 = $$02.addSchema(1914, c);
        $$02.addFixer((DataFix)new brw($$80, false));
        Schema $$81 = $$02.addSchema(1917, c);
        $$02.addFixer((DataFix)new bju($$81, false));
        Schema $$82 = $$02.addSchema(1918, c);
        $$02.addFixer((DataFix)new brq($$82, "minecraft:villager"));
        $$02.addFixer((DataFix)new brq($$82, "minecraft:zombie_villager"));
        Schema $$83 = $$02.addSchema(1920, btl::new);
        $$02.addFixer((DataFix)new boz($$83, false));
        $$02.addFixer((DataFix)new bik($$83, "Add campfire", bqh.w));
        Schema $$84 = $$02.addSchema(1925, c);
        $$02.addFixer((DataFix)new boq($$84));
        Schema $$85 = $$02.addSchema(1928, btm::new);
        $$02.addFixer((DataFix)new blw($$85, true));
        $$02.addFixer(bno.a($$85, "Rename ravager egg item", bia.b(blw.a)));
        Schema $$86 = $$02.addSchema(1929, btn::new);
        $$02.addFixer((DataFix)new bik($$86, "Add Wandering Trader and Trader Llama", bqh.H));
        Schema $$87 = $$02.addSchema(1931, bto::new);
        $$02.addFixer((DataFix)new bik($$87, "Added Fox", bqh.H));
        Schema $$88 = $$02.addSchema(1936, c);
        $$02.addFixer((DataFix)new bpf($$88, false));
        Schema $$89 = $$02.addSchema(1946, c);
        $$02.addFixer((DataFix)new bqp($$89, false));
        Schema $$90 = $$02.addSchema(1948, c);
        $$02.addFixer((DataFix)new bpd($$90));
        Schema $$91 = $$02.addSchema(1953, c);
        $$02.addFixer((DataFix)new bpb($$91, false));
        Schema $$92 = $$02.addSchema(1955, c);
        $$02.addFixer((DataFix)new brs($$92, false));
        $$02.addFixer((DataFix)new bse($$92, false));
        Schema $$93 = $$02.addSchema(1961, c);
        $$02.addFixer((DataFix)new bkd($$93, false));
        Schema $$94 = $$02.addSchema(1963, c);
        $$02.addFixer((DataFix)new bql($$94, false));
        Schema $$95 = $$02.addSchema(2100, btp::new);
        $$02.addFixer((DataFix)new bik($$95, "Added Bee and Bee Stinger", bqh.H));
        $$02.addFixer((DataFix)new bik($$95, "Add beehive", bqh.w));
        $$02.addFixer((DataFix)new boy($$95, "Rename sugar recipe", bqh.P, bia.a("minecraft:sugar", "minecraft:sugar_from_sugar_cane")));
        $$02.addFixer((DataFix)new bim($$95, false, "Rename sugar recipe advancement", bia.a("minecraft:recipes/misc/sugar", "minecraft:recipes/misc/sugar_from_sugar_cane")));
        Schema $$96 = $$02.addSchema(2202, c);
        $$02.addFixer((DataFix)new bjz($$96, false));
        Schema $$97 = $$02.addSchema(2209, c);
        UnaryOperator<String> $$98 = bia.a("minecraft:bee_hive", "minecraft:beehive");
        $$02.addFixer(bno.a($$97, "Rename bee_hive item to beehive", $$98));
        $$02.addFixer((DataFix)new bpz($$97, "Rename bee_hive poi to beehive", $$98));
        $$02.addFixer(bjp.a($$97, "Rename bee_hive block to beehive", $$98));
        Schema $$99 = $$02.addSchema(2211, c);
        $$02.addFixer((DataFix)new brc($$99, false));
        Schema $$100 = $$02.addSchema(2218, c);
        $$02.addFixer((DataFix)new bmx($$100, false));
        Schema $$101 = $$02.addSchema(2501, btq::new);
        $$02.addFixer((DataFix)new bmz($$101, true));
        Schema $$102 = $$02.addSchema(2502, btr::new);
        $$02.addFixer((DataFix)new bik($$102, "Added Hoglin", bqh.H));
        Schema $$103 = $$02.addSchema(2503, c);
        $$02.addFixer((DataFix)new brv($$103, false));
        $$02.addFixer((DataFix)new bim($$103, false, "Composter category change", bia.a("minecraft:recipes/misc/composter", "minecraft:recipes/decorations/composter")));
        Schema $$104 = $$02.addSchema(2505, bts::new);
        $$02.addFixer((DataFix)new bik($$104, "Added Piglin", bqh.H));
        $$02.addFixer((DataFix)new bor($$104, "minecraft:villager"));
        Schema $$105 = $$02.addSchema(2508, c);
        $$02.addFixer(bno.a($$105, "Renamed fungi items to fungus", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:warped_fungi", (Object)"minecraft:warped_fungus", (Object)"minecraft:crimson_fungi", (Object)"minecraft:crimson_fungus"))));
        $$02.addFixer(bjp.a($$105, "Renamed fungi blocks to fungus", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:warped_fungi", (Object)"minecraft:warped_fungus", (Object)"minecraft:crimson_fungi", (Object)"minecraft:crimson_fungus"))));
        Schema $$106 = $$02.addSchema(2509, btt::new);
        $$02.addFixer((DataFix)new bmn($$106));
        $$02.addFixer(bno.a($$106, "Rename zombie pigman egg item", bia.b(bmn.a)));
        Schema $$107 = $$02.addSchema(2511, c);
        $$02.addFixer((DataFix)new blu($$107));
        Schema $$108 = $$02.addSchema(2511, 1, btu::new);
        $$02.addFixer((DataFix)new bov($$108, "SplashPotionItemFieldRenameFix", bqh.H, "minecraft:potion"));
        Schema $$109 = $$02.addSchema(2514, c);
        $$02.addFixer((DataFix)new bmi($$109));
        $$02.addFixer((DataFix)new bjl($$109));
        $$02.addFixer((DataFix)new bpx($$109));
        $$02.addFixer((DataFix)new bom($$109));
        $$02.addFixer((DataFix)new bqs($$109));
        $$02.addFixer((DataFix)new bnz($$109));
        Schema $$110 = $$02.addSchema(2516, c);
        $$02.addFixer((DataFix)new bnc($$110, "minecraft:villager"));
        $$02.addFixer((DataFix)new bnc($$110, "minecraft:zombie_villager"));
        Schema $$111 = $$02.addSchema(2518, c);
        $$02.addFixer((DataFix)new bob($$111, false));
        $$02.addFixer((DataFix)new boc($$111));
        Schema $$112 = $$02.addSchema(2519, btv::new);
        $$02.addFixer((DataFix)new bik($$112, "Added Strider", bqh.H));
        Schema $$113 = $$02.addSchema(2522, btw::new);
        $$02.addFixer((DataFix)new bik($$113, "Added Zoglin", bqh.H));
        Schema $$114 = $$02.addSchema(2523, c);
        $$02.addFixer((DataFix)new bis($$114, "Attribute renames", bia.a((Map<String, String>)ImmutableMap.builder().put((Object)"generic.maxHealth", (Object)"minecraft:generic.max_health").put((Object)"Max Health", (Object)"minecraft:generic.max_health").put((Object)"zombie.spawnReinforcements", (Object)"minecraft:zombie.spawn_reinforcements").put((Object)"Spawn Reinforcements Chance", (Object)"minecraft:zombie.spawn_reinforcements").put((Object)"horse.jumpStrength", (Object)"minecraft:horse.jump_strength").put((Object)"Jump Strength", (Object)"minecraft:horse.jump_strength").put((Object)"generic.followRange", (Object)"minecraft:generic.follow_range").put((Object)"Follow Range", (Object)"minecraft:generic.follow_range").put((Object)"generic.knockbackResistance", (Object)"minecraft:generic.knockback_resistance").put((Object)"Knockback Resistance", (Object)"minecraft:generic.knockback_resistance").put((Object)"generic.movementSpeed", (Object)"minecraft:generic.movement_speed").put((Object)"Movement Speed", (Object)"minecraft:generic.movement_speed").put((Object)"generic.flyingSpeed", (Object)"minecraft:generic.flying_speed").put((Object)"Flying Speed", (Object)"minecraft:generic.flying_speed").put((Object)"generic.attackDamage", (Object)"minecraft:generic.attack_damage").put((Object)"generic.attackKnockback", (Object)"minecraft:generic.attack_knockback").put((Object)"generic.attackSpeed", (Object)"minecraft:generic.attack_speed").put((Object)"generic.armorToughness", (Object)"minecraft:generic.armor_toughness").build())));
        Schema $$115 = $$02.addSchema(2527, c);
        $$02.addFixer((DataFix)new biy($$115));
        Schema $$116 = $$02.addSchema(2528, c);
        $$02.addFixer(bno.a($$116, "Rename soul fire torch and soul fire lantern", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:soul_fire_torch", (Object)"minecraft:soul_torch", (Object)"minecraft:soul_fire_lantern", (Object)"minecraft:soul_lantern"))));
        $$02.addFixer(bjp.a($$116, "Rename soul fire torch and soul fire lantern", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:soul_fire_torch", (Object)"minecraft:soul_torch", (Object)"minecraft:soul_fire_wall_torch", (Object)"minecraft:soul_wall_torch", (Object)"minecraft:soul_fire_lantern", (Object)"minecraft:soul_lantern"))));
        Schema $$117 = $$02.addSchema(2529, c);
        $$02.addFixer((DataFix)new brb($$117, false));
        Schema $$118 = $$02.addSchema(2531, c);
        $$02.addFixer((DataFix)new bqg($$118));
        Schema $$119 = $$02.addSchema(2533, c);
        $$02.addFixer((DataFix)new brr($$119));
        Schema $$120 = $$02.addSchema(2535, c);
        $$02.addFixer((DataFix)new bmc($$120));
        Schema $$121 = $$02.addSchema(2537, c);
        $$02.addFixer((DataFix)new bof($$121));
        Schema $$1222 = $$02.addSchema(2538, c);
        $$02.addFixer((DataFix)new bol($$1222));
        Schema $$123 = $$02.addSchema(2550, c);
        $$02.addFixer((DataFix)new brz($$123));
        Schema $$124 = $$02.addSchema(2551, btx::new);
        $$02.addFixer((DataFix)new bsc($$124, "add types to WorldGenData", bqh.S));
        Schema $$125 = $$02.addSchema(2552, c);
        $$02.addFixer((DataFix)new boy($$125, "Nether biome rename", bqh.Q, bia.a("minecraft:nether", "minecraft:nether_wastes")));
        Schema $$126 = $$02.addSchema(2553, c);
        $$02.addFixer((DataFix)new boy($$126, "Biomes fix", bqh.Q, bia.b(bix.a)));
        Schema $$127 = $$02.addSchema(2556, c);
        $$02.addFixer((DataFix)new bph($$127));
        Schema $$128 = $$02.addSchema(2558, c);
        $$02.addFixer((DataFix)new bos($$128, false));
        $$02.addFixer((DataFix)new bpq($$128, false, "Rename swapHands setting", "key_key.swapHands", "key_key.swapOffhand"));
        Schema $$129 = $$02.addSchema(2568, bty::new);
        $$02.addFixer((DataFix)new bik($$129, "Added Piglin Brute", bqh.H));
        Schema $$130 = $$02.addSchema(2571, btz::new);
        $$02.addFixer((DataFix)new bik($$130, "Added Goat", bqh.H));
        Schema $$131 = $$02.addSchema(2679, c);
        $$02.addFixer((DataFix)new bjv($$131, false));
        Schema $$132 = $$02.addSchema(2680, c);
        $$02.addFixer(bno.a($$132, "Renamed grass path item to dirt path", bia.a("minecraft:grass_path", "minecraft:dirt_path")));
        $$02.addFixer(bjp.a($$132, "Renamed grass path block to dirt path", bia.a("minecraft:grass_path", "minecraft:dirt_path")));
        Schema $$133 = $$02.addSchema(2684, bua::new);
        $$02.addFixer((DataFix)new bik($$133, "Added Sculk Sensor", bqh.w));
        Schema $$134 = $$02.addSchema(2686, bub::new);
        $$02.addFixer((DataFix)new bik($$134, "Added Axolotl", bqh.H));
        Schema $$135 = $$02.addSchema(2688, buc::new);
        $$02.addFixer((DataFix)new bik($$135, "Added Glow Squid", bqh.H));
        $$02.addFixer((DataFix)new bik($$135, "Added Glow Item Frame", bqh.H));
        Schema $$136 = $$02.addSchema(2690, c);
        ImmutableMap $$137 = ImmutableMap.builder().put((Object)"minecraft:weathered_copper_block", (Object)"minecraft:oxidized_copper_block").put((Object)"minecraft:semi_weathered_copper_block", (Object)"minecraft:weathered_copper_block").put((Object)"minecraft:lightly_weathered_copper_block", (Object)"minecraft:exposed_copper_block").put((Object)"minecraft:weathered_cut_copper", (Object)"minecraft:oxidized_cut_copper").put((Object)"minecraft:semi_weathered_cut_copper", (Object)"minecraft:weathered_cut_copper").put((Object)"minecraft:lightly_weathered_cut_copper", (Object)"minecraft:exposed_cut_copper").put((Object)"minecraft:weathered_cut_copper_stairs", (Object)"minecraft:oxidized_cut_copper_stairs").put((Object)"minecraft:semi_weathered_cut_copper_stairs", (Object)"minecraft:weathered_cut_copper_stairs").put((Object)"minecraft:lightly_weathered_cut_copper_stairs", (Object)"minecraft:exposed_cut_copper_stairs").put((Object)"minecraft:weathered_cut_copper_slab", (Object)"minecraft:oxidized_cut_copper_slab").put((Object)"minecraft:semi_weathered_cut_copper_slab", (Object)"minecraft:weathered_cut_copper_slab").put((Object)"minecraft:lightly_weathered_cut_copper_slab", (Object)"minecraft:exposed_cut_copper_slab").put((Object)"minecraft:waxed_semi_weathered_copper", (Object)"minecraft:waxed_weathered_copper").put((Object)"minecraft:waxed_lightly_weathered_copper", (Object)"minecraft:waxed_exposed_copper").put((Object)"minecraft:waxed_semi_weathered_cut_copper", (Object)"minecraft:waxed_weathered_cut_copper").put((Object)"minecraft:waxed_lightly_weathered_cut_copper", (Object)"minecraft:waxed_exposed_cut_copper").put((Object)"minecraft:waxed_semi_weathered_cut_copper_stairs", (Object)"minecraft:waxed_weathered_cut_copper_stairs").put((Object)"minecraft:waxed_lightly_weathered_cut_copper_stairs", (Object)"minecraft:waxed_exposed_cut_copper_stairs").put((Object)"minecraft:waxed_semi_weathered_cut_copper_slab", (Object)"minecraft:waxed_weathered_cut_copper_slab").put((Object)"minecraft:waxed_lightly_weathered_cut_copper_slab", (Object)"minecraft:waxed_exposed_cut_copper_slab").build();
        $$02.addFixer(bno.a($$136, "Renamed copper block items to new oxidized terms", bia.b((Map<String, String>)$$137)));
        $$02.addFixer(bjp.a($$136, "Renamed copper blocks to new oxidized terms", bia.b((Map<String, String>)$$137)));
        Schema $$138 = $$02.addSchema(2691, c);
        ImmutableMap $$139 = ImmutableMap.builder().put((Object)"minecraft:waxed_copper", (Object)"minecraft:waxed_copper_block").put((Object)"minecraft:oxidized_copper_block", (Object)"minecraft:oxidized_copper").put((Object)"minecraft:weathered_copper_block", (Object)"minecraft:weathered_copper").put((Object)"minecraft:exposed_copper_block", (Object)"minecraft:exposed_copper").build();
        $$02.addFixer(bno.a($$138, "Rename copper item suffixes", bia.b((Map<String, String>)$$139)));
        $$02.addFixer(bjp.a($$138, "Rename copper blocks suffixes", bia.b((Map<String, String>)$$139)));
        Schema $$140 = $$02.addSchema(2693, c);
        $$02.addFixer((DataFix)new bij($$140, bqh.S, "has_increased_height_already", false));
        Schema $$141 = $$02.addSchema(2696, c);
        ImmutableMap $$142 = ImmutableMap.builder().put((Object)"minecraft:grimstone", (Object)"minecraft:deepslate").put((Object)"minecraft:grimstone_slab", (Object)"minecraft:cobbled_deepslate_slab").put((Object)"minecraft:grimstone_stairs", (Object)"minecraft:cobbled_deepslate_stairs").put((Object)"minecraft:grimstone_wall", (Object)"minecraft:cobbled_deepslate_wall").put((Object)"minecraft:polished_grimstone", (Object)"minecraft:polished_deepslate").put((Object)"minecraft:polished_grimstone_slab", (Object)"minecraft:polished_deepslate_slab").put((Object)"minecraft:polished_grimstone_stairs", (Object)"minecraft:polished_deepslate_stairs").put((Object)"minecraft:polished_grimstone_wall", (Object)"minecraft:polished_deepslate_wall").put((Object)"minecraft:grimstone_tiles", (Object)"minecraft:deepslate_tiles").put((Object)"minecraft:grimstone_tile_slab", (Object)"minecraft:deepslate_tile_slab").put((Object)"minecraft:grimstone_tile_stairs", (Object)"minecraft:deepslate_tile_stairs").put((Object)"minecraft:grimstone_tile_wall", (Object)"minecraft:deepslate_tile_wall").put((Object)"minecraft:grimstone_bricks", (Object)"minecraft:deepslate_bricks").put((Object)"minecraft:grimstone_brick_slab", (Object)"minecraft:deepslate_brick_slab").put((Object)"minecraft:grimstone_brick_stairs", (Object)"minecraft:deepslate_brick_stairs").put((Object)"minecraft:grimstone_brick_wall", (Object)"minecraft:deepslate_brick_wall").put((Object)"minecraft:chiseled_grimstone", (Object)"minecraft:chiseled_deepslate").build();
        $$02.addFixer(bno.a($$141, "Renamed grimstone block items to deepslate", bia.b((Map<String, String>)$$142)));
        $$02.addFixer(bjp.a($$141, "Renamed grimstone blocks to deepslate", bia.b((Map<String, String>)$$142)));
        Schema $$143 = $$02.addSchema(2700, c);
        $$02.addFixer(bjp.a($$143, "Renamed cave vines blocks", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:cave_vines_head", (Object)"minecraft:cave_vines", (Object)"minecraft:cave_vines_body", (Object)"minecraft:cave_vines_plant"))));
        Schema $$144 = $$02.addSchema(2701, c);
        $$02.addFixer((DataFix)new bqr($$144));
        Schema $$145 = $$02.addSchema(2702, c);
        $$02.addFixer((DataFix)new bie($$145));
        Schema $$146 = $$02.addSchema(2704, bud::new);
        $$02.addFixer((DataFix)new bik($$146, "Added Goat", bqh.H));
        Schema $$147 = $$02.addSchema(2707, bue::new);
        $$02.addFixer((DataFix)new bik($$147, "Added Marker", bqh.H));
        $$02.addFixer((DataFix)new bij($$147, bqh.S, "has_increased_height_already", true));
        Schema $$148 = $$02.addSchema(2710, c);
        $$02.addFixer((DataFix)new bra($$148, "Renamed play_one_minute stat to play_time", (Map<String, String>)ImmutableMap.of((Object)"minecraft:play_one_minute", (Object)"minecraft:play_time")));
        Schema $$149 = $$02.addSchema(2717, c);
        $$02.addFixer(bno.a($$149, "Rename azalea_leaves_flowers", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:azalea_leaves_flowers", (Object)"minecraft:flowering_azalea_leaves"))));
        $$02.addFixer(bjp.a($$149, "Rename azalea_leaves_flowers items", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:azalea_leaves_flowers", (Object)"minecraft:flowering_azalea_leaves"))));
        Schema $$150 = $$02.addSchema(2825, c);
        $$02.addFixer((DataFix)new bij($$150, bqh.S, "has_increased_height_already", false));
        Schema $$151 = $$02.addSchema(2831, buf::new);
        $$02.addFixer((DataFix)new bqy($$151));
        Schema $$152 = $$02.addSchema(2832, bug::new);
        $$02.addFixer((DataFix)new bsa($$152));
        $$02.addFixer((DataFix)new bkc($$152));
        Schema $$153 = $$02.addSchema(2833, c);
        $$02.addFixer((DataFix)new bry($$153));
        Schema $$154 = $$02.addSchema(2838, c);
        $$02.addFixer((DataFix)new boy($$154, "Caves and Cliffs biome renames", bqh.Q, bia.b(bjw.a)));
        Schema $$155 = $$02.addSchema(2841, c);
        $$02.addFixer((DataFix)new bkf($$155));
        Schema $$156 = $$02.addSchema(2842, buh::new);
        $$02.addFixer((DataFix)new bkg($$156));
        Schema $$157 = $$02.addSchema(2843, c);
        $$02.addFixer((DataFix)new bps($$157));
        $$02.addFixer((DataFix)new boy($$157, "Remove Deep Warm Ocean", bqh.Q, bia.a("minecraft:deep_warm_ocean", "minecraft:warm_ocean")));
        Schema $$158 = $$02.addSchema(2846, c);
        $$02.addFixer((DataFix)new bim($$158, false, "Rename some C&C part 2 advancements", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:husbandry/play_jukebox_in_meadows", (Object)"minecraft:adventure/play_jukebox_in_meadows", (Object)"minecraft:adventure/caves_and_cliff", (Object)"minecraft:adventure/fall_from_world_height", (Object)"minecraft:adventure/ride_strider_in_overworld_lava", (Object)"minecraft:nether/ride_strider_in_overworld_lava"))));
        Schema $$159 = $$02.addSchema(2852, c);
        $$02.addFixer((DataFix)new bry($$159));
        Schema $$160 = $$02.addSchema(2967, c);
        $$02.addFixer((DataFix)new brd($$160));
        Schema $$161 = $$02.addSchema(2970, c);
        $$02.addFixer((DataFix)new bre($$161));
        Schema $$162 = $$02.addSchema(3076, bui::new);
        $$02.addFixer((DataFix)new bik($$162, "Added Sculk Catalyst", bqh.w));
        Schema $$163 = $$02.addSchema(3077, c);
        $$02.addFixer((DataFix)new bka($$163));
        Schema $$164 = $$02.addSchema(3078, buj::new);
        $$02.addFixer((DataFix)new bik($$164, "Added Frog", bqh.H));
        $$02.addFixer((DataFix)new bik($$164, "Added Tadpole", bqh.H));
        $$02.addFixer((DataFix)new bik($$164, "Added Sculk Shrieker", bqh.w));
        Schema $$165 = $$02.addSchema(3081, buk::new);
        $$02.addFixer((DataFix)new bik($$165, "Added Warden", bqh.H));
        Schema $$166 = $$02.addSchema(3082, bul::new);
        $$02.addFixer((DataFix)new bik($$166, "Added Chest Boat", bqh.H));
        Schema $$167 = $$02.addSchema(3083, bum::new);
        $$02.addFixer((DataFix)new bik($$167, "Added Allay", bqh.H));
        Schema $$168 = $$02.addSchema(3084, c);
        $$02.addFixer((DataFix)new boy($$168, "game_event_renames_3084", bqh.K, bia.b((Map<String, String>)ImmutableMap.builder().put((Object)"minecraft:block_press", (Object)"minecraft:block_activate").put((Object)"minecraft:block_switch", (Object)"minecraft:block_activate").put((Object)"minecraft:block_unpress", (Object)"minecraft:block_deactivate").put((Object)"minecraft:block_unswitch", (Object)"minecraft:block_deactivate").put((Object)"minecraft:drinking_finish", (Object)"minecraft:drink").put((Object)"minecraft:elytra_free_fall", (Object)"minecraft:elytra_glide").put((Object)"minecraft:entity_damaged", (Object)"minecraft:entity_damage").put((Object)"minecraft:entity_dying", (Object)"minecraft:entity_die").put((Object)"minecraft:entity_killed", (Object)"minecraft:entity_die").put((Object)"minecraft:mob_interact", (Object)"minecraft:entity_interact").put((Object)"minecraft:ravager_roar", (Object)"minecraft:entity_roar").put((Object)"minecraft:ring_bell", (Object)"minecraft:block_change").put((Object)"minecraft:shulker_close", (Object)"minecraft:container_close").put((Object)"minecraft:shulker_open", (Object)"minecraft:container_open").put((Object)"minecraft:wolf_shaking", (Object)"minecraft:entity_shake").build())));
        Schema $$169 = $$02.addSchema(3086, c);
        $$02.addFixer((DataFix)new bmj($$169, "Change cat variant type", bqh.H, "minecraft:cat", "CatType", arg_0 -> ((Int2ObjectOpenHashMap)bhs.a(new Int2ObjectOpenHashMap(), (? super T $$0) -> {
            $$0.defaultReturnValue((Object)"minecraft:tabby");
            $$0.put(0, (Object)"minecraft:tabby");
            $$0.put(1, (Object)"minecraft:black");
            $$0.put(2, (Object)"minecraft:red");
            $$0.put(3, (Object)"minecraft:siamese");
            $$0.put(4, (Object)"minecraft:british");
            $$0.put(5, (Object)"minecraft:calico");
            $$0.put(6, (Object)"minecraft:persian");
            $$0.put(7, (Object)"minecraft:ragdoll");
            $$0.put(8, (Object)"minecraft:white");
            $$0.put(9, (Object)"minecraft:jellie");
            $$0.put(10, (Object)"minecraft:all_black");
        })).get(arg_0)));
        ImmutableMap $$170 = ImmutableMap.builder().put((Object)"textures/entity/cat/tabby.png", (Object)"minecraft:tabby").put((Object)"textures/entity/cat/black.png", (Object)"minecraft:black").put((Object)"textures/entity/cat/red.png", (Object)"minecraft:red").put((Object)"textures/entity/cat/siamese.png", (Object)"minecraft:siamese").put((Object)"textures/entity/cat/british_shorthair.png", (Object)"minecraft:british").put((Object)"textures/entity/cat/calico.png", (Object)"minecraft:calico").put((Object)"textures/entity/cat/persian.png", (Object)"minecraft:persian").put((Object)"textures/entity/cat/ragdoll.png", (Object)"minecraft:ragdoll").put((Object)"textures/entity/cat/white.png", (Object)"minecraft:white").put((Object)"textures/entity/cat/jellie.png", (Object)"minecraft:jellie").put((Object)"textures/entity/cat/all_black.png", (Object)"minecraft:all_black").build();
        $$02.addFixer((DataFix)new bkp($$169, "Migrate cat variant advancement", "minecraft:husbandry/complete_catalogue", $$1 -> (String)$$170.getOrDefault($$1, $$1)));
        Schema $$171 = $$02.addSchema(3087, c);
        $$02.addFixer((DataFix)new bmj($$171, "Change frog variant type", bqh.H, "minecraft:frog", "Variant", arg_0 -> ((Int2ObjectOpenHashMap)bhs.a(new Int2ObjectOpenHashMap(), (? super T $$0) -> {
            $$0.put(0, (Object)"minecraft:temperate");
            $$0.put(1, (Object)"minecraft:warm");
            $$0.put(2, (Object)"minecraft:cold");
        })).get(arg_0)));
        Schema $$172 = $$02.addSchema(3090, c);
        $$02.addFixer((DataFix)new blk($$172, "EntityPaintingFieldsRenameFix", "minecraft:painting", Map.of("Motive", "variant", "Facing", "facing")));
        Schema $$173 = $$02.addSchema(3093, c);
        $$02.addFixer((DataFix)new bll($$173));
        Schema $$174 = $$02.addSchema(3094, c);
        $$02.addFixer((DataFix)new bnb($$174));
        Schema $$175 = $$02.addSchema(3097, c);
        $$02.addFixer((DataFix)new bmr($$175));
        $$02.addFixer((DataFix)new bms($$175));
        Map<String, String> $$176 = Map.of("minecraft:british", "minecraft:british_shorthair");
        $$02.addFixer((DataFix)new brp($$175, "Rename british shorthair", bqh.H, "minecraft:cat", $$176));
        $$02.addFixer((DataFix)new bkp($$175, "Migrate cat variant advancement for british shorthair", "minecraft:husbandry/complete_catalogue", $$1 -> $$176.getOrDefault($$1, (String)$$1)));
        $$02.addFixer((DataFix)new bpy($$175, "Remove unpopulated villager PoI types", Set.of("minecraft:unemployed", "minecraft:nitwit")::contains));
        Schema $$177 = $$02.addSchema(3108, c);
        $$02.addFixer((DataFix)new bja($$177));
        Schema $$178 = $$02.addSchema(3201, c);
        $$02.addFixer((DataFix)new bpp($$178));
        Schema $$179 = $$02.addSchema(3202, bun::new);
        $$02.addFixer((DataFix)new bik($$179, "Added Hanging Sign", bqh.w));
        Schema $$180 = $$02.addSchema(3203, buo::new);
        $$02.addFixer((DataFix)new bik($$180, "Added Camel", bqh.H));
        Schema $$181 = $$02.addSchema(3204, bup::new);
        $$02.addFixer((DataFix)new bik($$181, "Added Chiseled Bookshelf", bqh.w));
        Schema $$182 = $$02.addSchema(3209, c);
        $$02.addFixer((DataFix)new bnv($$182, false, "minecraft:pig_spawn_egg"));
        Schema $$183 = $$02.addSchema(3214, c);
        $$02.addFixer((DataFix)new bpg($$183));
        Schema $$184 = $$02.addSchema(3319, c);
        $$02.addFixer((DataFix)new bpe($$184));
        Schema $$185 = $$02.addSchema(3322, c);
        $$02.addFixer((DataFix)new bkx($$185));
        Schema $$186 = $$02.addSchema(3325, buq::new);
        $$02.addFixer((DataFix)new bik($$186, "Added displays", bqh.H));
        Schema $$187 = $$02.addSchema(3326, bur::new);
        $$02.addFixer((DataFix)new bik($$187, "Added Sniffer", bqh.H));
        Schema $$188 = $$02.addSchema(3327, bus::new);
        $$02.addFixer((DataFix)new bik($$188, "Archaeology", bqh.w));
        Schema $$189 = $$02.addSchema(3328, but::new);
        $$02.addFixer((DataFix)new bik($$189, "Added interaction", bqh.H));
        Schema $$190 = $$02.addSchema(3438, buu::new);
        $$02.addFixer(bji.a($$190, "Rename Suspicious Sand to Brushable Block", bia.a("minecraft:suspicious_sand", "minecraft:brushable_block")));
        $$02.addFixer((DataFix)new bld($$190));
        $$02.addFixer(bno.a($$190, "Pottery shard renaming", bia.b((Map<String, String>)ImmutableMap.of((Object)"minecraft:pottery_shard_archer", (Object)"minecraft:archer_pottery_shard", (Object)"minecraft:pottery_shard_prize", (Object)"minecraft:prize_pottery_shard", (Object)"minecraft:pottery_shard_arms_up", (Object)"minecraft:arms_up_pottery_shard", (Object)"minecraft:pottery_shard_skull", (Object)"minecraft:skull_pottery_shard"))));
        $$02.addFixer((DataFix)new bik($$190, "Added calibrated sculk sensor", bqh.w));
        Schema $$191 = $$02.addSchema(3439, buv::new);
        $$02.addFixer((DataFix)new bjk($$191, "Updated sign text format for Signs", "minecraft:sign"));
        Schema $$192 = $$02.addSchema(3439, 1, buw::new);
        $$02.addFixer((DataFix)new bjk($$192, "Updated sign text format for Hanging Signs", "minecraft:hanging_sign"));
        Schema $$193 = $$02.addSchema(3440, c);
        $$02.addFixer((DataFix)new boy($$193, "Replace experimental 1.20 overworld", bqh.R, bia.a("minecraft:overworld_update_1_20", "minecraft:overworld")));
        $$02.addFixer((DataFix)new bmq($$193, "Remove 1.20 feature toggle", Set.of("minecraft:update_1_20")));
        Schema $$194 = $$02.addSchema(3447, c);
        $$02.addFixer(bno.a($$194, "Pottery shard item renaming to Pottery sherd", bia.b(Stream.of("minecraft:angler_pottery_shard", "minecraft:archer_pottery_shard", "minecraft:arms_up_pottery_shard", "minecraft:blade_pottery_shard", "minecraft:brewer_pottery_shard", "minecraft:burn_pottery_shard", "minecraft:danger_pottery_shard", "minecraft:explorer_pottery_shard", "minecraft:friend_pottery_shard", "minecraft:heart_pottery_shard", "minecraft:heartbreak_pottery_shard", "minecraft:howl_pottery_shard", "minecraft:miner_pottery_shard", "minecraft:mourner_pottery_shard", "minecraft:plenty_pottery_shard", "minecraft:prize_pottery_shard", "minecraft:sheaf_pottery_shard", "minecraft:shelter_pottery_shard", "minecraft:skull_pottery_shard", "minecraft:snort_pottery_shard").collect(Collectors.toMap(Function.identity(), $$0 -> $$0.replace("_pottery_shard", "_pottery_sherd"))))));
        Schema $$195 = $$02.addSchema(3448, bux::new);
        $$02.addFixer((DataFix)new bkt($$195));
        Schema $$196 = $$02.addSchema(3450, c);
        $$02.addFixer((DataFix)new bqi($$196, "Remove liquid_carvers and heightmap chunk statuses", bia.b(Map.of("minecraft:liquid_carvers", "minecraft:carvers", "minecraft:heightmaps", "minecraft:spawn"))));
        Schema $$197 = $$02.addSchema(3451, c);
        $$02.addFixer((DataFix)new bkb($$197));
        Schema $$198 = $$02.addSchema(3459, c);
        $$02.addFixer((DataFix)new bog($$198));
        Schema $$199 = $$02.addSchema(3564, c);
        $$02.addFixer((DataFix)new bkv($$199, "minecraft:sign"));
        Schema $$200 = $$02.addSchema(3564, 1, c);
        $$02.addFixer((DataFix)new bkv($$200, "minecraft:hanging_sign"));
        Schema $$201 = $$02.addSchema(3565, c);
        $$02.addFixer((DataFix)new bqd($$201));
        Schema $$202 = $$02.addSchema(3566, c);
        $$02.addFixer((DataFix)new bqu($$202));
        Schema $$203 = $$02.addSchema(3568, c);
        $$02.addFixer((DataFix)new bot($$203));
        Schema $$204 = $$02.addSchema(3682, buy::new);
        $$02.addFixer((DataFix)new bik($$204, "Added Crafter", bqh.w));
        Schema $$205 = $$02.addSchema(3683, buz::new);
        $$02.addFixer((DataFix)new bqa($$205));
        Schema $$206 = $$02.addSchema(3685, bva::new);
        $$02.addFixer((DataFix)new bmu($$206));
        Schema $$207 = $$02.addSchema(3689, bvb::new);
        $$02.addFixer((DataFix)new bik($$207, "Added Breeze", bqh.H));
        $$02.addFixer((DataFix)new bik($$207, "Added Trial Spawner", bqh.w));
        Schema $$208 = $$02.addSchema(3692, c);
        UnaryOperator<String> $$209 = bia.b(Map.of("minecraft:grass", "minecraft:short_grass"));
        $$02.addFixer(bjp.a($$208, "Rename grass block to short_grass", $$209));
        $$02.addFixer(bno.a($$208, "Rename grass item to short_grass", $$209));
        Schema $$210 = $$02.addSchema(3799, bvc::new);
        $$02.addFixer((DataFix)new bik($$210, "Added Armadillo", bqh.H));
        Schema $$211 = $$02.addSchema(3800, c);
        UnaryOperator<String> $$212 = bia.b(Map.of("minecraft:scute", "minecraft:turtle_scute"));
        $$02.addFixer(bno.a($$211, "Rename scute item to turtle_scute", $$212));
        Schema $$213 = $$02.addSchema(3803, c);
        $$02.addFixer((DataFix)new bqm($$213, "Rename sweeping enchant to sweeping_edge", Map.of("minecraft:sweeping", "minecraft:sweeping_edge")));
        Schema $$214 = $$02.addSchema(3807, bvd::new);
        $$02.addFixer((DataFix)new bik($$214, "Added Vault", bqh.w));
        Schema $$215 = $$02.addSchema(3807, 1, c);
        $$02.addFixer((DataFix)new bop($$215));
        Schema $$216 = $$02.addSchema(3808, bve::new);
        $$02.addFixer((DataFix)new bne($$216, "minecraft:horse", "ArmorItem", true));
        Schema $$217 = $$02.addSchema(3808, 1, bvf::new);
        $$02.addFixer((DataFix)new bne($$217, "minecraft:llama", "DecorItem", false));
        Schema $$218 = $$02.addSchema(3808, 2, bvg::new);
        $$02.addFixer((DataFix)new bne($$218, "minecraft:trader_llama", "DecorItem", false));
        Schema $$219 = $$02.addSchema(3809, c);
        $$02.addFixer((DataFix)new bjx($$219));
        Schema $$220 = $$02.addSchema(3812, c);
        $$02.addFixer((DataFix)new bmv($$220));
        Schema $$221 = $$02.addSchema(3813, bvh::new);
        $$02.addFixer((DataFix)new bjn($$221));
        Schema $$222 = $$02.addSchema(3814, c);
        $$02.addFixer((DataFix)new bis($$222, "Rename jump strength attribute", bia.a("minecraft:horse.jump_strength", "minecraft:generic.jump_strength")));
        Schema $$223 = $$02.addSchema(3816, bvi::new);
        $$02.addFixer((DataFix)new bik($$223, "Added Bogged", bqh.H));
        Schema $$224 = $$02.addSchema(3818, bvj::new);
        $$02.addFixer((DataFix)new biw($$224));
        $$02.addFixer((DataFix)new bky($$224));
        Schema $$225 = $$02.addSchema(3818, 1, c);
        $$02.addFixer((DataFix)new biu($$225));
        Schema $$226 = $$02.addSchema(3818, 2, c);
        $$02.addFixer((DataFix)new bri($$226));
        Schema $$227 = $$02.addSchema(3818, 3, bvk::new);
        $$02.addFixer((DataFix)new bsc($$227, "Inject data component types", bqh.A));
        Schema $$228 = $$02.addSchema(3818, 4, bvl::new);
        $$02.addFixer((DataFix)new bpt($$228));
        Schema $$229 = $$02.addSchema(3818, 5, bvm::new);
        $$02.addFixer((DataFix)new bnr($$229));
        Schema $$230 = $$02.addSchema(3818, 6, c);
        $$02.addFixer((DataFix)new bio($$230));
        Schema $$231 = $$02.addSchema(3820, c);
        $$02.addFixer((DataFix)new bpv($$231));
        $$02.addFixer((DataFix)new boo($$231));
        Schema $$232 = $$02.addSchema(3825, bvn::new);
        $$02.addFixer((DataFix)new bns($$232));
        $$02.addFixer((DataFix)new bit($$232));
        $$02.addFixer((DataFix)new brl($$232));
        $$02.addFixer((DataFix)new bik($$232, "Added Ominous Item Spawner", bqh.H));
        Schema $$233 = $$02.addSchema(3828, c);
        $$02.addFixer((DataFix)new bkz($$233));
        Schema $$234 = $$02.addSchema(3833, c);
        $$02.addFixer((DataFix)new bqk($$234));
        Schema $$235 = $$02.addSchema(3938, bvo::new);
        $$02.addFixer((DataFix)new bqb($$235));
        Schema $$236 = $$02.addSchema(3939, c);
        $$02.addFixer((DataFix)new bmq($$236, "Remove 1.21 feature toggle", Set.of("minecraft:update_1_21")));
        Schema $$237 = $$02.addSchema(3943, c);
        $$02.addFixer((DataFix)new bpn($$237));
        Schema $$238 = $$02.addSchema(3945, c);
        $$02.addFixer((DataFix)new biq($$238));
        $$02.addFixer((DataFix)new bod($$238));
        Schema $$239 = $$02.addSchema(4054, c);
        $$02.addFixer((DataFix)new bpc($$239));
        Schema $$240 = $$02.addSchema(4055, c);
        $$02.addFixer((DataFix)new bip($$240));
        Schema $$241 = $$02.addSchema(4057, c);
        $$02.addFixer((DataFix)new bjt($$241));
        Schema $$242 = $$02.addSchema(4059, bvp::new);
        $$02.addFixer((DataFix)new bmw($$242));
        Schema $$243 = $$02.addSchema(4061, c);
        $$02.addFixer((DataFix)new brm($$243));
        Schema $$244 = $$02.addSchema(4064, c);
        $$02.addFixer((DataFix)new bmt($$244));
        Schema $$245 = $$02.addSchema(4067, bvq::new);
        $$02.addFixer((DataFix)new bjs($$245));
        $$02.addFixer((DataFix)new bmq($$245, "Remove Bundle experimental feature flag", Set.of("minecraft:bundle")));
        Schema $$246 = $$02.addSchema(4068, c);
        $$02.addFixer((DataFix)new bon($$246));
        $$02.addFixer((DataFix)new bkn($$246));
        Schema $$247 = $$02.addSchema(4070, bvr::new);
        $$02.addFixer((DataFix)new bik($$247, "Added Pale Oak Boat and Pale Oak Chest Boat", bqh.H));
        Schema $$248 = $$02.addSchema(4071, bvs::new);
        $$02.addFixer((DataFix)new bik($$248, "Added Creaking", bqh.H));
        $$02.addFixer((DataFix)new bik($$248, "Added Creaking Heart", bqh.w));
        Schema $$249 = $$02.addSchema(4081, c);
        $$02.addFixer((DataFix)new bma($$249));
        Schema $$250 = $$02.addSchema(4173, c);
        $$02.addFixer((DataFix)new blk($$250, "Rename TNT Minecart fuse", "minecraft:tnt_minecart", Map.of("TNTFuse", "fuse")));
        Schema $$251 = $$02.addSchema(4175, c);
        $$02.addFixer((DataFix)new bmp($$251));
        $$02.addFixer((DataFix)new bkq($$251));
        Schema $$252 = $$02.addSchema(4176, c);
        $$02.addFixer((DataFix)new bnh($$252));
        $$02.addFixer((DataFix)new bni($$252));
        Schema $$253 = $$02.addSchema(4180, c);
        $$02.addFixer((DataFix)new bmq($$253, "Remove Winter Drop toggle", Set.of("minecraft:winter_drop")));
        Schema $$254 = $$02.addSchema(4181, c);
        $$02.addFixer((DataFix)new bje($$254, "minecraft:furnace"));
        $$02.addFixer((DataFix)new bje($$254, "minecraft:smoker"));
        $$02.addFixer((DataFix)new bje($$254, "minecraft:blast_furnace"));
        Schema $$255 = $$02.addSchema(4187, c);
        $$02.addFixer((DataFix)new blb($$255, "Villager follow range fix undo", "minecraft:villager", "minecraft:follow_range", $$0 -> $$0 == 48.0 ? 16.0 : $$0));
        $$02.addFixer((DataFix)new blb($$255, "Bee follow range fix", "minecraft:bee", "minecraft:follow_range", $$0 -> $$0 == 48.0 ? 16.0 : $$0));
        $$02.addFixer((DataFix)new blb($$255, "Allay follow range fix", "minecraft:allay", "minecraft:follow_range", $$0 -> $$0 == 48.0 ? 16.0 : $$0));
        $$02.addFixer((DataFix)new blb($$255, "Llama follow range fix", "minecraft:llama", "minecraft:follow_range", $$0 -> $$0 == 40.0 ? 16.0 : $$0));
        $$02.addFixer((DataFix)new blb($$255, "Piglin Brute follow range fix", "minecraft:piglin_brute", "minecraft:follow_range", $$0 -> $$0 == 16.0 ? 12.0 : $$0));
        $$02.addFixer((DataFix)new blb($$255, "Warden follow range fix", "minecraft:warden", "minecraft:follow_range", $$0 -> $$0 == 16.0 ? 24.0 : $$0));
        Schema schema = $$02.addSchema(4290, bvt::new);
        $$02.addFixer((DataFix)new bro((Schema)$$256));
        Schema schema2 = $$02.addSchema(4291, c);
        $$02.addFixer((DataFix)new boh((Schema)$$257));
        $$02.addFixer((DataFix)new brg((Schema)$$257));
        Schema schema3 = $$02.addSchema(4292, bvu::new);
        $$02.addFixer((DataFix)new brf((Schema)$$258));
        Schema schema4 = $$02.addSchema(4293, c);
        $$02.addFixer((DataFix)new bku((Schema)$$259));
        Schema schema5 = $$02.addSchema(4294, c);
        $$02.addFixer((DataFix)new bjo((Schema)$$260, "CreakingHeartBlockStateFix", "minecraft:creaking_heart", "active", "creaking_heart_state", $$0 -> $$0.equals("true") ? "awake" : "uprooted"));
        Schema schema6 = $$02.addSchema(4295, c);
        $$02.addFixer((DataFix)new biz((Schema)$$261));
        Schema schema7 = $$02.addSchema(4296, c);
        $$02.addFixer((DataFix)new bin((Schema)$$262));
        Schema schema8 = $$02.addSchema(4297, c);
        $$02.addFixer((DataFix)new bmy((Schema)$$263));
        Schema schema9 = $$02.addSchema(4299, c);
        $$02.addFixer((DataFix)new bme((Schema)$$264));
        Schema schema10 = $$02.addSchema(4300, bvv::new);
        $$02.addFixer((DataFix)new bqq((Schema)$$265));
        Schema schema11 = $$02.addSchema(4301, bvw::new);
        $$02.addFixer((DataFix)new bmo((Schema)$$266));
        Schema schema12 = $$02.addSchema(4302, bvx::new);
        $$02.addFixer((DataFix)new bik((Schema)$$267, "Added Test and Test Instance Block Entities", bqh.w));
        Schema schema13 = $$02.addSchema(4303, c);
        $$02.addFixer((DataFix)new blj((Schema)$$268, bqh.H));
        $$02.addFixer((DataFix)new blj((Schema)$$268, bqh.c));
        Schema schema14 = $$02.addSchema(4305, c);
        $$02.addFixer((DataFix)new bjo((Schema)$$269, "rename test block mode", "minecraft:test_block", "test_block_mode", "mode", $$0 -> $$0));
        Schema schema15 = $$02.addSchema(4306, bvy::new);
        $$02.addFixer((DataFix)new brh((Schema)$$270));
        Schema schema16 = $$02.addSchema(4307, bvz::new);
        $$02.addFixer((DataFix)new brj((Schema)$$271));
        Schema schema17 = $$02.addSchema(4309, c);
        $$02.addFixer((DataFix)new bqc((Schema)$$272));
        $$02.addFixer((DataFix)new bkk((Schema)$$272));
        Schema schema18 = $$02.addSchema(4311, c);
        $$02.addFixer((DataFix)new bim((Schema)$$273, false, "Use lodestone category change", bia.a("minecraft:nether/use_lodestone", "minecraft:adventure/use_lodestone")));
        Schema schema19 = $$02.addSchema(4312, bwa::new);
        $$02.addFixer((DataFix)new bpu((Schema)$$274));
        Schema schema20 = $$02.addSchema(4314, c);
        $$02.addFixer((DataFix)new bng((Schema)$$275));
        Schema schema21 = $$02.addSchema(4420, bwb::new);
        $$02.addFixer((DataFix)new bov((Schema)$$276, "AreaEffectCloudCustomParticleFix", bqh.H, "minecraft:area_effect_cloud"));
        Schema schema22 = $$02.addSchema(4421, bwc::new);
        $$02.addFixer((DataFix)new bik((Schema)$$277, "Added Happy Ghast", bqh.H));
        Schema schema23 = $$02.addSchema(4424, c);
        $$02.addFixer((DataFix)new bmq((Schema)$$278, "Remove Locator Bar experimental feature flag", Set.of("minecraft:locator_bar")));
        $$02.addFixer((DataFix)new bii((Schema)$$278, bqh.c, "style", $$0 -> $$0.createString("minecraft:default"), "locator_bar_icon"));
        $$02.addFixer((DataFix)new bii((Schema)$$278, bqh.H, "style", $$0 -> $$0.createString("minecraft:default"), "locator_bar_icon"));
        Schema schema24 = $$02.addSchema(4531, bwd::new);
        $$02.addFixer((DataFix)new bik((Schema)$$279, "Added Copper Golem", bqh.H));
        Schema schema25 = $$02.addSchema(4532, bwe::new);
        $$02.addFixer((DataFix)new bik((Schema)$$280, "Added Copper Golem Statue Block Entity", bqh.w));
        Schema schema26 = $$02.addSchema(4533, bwf::new);
        $$02.addFixer((DataFix)new bik((Schema)$$281, "Added Shelf", bqh.w));
        Schema schema27 = $$02.addSchema(4535, c);
        $$02.addFixer((DataFix)new bko((Schema)$$282));
        Schema schema28 = $$02.addSchema(4537, c);
        $$02.addFixer((DataFix)new bkb((Schema)$$283));
        Schema schema29 = $$02.addSchema(4541, c);
        $$02.addFixer(bjp.a((Schema)$$284, "Rename chain to iron_chain", bia.a("minecraft:chain", "minecraft:iron_chain")));
        $$02.addFixer(bno.a((Schema)$$284, "Rename chain to iron_chain", bia.a("minecraft:chain", "minecraft:iron_chain")));
        Schema schema30 = $$02.addSchema(4543, bwg::new);
        $$02.addFixer((DataFix)new bik((Schema)$$285, "Added Mannequin", bqh.H));
        Schema schema31 = $$02.addSchema(4544, c);
        $$02.addFixer((DataFix)new boi((Schema)$$286));
        Schema schema32 = $$02.addSchema(4548, c);
        $$02.addFixer((DataFix)new bsb((Schema)$$287));
        $$02.addFixer((DataFix)new bpw((Schema)$$287));
        Schema schema33 = $$02.addSchema(4648, bwh::new);
        $$02.addFixer((DataFix)new bik((Schema)$$288, "Added Nautilus and Zombie Nautilus", bqh.H));
        Schema schema34 = $$02.addSchema(4649, c);
        $$02.addFixer((DataFix)new brn((Schema)$$289));
        Schema schema35 = $$02.addSchema(4650, c);
        $$02.addFixer((DataFix)new bks((Schema)$$290));
        Schema schema36 = $$02.addSchema(4651, c);
        $$02.addFixer((DataFix)new bpj((Schema)$$291, "cutoutLeaves", "false", "true", "true"));
        $$02.addFixer((DataFix)new bpj((Schema)$$291, "weatherRadius", "5", "10", "10"));
        $$02.addFixer((DataFix)new bpj((Schema)$$291, "vignette", "false", "true", "true"));
        $$02.addFixer((DataFix)new bpj((Schema)$$291, "improvedTransparency", "false", "false", "true"));
        $$02.addFixer((DataFix)new bpr((Schema)$$291));
        Schema schema37 = $$02.addSchema(4656, bwi::new);
        $$02.addFixer((DataFix)new bik((Schema)$$292, "Added Parched and Camel Husk", bqh.H));
        Schema schema38 = $$02.addSchema(4657, c);
        $$02.addFixer((DataFix)new brx((Schema)$$293));
        Schema schema39 = $$02.addSchema(4658, c);
        $$02.addFixer((DataFix)new bna((Schema)$$294));
        Schema schema40 = $$02.addSchema(4661, c);
        $$02.addFixer((DataFix)new bpo((Schema)$$295, false));
    }

    private static UnaryOperator<String> a(Map<String, String> $$0) {
        return $$1 -> $$0.getOrDefault($$1, (String)$$1);
    }

    private static UnaryOperator<String> b(Map<String, String> $$0) {
        return $$1 -> $$0.getOrDefault(bsh.a($$1), (String)$$1);
    }

    private static UnaryOperator<String> a(String $$0, String $$1) {
        return $$2 -> Objects.equals(bsh.a($$2), $$0) ? $$1 : $$2;
    }
}

