/*
 * Decompiled with CFR 0.152.
 */
public interface cfa {
    public static final amt<cez> a = amt.a(mj.ba, amo.b("in_fire"));
    public static final amt<cez> b = amt.a(mj.ba, amo.b("campfire"));
    public static final amt<cez> c = amt.a(mj.ba, amo.b("lightning_bolt"));
    public static final amt<cez> d = amt.a(mj.ba, amo.b("on_fire"));
    public static final amt<cez> e = amt.a(mj.ba, amo.b("lava"));
    public static final amt<cez> f = amt.a(mj.ba, amo.b("hot_floor"));
    public static final amt<cez> g = amt.a(mj.ba, amo.b("in_wall"));
    public static final amt<cez> h = amt.a(mj.ba, amo.b("cramming"));
    public static final amt<cez> i = amt.a(mj.ba, amo.b("drown"));
    public static final amt<cez> j = amt.a(mj.ba, amo.b("starve"));
    public static final amt<cez> k = amt.a(mj.ba, amo.b("cactus"));
    public static final amt<cez> l = amt.a(mj.ba, amo.b("fall"));
    public static final amt<cez> m = amt.a(mj.ba, amo.b("ender_pearl"));
    public static final amt<cez> n = amt.a(mj.ba, amo.b("fly_into_wall"));
    public static final amt<cez> o = amt.a(mj.ba, amo.b("out_of_world"));
    public static final amt<cez> p = amt.a(mj.ba, amo.b("generic"));
    public static final amt<cez> q = amt.a(mj.ba, amo.b("magic"));
    public static final amt<cez> r = amt.a(mj.ba, amo.b("wither"));
    public static final amt<cez> s = amt.a(mj.ba, amo.b("dragon_breath"));
    public static final amt<cez> t = amt.a(mj.ba, amo.b("dry_out"));
    public static final amt<cez> u = amt.a(mj.ba, amo.b("sweet_berry_bush"));
    public static final amt<cez> v = amt.a(mj.ba, amo.b("freeze"));
    public static final amt<cez> w = amt.a(mj.ba, amo.b("stalagmite"));
    public static final amt<cez> x = amt.a(mj.ba, amo.b("falling_block"));
    public static final amt<cez> y = amt.a(mj.ba, amo.b("falling_anvil"));
    public static final amt<cez> z = amt.a(mj.ba, amo.b("falling_stalactite"));
    public static final amt<cez> A = amt.a(mj.ba, amo.b("sting"));
    public static final amt<cez> B = amt.a(mj.ba, amo.b("mob_attack"));
    public static final amt<cez> C = amt.a(mj.ba, amo.b("mob_attack_no_aggro"));
    public static final amt<cez> D = amt.a(mj.ba, amo.b("player_attack"));
    public static final amt<cez> E = amt.a(mj.ba, amo.b("spear"));
    public static final amt<cez> F = amt.a(mj.ba, amo.b("arrow"));
    public static final amt<cez> G = amt.a(mj.ba, amo.b("trident"));
    public static final amt<cez> H = amt.a(mj.ba, amo.b("mob_projectile"));
    public static final amt<cez> I = amt.a(mj.ba, amo.b("spit"));
    public static final amt<cez> J = amt.a(mj.ba, amo.b("wind_charge"));
    public static final amt<cez> K = amt.a(mj.ba, amo.b("fireworks"));
    public static final amt<cez> L = amt.a(mj.ba, amo.b("fireball"));
    public static final amt<cez> M = amt.a(mj.ba, amo.b("unattributed_fireball"));
    public static final amt<cez> N = amt.a(mj.ba, amo.b("wither_skull"));
    public static final amt<cez> O = amt.a(mj.ba, amo.b("thrown"));
    public static final amt<cez> P = amt.a(mj.ba, amo.b("indirect_magic"));
    public static final amt<cez> Q = amt.a(mj.ba, amo.b("thorns"));
    public static final amt<cez> R = amt.a(mj.ba, amo.b("explosion"));
    public static final amt<cez> S = amt.a(mj.ba, amo.b("player_explosion"));
    public static final amt<cez> T = amt.a(mj.ba, amo.b("sonic_boom"));
    public static final amt<cez> U = amt.a(mj.ba, amo.b("bad_respawn_point"));
    public static final amt<cez> V = amt.a(mj.ba, amo.b("outside_border"));
    public static final amt<cez> W = amt.a(mj.ba, amo.b("generic_kill"));
    public static final amt<cez> X = amt.a(mj.ba, amo.b("mace_smash"));

    public static void a(qr<cez> $$0) {
        $$0.a(a, new cez("inFire", 0.1f, cev.d));
        $$0.a(b, new cez("inFire", 0.1f, cev.d));
        $$0.a(c, new cez("lightningBolt", 0.1f));
        $$0.a(d, new cez("onFire", 0.0f, cev.d));
        $$0.a(e, new cez("lava", 0.1f, cev.d));
        $$0.a(f, new cez("hotFloor", 0.1f, cev.d));
        $$0.a(g, new cez("inWall", 0.0f));
        $$0.a(h, new cez("cramming", 0.0f));
        $$0.a(i, new cez("drown", 0.0f, cev.c));
        $$0.a(j, new cez("starve", 0.0f));
        $$0.a(k, new cez("cactus", 0.1f));
        $$0.a(l, new cez("fall", cew.b, 0.0f, cev.a, cfb.b));
        $$0.a(m, new cez("fall", cew.b, 0.0f, cev.a, cfb.b));
        $$0.a(n, new cez("flyIntoWall", 0.0f));
        $$0.a(o, new cez("outOfWorld", 0.0f));
        $$0.a(p, new cez("generic", 0.0f));
        $$0.a(q, new cez("magic", 0.0f));
        $$0.a(r, new cez("wither", 0.0f));
        $$0.a(s, new cez("dragonBreath", 0.0f));
        $$0.a(t, new cez("dryout", 0.1f));
        $$0.a(u, new cez("sweetBerryBush", 0.1f, cev.e));
        $$0.a(v, new cez("freeze", 0.0f, cev.f));
        $$0.a(w, new cez("stalagmite", 0.0f));
        $$0.a(x, new cez("fallingBlock", 0.1f));
        $$0.a(y, new cez("anvil", 0.1f));
        $$0.a(z, new cez("fallingStalactite", 0.1f));
        $$0.a(A, new cez("sting", 0.1f));
        $$0.a(B, new cez("mob", 0.1f));
        $$0.a(C, new cez("mob", 0.1f));
        $$0.a(D, new cez("player", 0.1f));
        $$0.a(E, new cez("spear", 0.1f));
        $$0.a(F, new cez("arrow", 0.1f));
        $$0.a(G, new cez("trident", 0.1f));
        $$0.a(H, new cez("mob", 0.1f));
        $$0.a(I, new cez("mob", 0.1f));
        $$0.a(K, new cez("fireworks", 0.1f));
        $$0.a(M, new cez("onFire", 0.1f, cev.d));
        $$0.a(L, new cez("fireball", 0.1f, cev.d));
        $$0.a(N, new cez("witherSkull", 0.1f));
        $$0.a(O, new cez("thrown", 0.1f));
        $$0.a(P, new cez("indirectMagic", 0.0f));
        $$0.a(Q, new cez("thorns", 0.1f, cev.b));
        $$0.a(R, new cez("explosion", cew.c, 0.1f));
        $$0.a(S, new cez("explosion.player", cew.c, 0.1f));
        $$0.a(T, new cez("sonic_boom", cew.c, 0.0f));
        $$0.a(U, new cez("badRespawnPoint", cew.c, 0.1f, cev.a, cfb.c));
        $$0.a(V, new cez("outsideBorder", 0.0f));
        $$0.a(W, new cez("genericKill", 0.0f));
        $$0.a(J, new cez("mob", 0.1f));
        $$0.a(X, new cez("mace_smash", 0.1f));
    }
}

