/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 */
import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;

public class hdd {
    private static final hdk a = new hdk(0.008f);
    private static final hdk b = new hdk(1.0f);
    private static final hdk c = new hdk(0.5f);

    public static Map<hde, hdm> a() {
        ImmutableMap.Builder $$02 = ImmutableMap.builder();
        hdm $$12 = hdm.a(gzo.a(hdk.a, 0.0f), 64, 64);
        hvk<hdm> $$2 = gzo.a(c, b).a($$0 -> hdm.a($$0, 64, 32));
        hvk<hdm> $$32 = $$2.a($$0 -> $$0.a(gzo.b));
        hvk<hdm> $$4 = hht.b(c, b).a($$0 -> hdm.a($$0, 64, 32));
        hvk<hdm> $$5 = hew.b(c, new hdk(1.02f)).a($$0 -> hdm.a($$0, 64, 32));
        hvk<hdm> $$6 = $$5.a($$0 -> $$0.a(gzo.b));
        hdm $$7 = hgt.a();
        hdm $$8 = hhl.f();
        hdm $$9 = hdm.a(hap.a(hdk.a), 64, 64);
        hdm $$10 = hdm.a(hap.b(hdk.a), 64, 64);
        hdm $$11 = har.a(false);
        hdm $$122 = har.a(true);
        hdp $$13 = hdp.scaling(0.9375f);
        hdm $$14 = hep.e().a($$13);
        hdm $$15 = gzy.a();
        hdm $$16 = haa.a();
        hdm $$17 = hak.e();
        hdm $$18 = hah.f();
        hdm $$19 = haj.a();
        hdm $$20 = hcg.a(hdk.a);
        hdm $$21 = hgz.a();
        hdm $$22 = hdm.a(hav.a(hdk.a), 64, 32);
        hdm $$23 = $$22.a(hav.c);
        hdm $$24 = hdm.a(hav.a(new hdk(0.01f)), 64, 32);
        hdm $$25 = hdm.a(hew.a(hdk.a), 64, 64);
        hdm $$26 = hdm.a(hhk.a(), 64, 64);
        hdm $$27 = hhl.e();
        hdm $$28 = hbu.a(hdk.a);
        hdm $$29 = hbu.a(new hdk(0.5f));
        hdm $$30 = hfn.a();
        hdm $$31 = hen.a();
        hdm $$322 = hen.e();
        hdm $$33 = hfg.f();
        hdm $$34 = hdm.a(hgd.e(), 64, 64).a($$13);
        hdm $$35 = hdm.a(hgd.f(), 64, 64).a($$13);
        hdm $$36 = hfl.a();
        hdm $$37 = gzw.a();
        hdm $$38 = had.a();
        hdm $$39 = hae.f();
        hdm $$40 = hag.a();
        hdm $$41 = hbo.a();
        hdm $$42 = hcc.a();
        hdm $$43 = hch.b(hdk.a);
        hdm $$44 = hch.b(new hdk(0.5f));
        hdm $$45 = hco.a();
        hdm $$46 = hcn.a();
        hdm $$47 = hcq.a();
        hdm $$48 = hcu.a();
        hdm $$49 = hal.a();
        hdm $$50 = hdm.a(hcw.a(hdk.a), 64, 32);
        hdm $$51 = hdm.a(hcw.a(new hdk(0.2f)), 64, 32);
        hdm $$52 = hgb.e();
        hdm $$53 = hgb.f();
        hdm $$54 = hgg.e();
        hvk<hdm> $$55 = hgf.b(c, b);
        hdm $$56 = hfy.a(hdk.a);
        hdm $$57 = hfy.a(new hdk(0.25f));
        hdm $$58 = hcs.a();
        hdm $$59 = han.a();
        hdm $$60 = hbc.a();
        hdm $$61 = hbz.a();
        $$02.put((Object)hdf.c, (Object)gzu.a());
        $$02.put((Object)hdf.d, (Object)$$37);
        $$02.put((Object)hdf.e, (Object)$$37.a(gzw.b));
        $$02.put((Object)hdf.f, (Object)$$54);
        hdf.g.a($$55, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.h, (Object)$$54.a(gzo.b));
        hdf.i.a($$55.a($$0 -> $$0.a(gzo.b)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.j, (Object)hhe.a());
        $$02.put((Object)hdf.k, (Object)$$15);
        $$02.put((Object)hdf.l, (Object)$$15.a(gzy.c));
        $$02.put((Object)hdf.o, (Object)hgj.a(true));
        $$02.put((Object)hdf.q, (Object)hgj.a(false));
        $$02.put((Object)hdf.p, (Object)hgi.a(true));
        $$02.put((Object)hdf.r, (Object)hgi.a(false));
        $$02.put((Object)hdf.s, (Object)gzs.a());
        $$02.put((Object)hdf.t, (Object)hrf.d());
        $$02.put((Object)hdf.u, (Object)hrf.a());
        $$02.put((Object)hdf.v, (Object)$$16);
        $$02.put((Object)hdf.w, (Object)$$16.a(haa.b));
        $$02.put((Object)hdf.x, (Object)hab.a());
        $$02.put((Object)hdf.y, (Object)hgl.a());
        $$02.put((Object)hdf.B, (Object)hdu.a());
        $$02.put((Object)hdf.C, (Object)hgo.f());
        $$02.put((Object)hdf.D, (Object)hff.e());
        hdf.E.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.F, (Object)hdm.a(gzo.a(new hdk(0.2f), 0.0f), 64, 32));
        $$02.put((Object)hdf.G, (Object)hgr.a());
        $$02.put((Object)hdf.H, (Object)hdw.a());
        $$02.put((Object)hdf.I, (Object)hdw.e());
        $$02.put((Object)hdf.J, (Object)hdw.f());
        $$02.put((Object)hdf.Q, (Object)$$22.a(hau.b));
        $$02.put((Object)hdf.R, (Object)$$23.a(hau.b));
        $$02.put((Object)hdf.T, (Object)$$24.a(hau.b));
        $$02.put((Object)hdf.S, (Object)$$24.a(hav.c).a(hau.b));
        $$02.put((Object)hdf.K, (Object)$$38);
        $$02.put((Object)hdf.L, (Object)$$38.a(had.b));
        $$02.put((Object)hdf.M, (Object)$$39);
        $$02.put((Object)hdf.N, (Object)$$39.a(had.b));
        $$02.put((Object)hdf.O, (Object)$$39);
        $$02.put((Object)hdf.P, (Object)$$39.a(had.b));
        $$02.put((Object)hdf.U, (Object)$$36.a(hdp.scaling(0.7f)));
        $$02.put((Object)hdf.X, (Object)hgv.a());
        $$02.put((Object)hdf.Y, (Object)$$7);
        $$02.put((Object)hdf.Z, (Object)$$40);
        $$02.put((Object)hdf.aa, (Object)$$40.a(hag.d));
        $$02.put((Object)hdf.ab, (Object)hay.a());
        $$02.put((Object)hdf.ac, (Object)$$18);
        $$02.put((Object)hdf.ad, (Object)$$18.a(hag.d));
        $$02.put((Object)hdf.ae, (Object)$$19);
        $$02.put((Object)hdf.af, (Object)$$19.a(hak.h));
        $$02.put((Object)hdf.ag, (Object)$$20);
        $$02.put((Object)hdf.ah, (Object)$$20.a(hch.h));
        $$02.put((Object)hdf.ai, (Object)$$7);
        $$02.put((Object)hdf.ak, (Object)hrq.a());
        $$02.put((Object)hdf.am, (Object)hrq.d());
        $$02.put((Object)hdf.al, (Object)hrq.f());
        $$02.put((Object)hdf.aj, (Object)hrq.g());
        $$02.put((Object)hdf.an, (Object)hbq.e());
        $$02.put((Object)hdf.ao, (Object)hbq.i());
        $$02.put((Object)hdf.ap, (Object)hbq.f());
        $$02.put((Object)hdf.aq, (Object)hbq.g());
        $$02.put((Object)hdf.ar, (Object)hbq.h());
        $$02.put((Object)hdf.at, (Object)$$17);
        $$02.put((Object)hdf.au, (Object)$$17.a(hak.h));
        $$02.put((Object)hdf.av, (Object)hdy.a());
        $$02.put((Object)hdf.aw, (Object)hdy.e());
        $$02.put((Object)hdf.ax, (Object)hea.a(hdk.a));
        $$02.put((Object)hdf.ay, (Object)hea.a(new hdk(2.0f)));
        $$02.put((Object)hdf.az, (Object)$$8);
        $$02.put((Object)hdf.aC, (Object)hrs.a());
        $$02.put((Object)hdf.aD, (Object)hrs.d());
        $$02.put((Object)hdf.aE, (Object)$$59);
        $$02.put((Object)hdf.aF, (Object)$$59.a(han.b));
        $$02.put((Object)hdf.aG, (Object)haq.a(0.87f));
        $$02.put((Object)hdf.aH, (Object)haq.b(0.87f));
        $$02.put((Object)hdf.aI, (Object)haq.a(0.87f, false));
        $$02.put((Object)hdf.aJ, (Object)haq.a(0.87f, true));
        $$02.put((Object)hdf.aK, (Object)hgv.f());
        $$02.put((Object)hdf.aL, (Object)hgv.e());
        $$02.put((Object)hdf.aM, (Object)hhj.a());
        $$02.put((Object)hdf.aN, (Object)$$56);
        hdf.aR.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.aS, (Object)$$57);
        $$02.put((Object)hdf.aO, (Object)$$56.a(gzo.b));
        hdf.aP.a($$32, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.aQ, (Object)$$57.a(gzo.b));
        $$02.put((Object)hdf.aT, (Object)hek.e());
        $$02.put((Object)hdf.aU, (Object)$$21);
        $$02.put((Object)hdf.aV, (Object)$$21.a(hgz.b));
        $$02.put((Object)hdf.aW, (Object)hee.e());
        $$02.put((Object)hdf.aX, (Object)heg.a());
        $$02.put((Object)hdf.aY, (Object)hec.a());
        $$02.put((Object)hdf.aZ, (Object)hgx.a());
        $$02.put((Object)hdf.ba, (Object)$$14);
        $$02.put((Object)hdf.bb, (Object)hcy.a());
        $$02.put((Object)hdf.bc, (Object)hbg.a());
        $$02.put((Object)hdf.bd, (Object)hbg.a().a(hbg.b));
        $$02.put((Object)hdf.be, (Object)hbi.a());
        $$02.put((Object)hdf.bf, (Object)$$7);
        $$02.put((Object)hdf.bg, (Object)hei.a());
        hdp $$62 = hdp.scaling(6.0f);
        $$02.put((Object)hdf.bh, (Object)$$12.a($$62));
        hdf.bi.a($$2.a($$1 -> $$1.a($$62)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.bj, (Object)$$58);
        $$02.put((Object)hdf.bk, (Object)$$58.a(hcs.b));
        $$02.put((Object)hdf.bl, (Object)$$41);
        $$02.put((Object)hdf.bm, (Object)$$41.a(hbo.h));
        $$02.put((Object)hdf.bn, (Object)hek.a());
        $$02.put((Object)hdf.bo, (Object)hbm.a(false, hdk.a));
        $$02.put((Object)hdf.bp, (Object)hbm.a(true, hdk.a).a(hbm.b));
        $$02.put((Object)hdf.bq, (Object)hbl.a(false));
        $$02.put((Object)hdf.br, (Object)hbl.a(true).a(hbm.b));
        $$02.put((Object)hdf.bs, (Object)hbm.a(false, new hdk(0.2f)));
        $$02.put((Object)hdf.bt, (Object)hbm.a(true, new hdk(0.2f)).a(hbm.b));
        $$02.put((Object)hdf.bu, (Object)$$31);
        $$02.put((Object)hdf.bv, (Object)$$322);
        $$02.put((Object)hdf.bw, (Object)$$7);
        hdp $$63 = hdp.scaling(1.1f);
        $$02.put((Object)hdf.bx, (Object)$$9.a($$63));
        $$02.put((Object)hdf.bA, (Object)$$10.a($$63));
        $$02.put((Object)hdf.by, (Object)hdm.a(hap.a(new hdk(0.1f)), 64, 64).a($$63));
        $$02.put((Object)hdf.bB, (Object)hdm.a(hap.b(new hdk(0.1f)), 64, 64).a($$63));
        $$02.put((Object)hdf.bz, (Object)$$11.a($$63));
        $$02.put((Object)hdf.bC, (Object)$$122.a($$63));
        hdp $$64 = hdp.scaling(1.0625f);
        $$02.put((Object)hdf.bD, (Object)$$12.a($$64));
        hdf.bG.a($$2.a($$1 -> $$1.a($$64)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.bE, (Object)$$12.a(gzo.b).a($$64));
        hdf.bF.a($$32.a($$1 -> $$1.a($$64)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.bH, (Object)$$14);
        $$02.put((Object)hdf.bI, (Object)hbr.a());
        $$02.put((Object)hdf.bL, (Object)hhc.a());
        $$02.put((Object)hdf.bM, (Object)$$28);
        $$02.put((Object)hdf.bN, (Object)$$28.a(hbu.b));
        $$02.put((Object)hdf.bP, (Object)$$29);
        $$02.put((Object)hdf.bO, (Object)$$29.a(hbu.b));
        $$02.put((Object)hdf.bQ, (Object)hbv.a());
        $$02.put((Object)hdf.bR, (Object)hfi.a());
        $$02.put((Object)hdf.bU, (Object)$$7);
        $$02.put((Object)hdf.bV, (Object)$$17);
        $$02.put((Object)hdf.bW, (Object)$$17.a(hak.h));
        $$02.put((Object)hdf.bX, (Object)haq.a(0.92f));
        $$02.put((Object)hdf.bY, (Object)haq.b(0.92f));
        $$02.put((Object)hdf.bZ, (Object)haq.a(0.92f, false));
        $$02.put((Object)hdf.ca, (Object)haq.a(0.92f, true));
        $$02.put((Object)hdf.cb, (Object)hby.e());
        $$02.put((Object)hdf.cc, (Object)hby.g());
        $$02.put((Object)hdf.cd, (Object)$$61);
        $$02.put((Object)hdf.ce, (Object)hbx.a());
        $$02.put((Object)hdf.eP, (Object)hby.e());
        $$02.put((Object)hdf.as, (Object)her.a());
        $$02.put((Object)hdf.ch, (Object)$$22);
        $$02.put((Object)hdf.ci, (Object)$$23);
        $$02.put((Object)hdf.cl, (Object)$$42);
        $$02.put((Object)hdf.cm, (Object)$$42.a(hcc.h));
        $$02.put((Object)hdf.cn, (Object)hfg.g());
        hdf.co.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cp, (Object)hdm.a(gzo.a(new hdk(0.25f), 0.0f), 64, 32));
        $$02.put((Object)hdf.cq, (Object)hce.a());
        $$02.put((Object)hdf.cr, (Object)het.a());
        $$02.put((Object)hdf.cs, (Object)$$43);
        $$02.put((Object)hdf.cA, (Object)$$43.a(hch.h));
        $$02.put((Object)hdf.cC, (Object)$$44);
        $$02.put((Object)hdf.cB, (Object)$$44.a(hch.h));
        $$02.put((Object)hdf.ct, (Object)$$25);
        hdf.cz.a($$5, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cw, (Object)$$25);
        hdf.cx.a($$5, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cu, (Object)$$25.a(gzo.b));
        hdf.cv.a($$6, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cy, (Object)$$26);
        $$02.put((Object)hdf.cD, (Object)$$14);
        $$02.put((Object)hdf.cE, (Object)hdm.a(hht.a(hdk.a, false), 64, 64));
        $$02.put((Object)hdf.cG, (Object)hhs.e());
        $$02.put((Object)hdf.cF, (Object)hhr.e());
        $$02.put((Object)hdf.cH, (Object)$$27);
        hdf.cI.a($$4, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cJ, (Object)hdm.a(hht.a(hdk.a, true), 64, 64));
        hdf.cK.a($$4, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.cL, (Object)hda.a());
        $$02.put((Object)hdf.cM, (Object)hcj.a(false));
        $$02.put((Object)hdf.cN, (Object)hcj.a(true));
        $$02.put((Object)hdf.cO, (Object)haz.a());
        $$02.put((Object)hdf.cP, (Object)hba.a());
        $$02.put((Object)hdf.cQ, (Object)hbb.a());
        $$02.put((Object)hdf.cR, (Object)hcl.a(false));
        $$02.put((Object)hdf.cS, (Object)hcl.a(true));
        $$02.put((Object)hdf.cT, (Object)hez.a());
        $$02.put((Object)hdf.cU, (Object)$$60);
        $$02.put((Object)hdf.cW, (Object)$$60.a(hbc.b));
        $$02.put((Object)hdf.cV, (Object)$$60.a(hbc.c));
        $$02.put((Object)hdf.cX, (Object)$$45);
        $$02.put((Object)hdf.cY, (Object)$$45.a(hco.h));
        $$02.put((Object)hdf.da, (Object)$$46);
        $$02.put((Object)hdf.cZ, (Object)$$46.a(hco.h));
        $$02.put((Object)hdf.db, (Object)$$45);
        $$02.put((Object)hdf.dc, (Object)$$45.a(hco.h));
        $$02.put((Object)hdf.dd, (Object)hha.a());
        $$02.put((Object)hdf.de, (Object)hfb.a());
        $$02.put((Object)hdf.df, (Object)hfb.e());
        $$02.put((Object)hdf.dg, (Object)hhf.a());
        $$02.put((Object)hdf.dh, (Object)hfd.a());
        $$02.put((Object)hdf.di, (Object)$$33);
        hdf.dn.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.dj, (Object)$$9);
        $$02.put((Object)hdf.dk, (Object)$$10);
        $$02.put((Object)hdf.dl, (Object)$$11);
        $$02.put((Object)hdf.dm, (Object)$$122);
        $$02.put((Object)hdf.do, (Object)$$8);
        $$02.put((Object)hdf.dp, (Object)hfj.e());
        $$02.put((Object)hdf.dq, (Object)hfj.a());
        $$02.put((Object)hdf.dr, (Object)$$47);
        $$02.put((Object)hdf.ds, (Object)$$47.a(hcq.b));
        $$02.put((Object)hdf.dt, (Object)hbs.a());
        $$02.put((Object)hdf.du, (Object)$$7);
        $$02.put((Object)hdf.dv, (Object)$$36);
        $$02.put((Object)hdf.dy, (Object)$$58);
        $$02.put((Object)hdf.dz, (Object)$$58.a(hcs.b));
        $$02.put((Object)hdf.dA, (Object)$$33);
        hdf.dB.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.dC, (Object)hdm.a(gzo.a(new hdk(0.25f), 0.0f), 64, 32));
        $$02.put((Object)hdf.dD, (Object)$$30);
        $$02.put((Object)hdf.dE, (Object)$$30);
        $$02.put((Object)hdf.dF, (Object)$$30.a(hfn.b));
        $$02.put((Object)hdf.dG, (Object)$$30.a(hfn.b));
        $$02.put((Object)hdf.dH, (Object)hbj.a());
        $$02.put((Object)hdf.dI, (Object)$$7);
        $$02.put((Object)hdf.dJ, (Object)$$28);
        $$02.put((Object)hdf.dK, (Object)$$28.a(hbu.b));
        $$02.put((Object)hdf.dL, (Object)hhg.a());
        $$02.put((Object)hdf.dM, (Object)hbd.a(hdk.a));
        $$02.put((Object)hdf.dN, (Object)hbd.a(a));
        $$02.put((Object)hdf.dO, (Object)hbe.a(hdk.a));
        $$02.put((Object)hdf.dP, (Object)hbe.a(a));
        $$02.put((Object)hdf.dQ, (Object)$$48);
        $$02.put((Object)hdf.dR, (Object)$$48.a(hcu.h));
        $$02.put((Object)hdf.dS, (Object)hdm.a(hap.a(new hdk(0.1f)), 64, 64));
        $$02.put((Object)hdf.dT, (Object)hdm.a(hap.b(new hdk(0.1f)), 64, 64));
        $$02.put((Object)hdf.dU, (Object)hfp.a());
        $$02.put((Object)hdf.dV, (Object)$$34);
        $$02.put((Object)hdf.dW, (Object)$$35);
        $$02.put((Object)hdf.dX, (Object)$$34.a(hgd.b));
        $$02.put((Object)hdf.dY, (Object)$$35.a(hgd.b));
        $$02.put((Object)hdf.dZ, (Object)$$14);
        $$02.put((Object)hdf.eb, (Object)hfr.a());
        $$02.put((Object)hdf.ee, (Object)hfr.e());
        $$02.put((Object)hdf.ef, (Object)hfr.f());
        $$02.put((Object)hdf.ec, (Object)hfr.g());
        $$02.put((Object)hdf.ed, (Object)hfr.h());
        $$02.put((Object)hdf.eg, (Object)$$49);
        $$02.put((Object)hdf.eh, (Object)$$49.a(hak.h));
        $$02.put((Object)hdf.ea, (Object)$$34);
        $$02.put((Object)hdf.ei, (Object)hhh.a());
        $$02.put((Object)hdf.ej, (Object)hft.e().a($$13));
        $$02.put((Object)hdf.ek, (Object)hfv.a(hdk.a));
        $$02.put((Object)hdf.el, (Object)hfv.a(c));
        $$02.put((Object)hdf.ep, (Object)hzx.a());
        hdp $$65 = hdp.scaling(1.2f);
        $$02.put((Object)hdf.em, (Object)$$33.a($$65));
        hdf.en.a($$2.a($$1 -> $$1.a($$65)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.eo, (Object)$$8);
        $$02.put((Object)hdf.eq, (Object)$$50);
        $$02.put((Object)hdf.er, (Object)$$51);
        $$02.put((Object)hdf.es, (Object)$$50.a(hcw.b));
        $$02.put((Object)hdf.et, (Object)$$51.a(hcw.b));
        $$02.put((Object)hdf.eu, (Object)$$31);
        $$02.put((Object)hdf.ev, (Object)$$322);
        $$02.put((Object)hdf.ew, (Object)$$12);
        hdf.eE.a($$2, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.ex, (Object)$$12.a(gzo.b));
        hdf.ey.a($$32, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.ez, (Object)$$27);
        $$02.put((Object)hdf.eA, (Object)$$9);
        $$02.put((Object)hdf.eB, (Object)$$10);
        $$02.put((Object)hdf.eC, (Object)$$11);
        $$02.put((Object)hdf.eD, (Object)$$122);
        $$02.put((Object)hdf.eF, (Object)$$52);
        $$02.put((Object)hdf.eG, (Object)$$53);
        hvk<hdm> $$66 = hgb.b(c, b);
        hdf.eK.a($$66, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.eH, (Object)$$52.a(gzo.b));
        $$02.put((Object)hdf.eI, (Object)$$53.a(gzo.b));
        hdf.eJ.a($$66.a($$0 -> $$0.a(gzo.b)), (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.eL, (Object)$$25);
        hdf.eO.a($$5, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.eM, (Object)$$25.a(gzo.b));
        hdf.eN.a($$6, (ImmutableMap.Builder<hde, hdm>)$$02);
        $$02.put((Object)hdf.n, (Object)hgp.a());
        $$02.put((Object)hdf.m, (Object)hgp.e());
        hdm $$67 = hgo.a();
        hdm $$68 = hgo.e();
        $$02.put((Object)hdf.cf, (Object)$$67);
        $$02.put((Object)hdf.cg, (Object)$$68);
        $$02.put((Object)hdf.dw, (Object)$$67);
        $$02.put((Object)hdf.dx, (Object)$$68);
        $$02.put((Object)hdf.z, (Object)$$67);
        $$02.put((Object)hdf.A, (Object)$$68);
        $$02.put((Object)hdf.bJ, (Object)$$67);
        $$02.put((Object)hdf.bK, (Object)$$68);
        $$02.put((Object)hdf.a, (Object)$$67);
        $$02.put((Object)hdf.b, (Object)$$68);
        $$02.put((Object)hdf.V, (Object)$$67);
        $$02.put((Object)hdf.W, (Object)$$68);
        $$02.put((Object)hdf.aA, (Object)$$67);
        $$02.put((Object)hdf.aB, (Object)$$68);
        $$02.put((Object)hdf.cj, (Object)$$67);
        $$02.put((Object)hdf.ck, (Object)$$68);
        $$02.put((Object)hdf.bS, (Object)$$67);
        $$02.put((Object)hdf.bT, (Object)$$68);
        hdm $$69 = hrz.a(true);
        hdm $$70 = hrz.a(false);
        epw.a().forEach($$3 -> {
            $$02.put((Object)hdf.a($$3), (Object)$$69);
            $$02.put((Object)hdf.b($$3), (Object)$$70);
            for (hru.a $$4 : hru.a.values()) {
                hdm $$5 = hru.a($$4);
                $$02.put((Object)hdf.a($$3, $$4), (Object)$$5);
            }
        });
        ImmutableMap $$71 = $$02.build();
        List<hde> $$72 = hdf.a().filter($$1 -> !$$71.containsKey($$1)).toList();
        if (!$$72.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf($$72));
        }
        return $$71;
    }
}

