/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.lang.invoke.MethodHandle;
import java.lang.runtime.ObjectMethods;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Stream;

public class ox
extends on {
    private static final ImmutableList<dwn> c = ImmutableList.of((Object)dlx.am, (Object)dlx.an);
    private static final ImmutableList<dwn> d = ImmutableList.of((Object)dlx.ao, (Object)dlx.ap, (Object)dlx.qf);
    private static final ImmutableList<dwn> e = ImmutableList.of((Object)dlx.aq, (Object)dlx.ar, (Object)dlx.qh);
    private static final ImmutableList<dwn> f = ImmutableList.of((Object)dlx.as, (Object)dlx.at, (Object)dlx.aC, (Object)dlx.qj);
    private static final ImmutableList<dwn> g = ImmutableList.of((Object)dlx.aA, (Object)dlx.aB);
    private static final ImmutableList<dwn> h = ImmutableList.of((Object)dlx.ay, (Object)dlx.az);
    private static final ImmutableList<dwn> i = ImmutableList.of((Object)dlx.au, (Object)dlx.av);
    private static final ImmutableList<dwn> j = ImmutableList.of((Object)dlx.aw, (Object)dlx.ax);

    ox(jf.a $$0, om $$1) {
        super($$0, $$1);
    }

    @Override
    protected void a() {
        this.b.b();
        this.a(dgz.a(dhb.a));
        this.a((dwn)dzs.r, bdy.v, 4);
        this.b(dzs.p, bdy.u, 4);
        this.b(dzs.pC, bdy.A, 4);
        this.a((dwn)dzs.t, bdy.s, 4);
        this.a((dwn)dzs.v, bdy.t, 4);
        this.b(dzs.q, bdy.y, 4);
        this.b(dzs.n, bdy.r, 4);
        this.b(dzs.o, bdy.w, 4);
        this.b(dzs.pD, bdy.B, 4);
        this.b(dzs.w, bdy.x, 4);
        this.a((dwn)dzs.ax, (dwn)dzs.ab);
        this.a((dwn)dzs.av, (dwn)dzs.Z);
        this.a((dwn)dzs.az, (dwn)dzs.ad);
        this.a((dwn)dzs.u, (dwn)dzs.ae);
        this.a((dwn)dzs.aw, (dwn)dzs.aa);
        this.a((dwn)dzs.at, (dwn)dzs.X);
        this.a((dwn)dzs.au, (dwn)dzs.Y);
        this.a((dwn)dzs.ps, (dwn)dzs.pq);
        this.a((dwn)dzs.pj, (dwn)dzs.ph);
        this.a((dwn)dzs.aA, (dwn)dzs.af);
        this.a((dwn)dzs.aF, (dwn)dzs.am);
        this.a((dwn)dzs.aD, (dwn)dzs.ak);
        this.a((dwn)dzs.aH, (dwn)dzs.ao);
        this.a((dwn)dzs.aI, (dwn)dzs.ap);
        this.a((dwn)dzs.aE, (dwn)dzs.al);
        this.a((dwn)dzs.aB, (dwn)dzs.aq);
        this.a((dwn)dzs.aC, (dwn)dzs.aj);
        this.a((dwn)dzs.pt, (dwn)dzs.pr);
        this.a((dwn)dzs.pk, (dwn)dzs.pi);
        this.a((dwn)dzs.aJ, (dwn)dzs.ar);
        this.b((dwn)dlx.pz, (dwn)dzs.r);
        this.b((dwn)dlx.pv, (dwn)dzs.p);
        this.b((dwn)dlx.pD, (dwn)dzs.t);
        this.b((dwn)dlx.pF, (dwn)dzs.v);
        this.b((dwn)dlx.px, (dwn)dzs.q);
        this.b((dwn)dlx.pr, (dwn)dzs.n);
        this.b((dwn)dlx.pt, (dwn)dzs.o);
        this.b((dwn)dlx.pH, (dwn)dzs.w);
        this.e(dzs.cx, dlx.bW);
        this.e(dzs.cy, dlx.co);
        this.e(dzs.cz, dlx.bU);
        this.e(dzs.cA, dlx.bX);
        this.e(dzs.cB, dlx.cb);
        this.e(dzs.cC, dlx.bY);
        this.e(dzs.cD, dlx.bV);
        this.e(dzs.cE, dlx.ca);
        this.e(dzs.cF, dlx.bS);
        this.e(dzs.cG, dlx.bZ);
        this.e(dzs.cH, dlx.bT);
        this.e(dzs.cI, dlx.cc);
        List<dlp> $$02 = List.of(dlx.tB, dlx.tx, dlx.ty, dlx.tv, dlx.tt, dlx.tz, dlx.tp, dlx.tu, dlx.tr, dlx.to, dlx.tn, dlx.ts, dlx.tw, dlx.tA, dlx.tq, dlx.tm);
        List<dlp> $$1 = List.of(dlx.du, dlx.dq, dlx.dr, dlx.do, dlx.dm, dlx.ds, dlx.di, dlx.dn, dlx.dk, dlx.dh, dlx.dg, dlx.dl, dlx.dp, dlx.dt, dlx.dj, dlx.df);
        List<dlp> $$2 = List.of(dlx.tV, dlx.tR, dlx.tS, dlx.tP, dlx.tN, dlx.tT, dlx.tJ, dlx.tO, dlx.tL, dlx.tI, dlx.tH, dlx.tM, dlx.tQ, dlx.tU, dlx.tK, dlx.tG);
        List<dlp> $$3 = List.of(dlx.iM, dlx.iI, dlx.iJ, dlx.iG, dlx.iE, dlx.iK, dlx.iA, dlx.iF, dlx.iC, dlx.iz, dlx.iy, dlx.iD, dlx.iH, dlx.iL, dlx.iB, dlx.ix);
        List<dlp> $$4 = List.of(dlx.ph, dlx.pd, dlx.pe, dlx.pb, dlx.oZ, dlx.pf, dlx.oV, dlx.pa, dlx.oX, dlx.oU, dlx.oT, dlx.oY, dlx.pc, dlx.pg, dlx.oW, dlx.oS);
        this.a($$02, $$1, "wool", ol.a);
        this.a($$02, $$2, "bed_dye", ol.b);
        this.a($$02, $$3, "carpet_dye", ol.b);
        this.a($$02, $$4, "harness_dye", ol.f);
        this.g(dzs.jr, dzs.bZ);
        this.h(dlx.tV, dzs.bZ);
        this.i(dlx.xt, dzs.bZ);
        this.g(dzs.jn, dzs.bV);
        this.h(dlx.tR, dzs.bV);
        this.i(dlx.xp, dzs.bV);
        this.g(dzs.jo, dzs.bW);
        this.h(dlx.tS, dzs.bW);
        this.i(dlx.xq, dzs.bW);
        this.g(dzs.jl, dzs.bT);
        this.h(dlx.tP, dzs.bT);
        this.i(dlx.xn, dzs.bT);
        this.g(dzs.jj, dzs.bR);
        this.h(dlx.tN, dzs.bR);
        this.i(dlx.xl, dzs.bR);
        this.g(dzs.jp, dzs.bX);
        this.h(dlx.tT, dzs.bX);
        this.i(dlx.xr, dzs.bX);
        this.g(dzs.jf, dzs.bN);
        this.h(dlx.tJ, dzs.bN);
        this.i(dlx.xh, dzs.bN);
        this.g(dzs.jk, dzs.bS);
        this.h(dlx.tO, dzs.bS);
        this.i(dlx.xm, dzs.bS);
        this.g(dzs.jh, dzs.bP);
        this.h(dlx.tL, dzs.bP);
        this.i(dlx.xj, dzs.bP);
        this.g(dzs.je, dzs.bM);
        this.h(dlx.tI, dzs.bM);
        this.i(dlx.xg, dzs.bM);
        this.g(dzs.jd, dzs.bL);
        this.h(dlx.tH, dzs.bL);
        this.i(dlx.xf, dzs.bL);
        this.g(dzs.ji, dzs.bQ);
        this.h(dlx.tM, dzs.bQ);
        this.i(dlx.xk, dzs.bQ);
        this.g(dzs.jm, dzs.bU);
        this.h(dlx.tQ, dzs.bU);
        this.i(dlx.xo, dzs.bU);
        this.g(dzs.jq, dzs.bY);
        this.h(dlx.tU, dzs.bY);
        this.i(dlx.xs, dzs.bY);
        this.g(dzs.jc, dzs.bK);
        this.h(dlx.tG, dzs.bK);
        this.i(dlx.xe, dzs.bK);
        this.g(dzs.jg, dzs.bO);
        this.h(dlx.tK, dzs.bO);
        this.i(dlx.xi, dzs.bO);
        this.g(dzs.tX, dzs.ub);
        this.g(dzs.uU, dzs.uT);
        this.k(dlx.oS, dzs.bK);
        this.k(dlx.oT, dzs.bL);
        this.k(dlx.oU, dzs.bM);
        this.k(dlx.oV, dzs.bN);
        this.k(dlx.oW, dzs.bO);
        this.k(dlx.oX, dzs.bP);
        this.k(dlx.oY, dzs.bQ);
        this.k(dlx.oZ, dzs.bR);
        this.k(dlx.pa, dzs.bS);
        this.k(dlx.pb, dzs.bT);
        this.k(dlx.pc, dzs.bU);
        this.k(dlx.pd, dzs.bV);
        this.k(dlx.pe, dzs.bW);
        this.k(dlx.pf, dzs.bX);
        this.k(dlx.pg, dzs.bY);
        this.k(dlx.ph, dzs.bZ);
        this.j(dzs.fc, dlx.tB);
        this.l(dzs.iF, dzs.fc);
        this.m(dzs.iF, dlx.tB);
        this.j(dzs.eY, dlx.tx);
        this.l(dzs.iB, dzs.eY);
        this.m(dzs.iB, dlx.tx);
        this.j(dzs.eZ, dlx.ty);
        this.l(dzs.iC, dzs.eZ);
        this.m(dzs.iC, dlx.ty);
        this.j(dzs.eW, dlx.tv);
        this.l(dzs.iz, dzs.eW);
        this.m(dzs.iz, dlx.tv);
        this.j(dzs.eU, dlx.tt);
        this.l(dzs.ix, dzs.eU);
        this.m(dzs.ix, dlx.tt);
        this.j(dzs.fa, dlx.tz);
        this.l(dzs.iD, dzs.fa);
        this.m(dzs.iD, dlx.tz);
        this.j(dzs.eQ, dlx.tp);
        this.l(dzs.it, dzs.eQ);
        this.m(dzs.it, dlx.tp);
        this.j(dzs.eV, dlx.tu);
        this.l(dzs.iy, dzs.eV);
        this.m(dzs.iy, dlx.tu);
        this.j(dzs.eS, dlx.tr);
        this.l(dzs.iv, dzs.eS);
        this.m(dzs.iv, dlx.tr);
        this.j(dzs.eP, dlx.to);
        this.l(dzs.is, dzs.eP);
        this.m(dzs.is, dlx.to);
        this.j(dzs.eO, dlx.tn);
        this.l(dzs.ir, dzs.eO);
        this.m(dzs.ir, dlx.tn);
        this.j(dzs.eT, dlx.ts);
        this.l(dzs.iw, dzs.eT);
        this.m(dzs.iw, dlx.ts);
        this.j(dzs.eX, dlx.tw);
        this.l(dzs.iA, dzs.eX);
        this.m(dzs.iA, dlx.tw);
        this.j(dzs.fb, dlx.tA);
        this.l(dzs.iE, dzs.fb);
        this.m(dzs.iE, dlx.tA);
        this.j(dzs.eN, dlx.tm);
        this.l(dzs.iq, dzs.eN);
        this.m(dzs.iq, dlx.tm);
        this.j(dzs.eR, dlx.tq);
        this.l(dzs.iu, dzs.eR);
        this.m(dzs.iu, dlx.tq);
        this.n(dzs.ip, dlx.tB);
        this.n(dzs.il, dlx.tx);
        this.n(dzs.im, dlx.ty);
        this.n(dzs.ij, dlx.tv);
        this.n(dzs.ih, dlx.tt);
        this.n(dzs.in, dlx.tz);
        this.n(dzs.id, dlx.tp);
        this.n(dzs.ii, dlx.tu);
        this.n(dzs.if, dlx.tr);
        this.n(dzs.ic, dlx.to);
        this.n(dzs.ib, dlx.tn);
        this.n(dzs.ig, dlx.ts);
        this.n(dzs.ik, dlx.tw);
        this.n(dzs.io, dlx.tA);
        this.n(dzs.ia, dlx.tm);
        this.n(dzs.ie, dlx.tq);
        this.o(dzs.mX, dlx.tB);
        this.o(dzs.mT, dlx.tx);
        this.o(dzs.mU, dlx.ty);
        this.o(dzs.mR, dlx.tv);
        this.o(dzs.mP, dlx.tt);
        this.o(dzs.mV, dlx.tz);
        this.o(dzs.mL, dlx.tp);
        this.o(dzs.mQ, dlx.tu);
        this.o(dzs.mN, dlx.tr);
        this.o(dzs.mK, dlx.to);
        this.o(dzs.mJ, dlx.tn);
        this.o(dzs.mO, dlx.ts);
        this.o(dzs.mS, dlx.tw);
        this.o(dzs.mW, dlx.tA);
        this.o(dzs.mI, dlx.tm);
        this.o(dzs.mM, dlx.tq);
        this.a(dzs.nd);
        this.a(ol.b, (dwn)dlx.zz).a(Character.valueOf('S'), dlx.qY).a(Character.valueOf('H'), dlx.zf).b("S").b("H").b("has_string", this.b(dlx.qY)).b("has_honeycomb", this.b(dlx.zf)).a(this.b);
        this.p(dzs.rb, dlx.tB);
        this.p(dzs.qX, dlx.tx);
        this.p(dzs.qY, dlx.ty);
        this.p(dzs.qV, dlx.tv);
        this.p(dzs.qT, dlx.tt);
        this.p(dzs.qZ, dlx.tz);
        this.p(dzs.qP, dlx.tp);
        this.p(dzs.qU, dlx.tu);
        this.p(dzs.qR, dlx.tr);
        this.p(dzs.qO, dlx.to);
        this.p(dzs.qN, dlx.tn);
        this.p(dzs.qS, dlx.ts);
        this.p(dzs.qW, dlx.tw);
        this.p(dzs.ra, dlx.tA);
        this.p(dzs.qM, dlx.tm);
        this.p(dzs.qQ, dlx.tq);
        this.b(ol.a, (dwn)dzs.fr, 1).b(dzs.uh).b(dlx.rc).b("has_mud", this.b(dzs.uh)).a(this.b);
        this.a(ol.a, (dwn)dzs.fs, 4).a(Character.valueOf('#'), dzs.fr).b("##").b("##").b("has_packed_mud", this.b(dzs.fr)).a(this.b);
        this.b(ol.a, (dwn)dzs.ah, 1).b(dzs.uh).b(dlx.bN).b("has_mangrove_roots", this.b(dzs.ag)).a(this.b);
        this.a(ol.d, (dwn)dzs.hY, 6).a(Character.valueOf('#'), dzs.em).a(Character.valueOf('S'), dlx.qW).a(Character.valueOf('X'), dlx.qg).b("XSX").b("X#X").b("XSX").b("has_rail", this.b(dzs.dn)).a(this.b);
        this.b(ol.a, (dwn)dzs.g, 2).b(dzs.e).b(dzs.m).b("has_stone", this.b(dzs.e)).a(this.b);
        this.a(ol.b, (dwn)dzs.hJ).a(Character.valueOf('I'), dzs.cs).a(Character.valueOf('i'), dlx.qg).b("III").b(" i ").b("iii").b("has_iron_block", this.b(dzs.cs)).a(this.b);
        this.a(ol.b, (dwn)dlx.wS).a(Character.valueOf('/'), dlx.qW).a(Character.valueOf('_'), dzs.kx).b("///").b(" / ").b("/_/").b("has_stone_slab", this.b(dzs.kx)).a(this.b);
        this.a(ol.f, (dwn)dlx.pX, 4).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.rG).a(Character.valueOf('Y'), dlx.qZ).b("X").b("#").b("Y").b("has_feather", this.b(dlx.qZ)).b("has_flint", this.b(dlx.rG)).a(this.b);
        this.a(ol.b, (dwn)dzs.oR, 1).a(Character.valueOf('P'), bdy.b).a(Character.valueOf('S'), bdy.j).b("PSP").b("P P").b("PSP").b("has_planks", this.a(bdy.b)).b("has_wood_slab", this.a(bdy.j)).a(this.b);
        this.a(ol.i, (dwn)dzs.gD).a(Character.valueOf('S'), dlx.wE).a(Character.valueOf('G'), dzs.aX).a(Character.valueOf('O'), dzs.cK).b("GGG").b("GSG").b("OOO").b("has_nether_star", this.b(dlx.wE)).a(this.b);
        this.a(ol.b, (dwn)dzs.qf).a(Character.valueOf('P'), bdy.b).a(Character.valueOf('H'), dlx.zf).b("PPP").b("HHH").b("PPP").b("has_honeycomb", this.b(dlx.zf)).a(this.b);
        this.b(ol.g, (dwn)dlx.xB).b(dlx.pU).a(dlx.xz, 6).b("has_beetroot", this.b(dlx.xz)).a(this.b);
        this.b(ol.i, (dwn)dlx.tB).b(dlx.tj).b("black_dye").b("has_ink_sac", this.b(dlx.tj)).a(this.b);
        this.a((dwn)dlx.tB, (dwn)dzs.cn, "black_dye");
        this.b(ol.h, (dwn)dlx.us, 2).b(dlx.uk).b("has_blaze_rod", this.b(dlx.uk)).a(this.b);
        this.b(ol.i, (dwn)dlx.tx).b(dlx.qc).b("blue_dye").b("has_lapis_lazuli", this.b(dlx.qc)).a(this.b);
        this.a((dwn)dlx.tx, (dwn)dzs.cm, "blue_dye");
        this.b(ol.a, (dwn)dzs.nT, dzs.ju);
        this.b(ol.i, (dwn)dlx.tC, 3).b(dlx.tD).b("bonemeal").b("has_bone", this.b(dlx.tD)).a(this.b);
        this.b(ol.i, dlx.tC, ol.a, dlx.jT, "bone_meal_from_bone_block", "bonemeal");
        this.b(ol.i, (dwn)dlx.sB).a(dlx.sA, 3).b(dlx.sp).b("has_paper", this.b(dlx.sA)).a(this.b);
        this.a(ol.a, (dwn)dzs.cv).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('X'), dlx.sB).b("###").b("XXX").b("###").b("has_book", this.b(dlx.sB)).a(this.b);
        this.a(ol.f, (dwn)dlx.pW).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.qY).b(" #X").b("# X").b(" #X").b("has_string", this.b(dlx.qY)).a(this.b);
        this.a(ol.i, (dwn)dlx.pU, 4).a(Character.valueOf('#'), bdy.b).b("# #").b(" # ").b("has_brown_mushroom", this.b(dzs.cp)).b("has_red_mushroom", this.b(dzs.cq)).b("has_mushroom_stew", this.b(dlx.qX)).a(this.b);
        this.a(ol.g, (dwn)dlx.rd).a(Character.valueOf('#'), dlx.rc).b("###").b("has_wheat", this.b(dlx.rc)).a(this.b);
        this.a(ol.h, (dwn)dzs.gh).a(Character.valueOf('B'), dlx.uk).a(Character.valueOf('#'), bdy.bL).b(" B ").b("###").b("has_blaze_rod", this.b(dlx.uk)).a(this.b);
        this.a(ol.a, (dwn)dzs.ct).a(Character.valueOf('#'), dlx.sx).b("##").b("##").b("has_brick", this.b(dlx.sx)).a(this.b);
        this.b(ol.i, (dwn)dlx.ty).b(dlx.tl).b("brown_dye").b("has_cocoa_beans", this.b(dlx.tl)).a(this.b);
        this.a(ol.i, (dwn)dlx.sk).a(Character.valueOf('#'), dlx.qg).b("# #").b(" # ").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.g, (dwn)dzs.eL).a(Character.valueOf('A'), dlx.sq).a(Character.valueOf('B'), dlx.tE).a(Character.valueOf('C'), dlx.rc).a(Character.valueOf('E'), bdy.az).b("AAA").b("BEB").b("CCC").b("has_egg", this.a(bdy.az)).a(this.b);
        this.a(ol.b, (dwn)dzs.pe).a(Character.valueOf('L'), bdy.E).a(Character.valueOf('S'), dlx.qW).a(Character.valueOf('C'), bdy.bq).b(" S ").b("SCS").b("LLL").b("has_stick", this.b(dlx.qW)).b("has_coal", this.a(bdy.bq)).a(this.b);
        this.a(ol.d, (dwn)dlx.pn).a(Character.valueOf('#'), dlx.sZ).a(Character.valueOf('X'), dlx.wr).b("# ").b(" X").b("has_carrot", this.b(dlx.wr)).a(this.b);
        this.a(ol.d, (dwn)dlx.po).a(Character.valueOf('#'), dlx.sZ).a(Character.valueOf('X'), dlx.dQ).b("# ").b(" X").b("has_warped_fungus", this.b(dlx.dQ)).a(this.b);
        this.a(ol.h, (dwn)dzs.gi).a(Character.valueOf('#'), dlx.qg).b("# #").b("# #").b("###").b("has_water_bucket", this.b(dlx.sl)).a(this.b);
        this.a(ol.b, (dwn)dzs.qc).a(Character.valueOf('#'), bdy.j).b("# #").b("# #").b("###").b("has_wood_slab", this.a(bdy.j)).a(this.b);
        this.a(ol.b, (dwn)dzs.cS).a(Character.valueOf('#'), bdy.b).b("###").b("# #").b("###").b("has_lots_of_items", aj.f.a(new ce.a(Optional.empty(), new ce.a.a(cq.d.b(10), cq.d.c, cq.d.c), List.of()))).a(this.b);
        this.a(ol.b, (dwn)dzs.ts).a(Character.valueOf('#'), dlx.qi).a(Character.valueOf('X'), dlx.ft).b("###").b("#X#").b("###").b("has_copper_chest", this.b(dlx.Bh)).a(this.b);
        this.b(ol.d, (dwn)dlx.pj).b(dzs.cS).b(dlx.pi).b("has_minecart", this.b(dlx.pi)).a(this.b);
        this.c((dwn)dlx.pA, dlx.pz);
        this.c((dwn)dlx.pw, dlx.pv);
        this.c((dwn)dlx.pE, dlx.pD);
        this.c((dwn)dlx.pG, dlx.pF);
        this.c((dwn)dlx.py, dlx.px);
        this.c((dwn)dlx.ps, dlx.pr);
        this.c((dwn)dlx.pu, dlx.pt);
        this.c((dwn)dlx.pI, dlx.pH);
        this.b(ol.a, (dwn)dzs.hV, dqo.a((dwn)dzs.kG)).b("has_chiseled_quartz_block", this.b(dzs.hV)).b("has_quartz_block", this.b(dzs.hU)).b("has_quartz_pillar", this.b(dzs.hW)).a(this.b);
        this.b(ol.a, (dwn)dzs.fq, dqo.a((dwn)dzs.kD)).b("has_tag", this.a(bdy.c)).a(this.b);
        this.a(ol.a, (dwn)dzs.eu, (dwn)dlx.sy);
        this.a(ol.e, (dwn)dlx.ta).a(Character.valueOf('#'), dlx.qk).a(Character.valueOf('X'), dlx.mB).b(" # ").b("#X#").b(" # ").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.a(ol.i, (dwn)dlx.pY, ol.a, dlx.aF);
        this.a(ol.a, (dwn)dzs.k, 4).a(Character.valueOf('D'), dzs.j).a(Character.valueOf('G'), dzs.O).b("DG").b("GD").b("has_gravel", this.b(dzs.O)).a(this.b);
        this.a(ol.c, (dwn)dzs.hP).a(Character.valueOf('#'), dzs.em).a(Character.valueOf('X'), dlx.qd).a(Character.valueOf('I'), dzs.b).b(" # ").b("#X#").b("III").b("has_quartz", this.b(dlx.qd)).a(this.b);
        this.a(ol.e, (dwn)dlx.sG).a(Character.valueOf('#'), dlx.qg).a(Character.valueOf('X'), dlx.mB).b(" # ").b("#X#").b(" # ").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.a(ol.g, (dwn)dlx.tW, 8).a(Character.valueOf('#'), dlx.rc).a(Character.valueOf('X'), dlx.tl).b("#X#").b("has_cocoa", this.b(dlx.tl)).a(this.b);
        this.a(ol.b, (dwn)dzs.cX).a(Character.valueOf('#'), bdy.b).b("##").b("##").b("unlock_right_away", cy.a.e()).a(false).a(this.b);
        this.a(ol.f, (dwn)dlx.yz).a(Character.valueOf('~'), dlx.qY).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('&'), dlx.qg).a(Character.valueOf('$'), dzs.gw).b("#&#").b("~$~").b(" # ").b("has_string", this.b(dlx.qY)).b("has_iron_ingot", this.b(dlx.qg)).b("has_tripwire_hook", this.b(dzs.gw)).a(this.b);
        this.a(ol.b, (dwn)dzs.oQ).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('@'), dlx.qY).b("@@").b("##").b("has_string", this.b(dlx.qY)).a(this.b);
        this.b(ol.a, (dwn)dzs.ki, dqo.a((dwn)dzs.kH)).b("has_red_sandstone", this.b(dzs.kh)).b("has_chiseled_red_sandstone", this.b(dzs.ki)).b("has_cut_red_sandstone", this.b(dzs.kj)).a(this.b);
        this.g(ol.a, dzs.bd, dzs.ky);
        this.b(ol.i, dlx.qi, ol.a, dlx.aN, ox.e(dlx.qi), ox.d(dlx.qi));
        this.b(ol.i, (dwn)dlx.qi, 9).b(dzs.sw).b(ox.d(dlx.qi)).b(ox.c(dzs.sw), this.b(dzs.sw)).a(this.b, ox.r(dlx.qi, dzs.sw));
        this.b(dgz.a(dhb.a));
        this.b(ol.i, (dwn)dlx.tv, 2).b(dlx.tx).b(dlx.tz).b("cyan_dye").b("has_green_dye", this.b(dlx.tz)).b("has_blue_dye", this.b(dlx.tx)).a(this.b);
        this.a(ol.a, (dwn)dzs.iT).a(Character.valueOf('S'), dlx.wL).a(Character.valueOf('I'), dlx.tB).b("SSS").b("SIS").b("SSS").b("has_prismarine_shard", this.b(dlx.wL)).a(this.b);
        this.a(ol.c, (dwn)dzs.hQ).a(Character.valueOf('Q'), dlx.qd).a(Character.valueOf('G'), dzs.aX).a(Character.valueOf('W'), bdy.j).b("GGG").b("QQQ").b("WWW").b("has_quartz", this.b(dlx.qd)).a(this.b);
        this.a(ol.a, (dwn)dzs.uv, 4).a(Character.valueOf('S'), dzs.un).b("SS").b("SS").b("has_polished_deepslate", this.b(dzs.un)).a(this.b);
        this.a(ol.a, (dwn)dzs.ur, 4).a(Character.valueOf('S'), dzs.uv).b("SS").b("SS").b("has_deepslate_bricks", this.b(dzs.uv)).a(this.b);
        this.a(ol.d, (dwn)dzs.bx, 6).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dzs.dY).a(Character.valueOf('X'), dlx.qg).b("X X").b("X#X").b("XRX").b("has_rail", this.b(dzs.dn)).a(this.b);
        this.a(ol.e, (dwn)dlx.qP).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("XX").b("X#").b(" #").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.i, (dwn)dlx.qa, ol.a, dlx.aP);
        this.a(ol.f, (dwn)dlx.rx).a(Character.valueOf('X'), dlx.qa).b("X X").b("X X").b("has_diamond", this.b(dlx.qa)).a(this.b);
        this.a(ol.f, (dwn)dlx.rv).a(Character.valueOf('X'), dlx.qa).b("X X").b("XXX").b("XXX").b("has_diamond", this.b(dlx.qa)).a(this.b);
        this.a(ol.f, (dwn)dlx.ru).a(Character.valueOf('X'), dlx.qa).b("XXX").b("X X").b("has_diamond", this.b(dlx.qa)).a(this.b);
        this.a(ol.e, (dwn)dlx.qQ).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("XX").b(" #").b(" #").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.f, (dwn)dlx.rw).a(Character.valueOf('X'), dlx.qa).b("XXX").b("X X").b("X X").b("has_diamond", this.b(dlx.qa)).a(this.b);
        this.a(ol.e, (dwn)dlx.qO).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("XXX").b(" # ").b(" # ").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.e, (dwn)dlx.qN).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("X").b("#").b("#").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.f, (dwn)dlx.qM).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("X").b("X").b("#").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.f, (dwn)dlx.xN).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bA).b("  X").b(" # ").b("#  ").b("has_diamond", this.a(bdy.bA)).a(this.b);
        this.a(ol.a, (dwn)dzs.e, 2).a(Character.valueOf('Q'), dlx.qd).a(Character.valueOf('C'), dzs.m).b("CQ").b("QC").b("has_quartz", this.b(dlx.qd)).a(this.b);
        this.a(ol.c, (dwn)dzs.bb).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dzs.m).a(Character.valueOf('X'), dlx.pW).b("###").b("#X#").b("#R#").b("has_bow", this.b(dlx.pW)).a(this.b);
        this.a(ol.a, (dwn)dzs.tR, (dwn)dlx.zU);
        this.a(ol.c, (dwn)dzs.hZ).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dzs.m).b("###").b("# #").b("#R#").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.a(ol.i, (dwn)dlx.qb, ol.a, dlx.hk);
        this.a(ol.b, (dwn)dzs.gg).a(Character.valueOf('B'), dlx.sB).a(Character.valueOf('#'), dzs.cK).a(Character.valueOf('D'), dlx.qa).b(" B ").b("D#D").b("###").b("has_obsidian", this.b(dzs.cK)).a(this.b);
        this.a(ol.b, (dwn)dzs.gv).a(Character.valueOf('#'), dzs.cK).a(Character.valueOf('E'), dlx.uw).b("###").b("#E#").b("###").b("has_ender_eye", this.b(dlx.uw)).a(this.b);
        this.b(ol.i, (dwn)dlx.uw).b(dlx.uj).b(dlx.us).b("has_blaze_powder", this.b(dlx.us)).a(this.b);
        this.a(ol.a, (dwn)dzs.lv, 4).a(Character.valueOf('#'), dzs.go).b("##").b("##").b("has_end_stone", this.b(dzs.go)).a(this.b);
        this.a(ol.b, (dwn)dlx.xu).a(Character.valueOf('T'), dlx.ul).a(Character.valueOf('E'), dlx.uw).a(Character.valueOf('G'), dzs.aX).b("GGG").b("GEG").b("GTG").b("has_ender_eye", this.b(dlx.uw)).a(this.b);
        this.a(ol.b, (dwn)dzs.lp, 4).a(Character.valueOf('#'), dlx.xw).a(Character.valueOf('/'), dlx.uk).b("/").b("#").b("has_chorus_fruit_popped", this.b(dlx.xw)).a(this.b);
        this.b(ol.h, (dwn)dlx.ur).b(dlx.uq).b(dzs.cp).b(dlx.tE).b("has_spider_eye", this.b(dlx.uq)).a(this.b);
        this.b(ol.i, (dwn)dlx.wi, 3).b(dlx.ra).b(dlx.us).a(dqo.a(dlx.pY, dlx.pZ)).b("has_blaze_powder", this.b(dlx.us)).a(this.b);
        this.b(ol.i, (dwn)dlx.wG, 3).b(dlx.ra).b(dlx.sA).b("has_gunpowder", this.b(dlx.ra)).a(this.b, "firework_rocket_simple");
        this.a(ol.e, (dwn)dlx.sZ).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.qY).b("  #").b(" #X").b("# X").b("has_string", this.b(dlx.qY)).a(this.b);
        this.b(ol.e, (dwn)dlx.pT).b(dlx.qg).b(dlx.rG).b("has_flint", this.b(dlx.rG)).b("has_obsidian", this.b(dzs.cK)).a(this.b);
        this.a(ol.b, (dwn)dzs.gG).a(Character.valueOf('#'), dlx.sx).b("# #").b(" # ").b("has_brick", this.b(dlx.sx)).a(this.b);
        this.a(ol.b, (dwn)dzs.da).a(Character.valueOf('#'), bdy.bL).b("###").b("# #").b("###").b("has_cobblestone", this.a(bdy.bL)).a(this.b);
        this.b(ol.d, (dwn)dlx.pk).b(dzs.da).b(dlx.pi).b("has_minecart", this.b(dlx.pi)).a(this.b);
        this.a(ol.h, (dwn)dlx.uo, 3).a(Character.valueOf('#'), dzs.aX).b("# #").b(" # ").b("has_glass", this.b(dzs.aX)).a(this.b);
        this.a(ol.b, (dwn)dzs.fG, 16).a(Character.valueOf('#'), dzs.aX).b("###").b("###").b("has_glass", this.b(dzs.aX)).a(this.b);
        this.a(ol.a, (dwn)dzs.eH, (dwn)dlx.tc);
        this.b(ol.b, (dwn)dlx.wp).b(dlx.wo).b(dlx.tk).b("has_item_frame", this.b(dlx.wo)).b("has_glow_ink_sac", this.b(dlx.tk)).a(this.b);
        this.a(ol.g, (dwn)dlx.rK).a(Character.valueOf('#'), dlx.qk).a(Character.valueOf('X'), dlx.pV).b("###").b("#X#").b("###").b("has_gold_ingot", this.b(dlx.qk)).a(this.b);
        this.a(ol.e, (dwn)dlx.qF).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("XX").b("X#").b(" #").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.a(ol.f, (dwn)dlx.rB).a(Character.valueOf('X'), dlx.qk).b("X X").b("X X").b("has_gold_ingot", this.b(dlx.qk)).a(this.b);
        this.a(ol.h, (dwn)dlx.ww).a(Character.valueOf('#'), dlx.um).a(Character.valueOf('X'), dlx.wr).b("###").b("#X#").b("###").b("has_gold_nugget", this.b(dlx.um)).a(this.b);
        this.a(ol.f, (dwn)dlx.rz).a(Character.valueOf('X'), dlx.qk).b("X X").b("XXX").b("XXX").b("has_gold_ingot", this.b(dlx.qk)).a(this.b);
        this.a(ol.f, (dwn)dlx.ry).a(Character.valueOf('X'), dlx.qk).b("XXX").b("X X").b("has_gold_ingot", this.b(dlx.qk)).a(this.b);
        this.a(ol.e, (dwn)dlx.qG).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("XX").b(" #").b(" #").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.a(ol.f, (dwn)dlx.rA).a(Character.valueOf('X'), dlx.qk).b("XXX").b("X X").b("X X").b("has_gold_ingot", this.b(dlx.qk)).a(this.b);
        this.a(ol.e, (dwn)dlx.qE).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("XXX").b(" # ").b(" # ").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.a(ol.d, (dwn)dzs.bw, 6).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.qk).b("X X").b("X#X").b("XRX").b("has_rail", this.b(dzs.dn)).a(this.b);
        this.a(ol.e, (dwn)dlx.qD).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("X").b("#").b("#").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.a(ol.f, (dwn)dlx.qC).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("X").b("X").b("#").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.a(ol.f, (dwn)dlx.xM).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bz).b("  X").b(" # ").b("#  ").b("has_gold_ingot", this.a(bdy.bz)).a(this.b);
        this.b(ol.i, dlx.qk, ol.a, dlx.aO, "gold_ingot_from_gold_block", "gold_ingot");
        this.a(ol.i, dlx.um, ol.i, dlx.qk, "gold_ingot_from_nuggets", "gold_ingot");
        this.b(ol.a, (dwn)dzs.c).b(dzs.e).b(dlx.qd).b("has_quartz", this.b(dlx.qd)).a(this.b);
        this.b(ol.i, (dwn)dlx.tt, 2).b(dlx.tB).b(dlx.tm).b("gray_dye").b("has_white_dye", this.b(dlx.tm)).b("has_black_dye", this.b(dlx.tB)).a(this.b);
        this.b(ol.a, (dwn)dzs.jb, dlx.rc);
        this.d((dwn)dzs.hO, dlx.qg);
        this.b(ol.g, (dwn)dlx.zi, 4).b(dlx.mJ).a(dlx.uo, 4).b("has_honey_block", this.b(dzs.qg)).a(this.b);
        this.a(ol.c, (dwn)dzs.qg, (dwn)dlx.zi);
        this.a(ol.b, (dwn)dzs.qh, (dwn)dlx.zf);
        this.a(ol.c, (dwn)dzs.hT).a(Character.valueOf('C'), dzs.cS).a(Character.valueOf('I'), dlx.qg).b("I I").b("ICI").b(" I ").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.b(ol.d, (dwn)dlx.pm).b(dzs.hT).b(dlx.pi).b("has_minecart", this.b(dlx.pi)).a(this.b);
        this.a(ol.e, (dwn)dlx.qK).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("XX").b("X#").b(" #").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.a(ol.b, (dwn)dzs.fC, 16).a(Character.valueOf('#'), dlx.qg).b("###").b("###").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.b, (dwn)dzs.fD.d(), 16).a(Character.valueOf('#'), dlx.qi).b("###").b("###").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.f, (dwn)dlx.rt).a(Character.valueOf('X'), dlx.qg).b("X X").b("X X").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.f, (dwn)dlx.rr).a(Character.valueOf('X'), dlx.qg).b("X X").b("XXX").b("XXX").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a((dwn)dzs.dZ, dqo.a((dwn)dlx.qg)).a(ox.c(dlx.qg), this.b(dlx.qg)).a(this.b);
        this.a(ol.f, (dwn)dlx.rq).a(Character.valueOf('X'), dlx.qg).b("XXX").b("X X").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.e, (dwn)dlx.qL).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("XX").b(" #").b(" #").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.b(ol.i, dlx.qg, ol.a, dlx.aM, "iron_ingot_from_iron_block", "iron_ingot");
        this.a(ol.i, dlx.xR, ol.i, dlx.qg, "iron_ingot_from_nuggets", "iron_ingot");
        this.a(ol.f, (dwn)dlx.rs).a(Character.valueOf('X'), dlx.qg).b("XXX").b("X X").b("X X").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.e, (dwn)dlx.qJ).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("XXX").b(" # ").b(" # ").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.a(ol.e, (dwn)dlx.qI).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("X").b("#").b("#").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.a(ol.f, (dwn)dlx.qH).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("X").b("X").b("#").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.a(ol.f, (dwn)dlx.xL).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.by).b("  X").b(" # ").b("#  ").b("has_iron_ingot", this.a(bdy.by)).a(this.b);
        this.a(ol.c, (dwn)dzs.iQ, (dwn)dlx.qg);
        this.a(ol.b, (dwn)dlx.wo).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.sp).b("###").b("#X#").b("###").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.b, (dwn)dzs.ew).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('X'), dlx.qa).b("###").b("#X#").b("###").b("has_diamond", this.b(dlx.qa)).a(this.b);
        this.a(ol.b, (dwn)dzs.dm, 3).a(Character.valueOf('#'), dlx.qW).b("# #").b("###").b("# #").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.i, (dwn)dlx.qc, ol.a, dlx.cP);
        this.a(ol.e, (dwn)dlx.wZ, 2).a(Character.valueOf('~'), dlx.qY).b("~~ ").b("~~ ").b("  ~").b("has_string", this.b(dlx.qY)).a(this.b);
        this.a(ol.i, (dwn)dlx.sp, (dwn)dlx.wR);
        this.a(ol.f, (dwn)dlx.rh).a(Character.valueOf('X'), dlx.sp).b("X X").b("X X").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.f, (dwn)dlx.rf).a(Character.valueOf('X'), dlx.sp).b("X X").b("XXX").b("XXX").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.f, (dwn)dlx.re).a(Character.valueOf('X'), dlx.sp).b("XXX").b("X X").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.f, (dwn)dlx.rg).a(Character.valueOf('X'), dlx.sp).b("XXX").b("X X").b("X X").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.i, (dwn)dlx.wY).a(Character.valueOf('X'), dlx.sp).b("X X").b("XXX").b("X X").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.f, (dwn)dlx.oR).a(Character.valueOf('X'), dlx.sp).a(Character.valueOf('#'), dlx.qg).b(" X ").b("X#X").b("has_leather", this.b(dlx.sp)).a(this.b);
        this.a(ol.i, dlx.xS, ol.i, dlx.qi, "copper_ingot_from_nuggets", "copper_ingot");
        this.a(ol.e, (dwn)dlx.qv).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("XX").b("X#").b(" #").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.e, (dwn)dlx.qw).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("XX").b(" #").b(" #").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.e, (dwn)dlx.qu).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("XXX").b(" # ").b(" # ").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.e, (dwn)dlx.qt).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("X").b("#").b("#").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.f, (dwn)dlx.qs).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("X").b("X").b("#").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.f, (dwn)dlx.xK).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bx).b("  X").b(" # ").b("#  ").b("has_copper_ingot", this.a(bdy.bx)).a(this.b);
        this.a(ol.f, (dwn)dlx.rl).a(Character.valueOf('X'), dlx.qi).b("X X").b("X X").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.f, (dwn)dlx.rj).a(Character.valueOf('X'), dlx.qi).b("X X").b("XXX").b("XXX").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.f, (dwn)dlx.ri).a(Character.valueOf('X'), dlx.qi).b("XXX").b("X X").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.f, (dwn)dlx.rk).a(Character.valueOf('X'), dlx.qi).b("XXX").b("X X").b("X X").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.c, (dwn)dzs.oX).a(Character.valueOf('S'), bdy.j).a(Character.valueOf('B'), dzs.cv).b("SSS").b(" B ").b(" S ").b("has_book", this.b(dlx.sB)).a(this.b);
        this.a(ol.c, (dwn)dzs.dX).a(Character.valueOf('#'), dzs.m).a(Character.valueOf('X'), dlx.qW).b("X").b("#").b("has_cobblestone", this.b(dzs.m)).a(this.b);
        this.a((dwn)dlx.tp, (dwn)dzs.ce, "light_blue_dye");
        this.b(ol.i, (dwn)dlx.tp, 2).b(dlx.tx).b(dlx.tm).b("light_blue_dye").b("has_blue_dye", this.b(dlx.tx)).b("has_white_dye", this.b(dlx.tm)).a(this.b, "light_blue_dye_from_blue_white_dye");
        this.a((dwn)dlx.tu, (dwn)dzs.cg, "light_gray_dye");
        this.b(ol.i, (dwn)dlx.tu, 2).b(dlx.tt).b(dlx.tm).b("light_gray_dye").b("has_gray_dye", this.b(dlx.tt)).b("has_white_dye", this.b(dlx.tm)).a(this.b, "light_gray_dye_from_gray_white_dye");
        this.b(ol.i, (dwn)dlx.tu, 3).b(dlx.tB).a(dlx.tm, 2).b("light_gray_dye").b("has_white_dye", this.b(dlx.tm)).b("has_black_dye", this.b(dlx.tB)).a(this.b, "light_gray_dye_from_black_white_dye");
        this.a((dwn)dlx.tu, (dwn)dzs.cl, "light_gray_dye");
        this.a((dwn)dlx.tu, (dwn)dzs.cj, "light_gray_dye");
        this.d((dwn)dzs.hN, dlx.qk);
        this.a(ol.c, (dwn)dzs.tI).a(Character.valueOf('#'), dlx.qi).b("#").b("#").b("#").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.b(ol.i, (dwn)dlx.tr, 2).b(dlx.tz).b(dlx.tm).b("has_green_dye", this.b(dlx.tz)).b("has_white_dye", this.b(dlx.tm)).a(this.b);
        this.a(ol.a, (dwn)dzs.eK).a(Character.valueOf('A'), dzs.eJ).a(Character.valueOf('B'), dzs.cL).b("A").b("B").b("has_carved_pumpkin", this.b(dzs.eJ)).a(this.b);
        this.a((dwn)dlx.to, (dwn)dzs.cf, "magenta_dye");
        this.b(ol.i, (dwn)dlx.to, 4).b(dlx.tx).a(dlx.tA, 2).b(dlx.tm).b("magenta_dye").b("has_blue_dye", this.b(dlx.tx)).b("has_rose_red", this.b(dlx.tA)).b("has_white_dye", this.b(dlx.tm)).a(this.b, "magenta_dye_from_blue_red_white_dye");
        this.b(ol.i, (dwn)dlx.to, 3).b(dlx.tx).b(dlx.tA).b(dlx.ts).b("magenta_dye").b("has_pink_dye", this.b(dlx.ts)).b("has_blue_dye", this.b(dlx.tx)).b("has_red_dye", this.b(dlx.tA)).a(this.b, "magenta_dye_from_blue_red_pink");
        this.a(dlx.to, (dwn)dzs.jw, "magenta_dye", 2);
        this.b(ol.i, (dwn)dlx.to, 2).b(dlx.tw).b(dlx.ts).b("magenta_dye").b("has_pink_dye", this.b(dlx.ts)).b("has_purple_dye", this.b(dlx.tw)).a(this.b, "magenta_dye_from_purple_and_pink");
        this.a(ol.a, (dwn)dzs.lF, (dwn)dlx.ut);
        this.b(ol.h, (dwn)dlx.ut).b(dlx.us).b(dlx.sC).b("has_blaze_powder", this.b(dlx.us)).a(this.b);
        this.a(ol.i, (dwn)dlx.wv).a(Character.valueOf('#'), dlx.sA).a(Character.valueOf('X'), dlx.sG).b("###").b("#X#").b("###").b("has_compass", this.b(dlx.sG)).a(this.b);
        this.a(ol.a, (dwn)dzs.fI, (dwn)dlx.ua, "has_melon");
        this.b(ol.i, (dwn)dlx.ud).b(dlx.ua).b("has_melon", this.b(dlx.ua)).a(this.b);
        this.a(ol.d, (dwn)dlx.pi).a(Character.valueOf('#'), dlx.qg).b("# #").b("###").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.b(ol.a, (dwn)dzs.cJ).b(dzs.m).b(dzs.fN).b("mossy_cobblestone").b("has_vine", this.b(dzs.fN)).a(this.b, ox.r(dzs.cJ, dzs.fN));
        this.b(ol.a, (dwn)dzs.fo).b(dzs.fn).b(dzs.fN).b("mossy_stone_bricks").b("has_vine", this.b(dzs.fN)).a(this.b, ox.r(dzs.fo, dzs.fN));
        this.b(ol.a, (dwn)dzs.cJ).b(dzs.m).b(dzs.ub).b("mossy_cobblestone").b("has_moss_block", this.b(dzs.ub)).a(this.b, ox.r(dzs.cJ, dzs.ub));
        this.b(ol.a, (dwn)dzs.fo).b(dzs.fn).b(dzs.ub).b("mossy_stone_bricks").b("has_moss_block", this.b(dzs.ub)).a(this.b, ox.r(dzs.fo, dzs.ub));
        this.b(ol.g, (dwn)dlx.qX).b(dzs.cp).b(dzs.cq).b(dlx.pU).b("has_mushroom_stew", this.b(dlx.qX)).b("has_bowl", this.b(dlx.pU)).b("has_brown_mushroom", this.b(dzs.cp)).b("has_red_mushroom", this.b(dzs.cq)).a(this.b);
        mi.h.s().forEach($$0 -> {
            eih $$1 = eih.a($$0);
            if ($$1 != null) {
                this.a((dlp)$$0, $$1);
            }
        });
        this.a(ol.a, (dwn)dzs.gc, (dwn)dlx.wJ);
        this.a(ol.a, (dwn)dzs.fX, (dwn)dlx.wK);
        this.a(ol.i, (dwn)dlx.gI, ol.a, dlx.gJ);
        this.a(ol.i, (dwn)dzs.cQ).a(Character.valueOf('R'), dlx.gJ).a(Character.valueOf('L'), dzs.ae).b(" L ").b(" R ").b(" L ").b("has_resin_block", this.b(dlx.gJ)).a(this.b);
        this.b(ol.a, (dwn)dzs.lG, dlx.un);
        this.a(ol.c, (dwn)dzs.bf).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('X'), dlx.mB).b("###").b("#X#").b("###").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.a(ol.c, (dwn)dzs.lK).a(Character.valueOf('Q'), dlx.qd).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dzs.m).b("###").b("RRQ").b("###").b("has_quartz", this.b(dlx.qd)).a(this.b);
        this.a((dwn)dlx.tn, (dwn)dzs.ci, "orange_dye");
        this.b(ol.i, (dwn)dlx.tn, 2).b(dlx.tA).b(dlx.tq).b("orange_dye").b("has_red_dye", this.b(dlx.tA)).b("has_yellow_dye", this.b(dlx.tq)).a(this.b, "orange_dye_from_red_yellow");
        this.a(ol.b, (dwn)dlx.rJ).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.a).b("###").b("#X#").b("###").b("has_wool", this.a(bdy.a)).a(this.b);
        this.a(ol.i, (dwn)dlx.sA, 3).a(Character.valueOf('#'), dzs.ev).b("###").b("has_reeds", this.b(dzs.ev)).a(this.b);
        this.a(ol.a, (dwn)dzs.hW, 2).a(Character.valueOf('#'), dzs.hU).b("#").b("#").b("has_chiseled_quartz_block", this.b(dzs.hV)).b("has_quartz_block", this.b(dzs.hU)).b("has_quartz_pillar", this.b(dzs.hW)).a(this.b);
        this.b(ol.a, (dwn)dzs.ju, dzs.eq);
        this.a(dlx.ts, (dwn)dzs.jy, "pink_dye", 2);
        this.a((dwn)dlx.ts, (dwn)dzs.ck, "pink_dye");
        this.a((dwn)dlx.ts, (dwn)dzs.et, "pink_dye");
        this.b(ol.i, (dwn)dlx.ts, 2).b(dlx.tA).b(dlx.tm).b("pink_dye").b("has_white_dye", this.b(dlx.tm)).b("has_red_dye", this.b(dlx.tA)).a(this.b, "pink_dye_from_red_white_dye");
        this.a(ol.c, (dwn)dzs.bI).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('#'), dzs.m).a(Character.valueOf('T'), bdy.b).a(Character.valueOf('X'), dlx.qg).b("TTT").b("#X#").b("#R#").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.e(ol.a, dzs.eC, dzs.eB);
        this.a(ol.a, (dwn)dzs.iR, (dwn)dlx.wL);
        this.b(ol.a, (dwn)dzs.iS, dlx.wL);
        this.b(ol.g, (dwn)dlx.wF).b(dzs.fH).b(dlx.tE).a(bdy.az).b("has_carved_pumpkin", this.b(dzs.eJ)).b("has_pumpkin", this.b(dzs.fH)).a(this.b);
        this.b(ol.i, (dwn)dlx.uc, 4).b(dzs.fH).b("has_pumpkin", this.b(dzs.fH)).a(this.b);
        this.b(ol.i, (dwn)dlx.tw, 2).b(dlx.tx).b(dlx.tA).b("has_blue_dye", this.b(dlx.tx)).b("has_red_dye", this.b(dlx.tA)).a(this.b);
        this.a(ol.b, (dwn)dzs.lL).a(Character.valueOf('#'), dzs.cS).a(Character.valueOf('-'), dlx.xQ).b("-").b("#").b("-").b("has_shulker_shell", this.b(dlx.xQ)).a(this.b);
        this.c();
        this.a(ol.a, (dwn)dzs.ls, 4).a(Character.valueOf('F'), dlx.xw).b("FF").b("FF").b("has_chorus_fruit_popped", this.b(dlx.xw)).a(this.b);
        this.a(ol.a, (dwn)dzs.lt).a(Character.valueOf('#'), dzs.kJ).b("#").b("#").b("has_purpur_block", this.b(dzs.ls)).a(this.b);
        this.a(ol.a, (dwn)dzs.kJ, dqo.a(dzs.ls, dzs.lt)).a("has_purpur_block", this.b(dzs.ls)).a(this.b);
        this.b((dwn)dzs.lu, dqo.a(dzs.ls, dzs.lt)).a("has_purpur_block", this.b(dzs.ls)).a(this.b);
        this.a(ol.a, (dwn)dzs.hU, (dwn)dlx.qd);
        this.a(ol.a, (dwn)dzs.qK, 4).a(Character.valueOf('#'), dzs.hU).b("##").b("##").b("has_quartz_block", this.b(dzs.hU)).a(this.b);
        this.a(ol.a, (dwn)dzs.kG, dqo.a(dzs.hV, dzs.hU, dzs.hW)).a("has_chiseled_quartz_block", this.b(dzs.hV)).a("has_quartz_block", this.b(dzs.hU)).a("has_quartz_pillar", this.b(dzs.hW)).a(this.b);
        this.b((dwn)dzs.hX, dqo.a(dzs.hV, dzs.hU, dzs.hW)).a("has_chiseled_quartz_block", this.b(dzs.hV)).a("has_quartz_block", this.b(dzs.hU)).a("has_quartz_pillar", this.b(dzs.hW)).a(this.b);
        this.b(ol.g, (dwn)dlx.wP).b(dlx.wt).b(dlx.wO).b(dlx.pU).b(dlx.wr).b(dzs.cp).b("rabbit_stew").b("has_cooked_rabbit", this.b(dlx.wO)).a(this.b, ox.r(dlx.wP, dlx.dN));
        this.b(ol.g, (dwn)dlx.wP).b(dlx.wt).b(dlx.wO).b(dlx.pU).b(dlx.wr).b(dzs.cq).b("rabbit_stew").b("has_cooked_rabbit", this.b(dlx.wO)).a(this.b, ox.r(dlx.wP, dlx.dO));
        this.a(ol.d, (dwn)dzs.dn, 16).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.qg).b("X X").b("X#X").b("X X").b("has_minecart", this.b(dlx.pi)).a(this.b);
        this.a(ol.c, (dwn)dlx.mB, ol.c, dlx.mD);
        this.a(ol.c, (dwn)dzs.gq).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('G'), dzs.eH).b(" R ").b("RGR").b(" R ").b("has_glowstone", this.b(dzs.eH)).a(this.b);
        this.a(ol.c, (dwn)dzs.em).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dlx.mB).b("X").b("#").b("has_redstone", this.b(dlx.mB)).a(this.b);
        this.a((dwn)dlx.tA, (dwn)dlx.xz, "red_dye");
        this.a((dwn)dlx.tA, (dwn)dzs.cd, "red_dye");
        this.a(dlx.tA, (dwn)dzs.jx, "red_dye", 2);
        this.a((dwn)dlx.tn, (dwn)dzs.uW, "orange_dye");
        this.a((dwn)dlx.tt, (dwn)dzs.uX, "gray_dye");
        this.b(ol.i, (dwn)dlx.tA).b(dzs.ch).b("red_dye").b("has_red_flower", this.b(dzs.ch)).a(this.b, "red_dye_from_tulip");
        this.a(ol.a, (dwn)dzs.lH).a(Character.valueOf('W'), dlx.un).a(Character.valueOf('N'), dlx.wJ).b("NW").b("WN").b("has_nether_wart", this.b(dlx.un)).a(this.b);
        this.a(ol.a, (dwn)dzs.kh).a(Character.valueOf('#'), dzs.N).b("##").b("##").b("has_sand", this.b(dzs.N)).a(this.b);
        this.a(ol.a, (dwn)dzs.kH, dqo.a(dzs.kh, dzs.ki)).a("has_red_sandstone", this.b(dzs.kh)).a("has_chiseled_red_sandstone", this.b(dzs.ki)).a(this.b);
        this.b((dwn)dzs.kk, dqo.a(dzs.kh, dzs.ki, dzs.kj)).a("has_red_sandstone", this.b(dzs.kh)).a("has_chiseled_red_sandstone", this.b(dzs.ki)).a("has_cut_red_sandstone", this.b(dzs.kj)).a(this.b);
        this.a(ol.c, (dwn)dzs.eM).a(Character.valueOf('#'), dzs.em).a(Character.valueOf('X'), dlx.mB).a(Character.valueOf('I'), dzs.b).b("#X#").b("III").b("has_redstone_torch", this.b(dzs.em)).a(this.b);
        this.a(ol.a, (dwn)dzs.bc, dzs.L);
        this.a(ol.a, (dwn)dzs.ky, dqo.a(dzs.bc, dzs.bd)).a("has_sandstone", this.b(dzs.bc)).a("has_chiseled_sandstone", this.b(dzs.bd)).a(this.b);
        this.b((dwn)dzs.gs, dqo.a(dzs.bc, dzs.bd, dzs.be)).a("has_sandstone", this.b(dzs.bc)).a("has_chiseled_sandstone", this.b(dzs.bd)).a("has_cut_sandstone", this.b(dzs.be)).a(this.b);
        this.a(ol.a, (dwn)dzs.ja).a(Character.valueOf('S'), dlx.wL).a(Character.valueOf('C'), dlx.wM).b("SCS").b("CCC").b("SCS").b("has_prismarine_crystals", this.b(dlx.wM)).a(this.b);
        this.a(ol.e, (dwn)dlx.tZ).a(Character.valueOf('#'), dlx.qg).b(" #").b("# ").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.f, (dwn)dlx.xH).a(Character.valueOf('W'), bdy.bv).a(Character.valueOf('o'), dlx.qg).b("WoW").b("WWW").b(" W ").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.i, (dwn)dlx.sC, ol.c, dlx.mI);
        this.f(ol.a, dzs.kj, dzs.kh);
        this.f(ol.a, dzs.be, dzs.bc);
        this.a(ol.a, (dwn)dzs.er, (dwn)dlx.so);
        this.a(ol.b, (dwn)dzs.ep, 6).a(Character.valueOf('#'), dzs.er).b("###").b("has_snowball", this.b(dlx.so)).a(this.b);
        this.a(ol.b, (dwn)dzs.pf).a(Character.valueOf('L'), bdy.E).a(Character.valueOf('S'), dlx.qW).a(Character.valueOf('#'), bdy.T).b(" S ").b("S#S").b("LLL").b("has_soul_sand", this.a(bdy.T)).a(this.b);
        this.a(ol.h, (dwn)dlx.ux).a(Character.valueOf('#'), dlx.um).a(Character.valueOf('X'), dlx.ua).b("###").b("#X#").b("###").b("has_melon", this.b(dlx.ua)).a(this.b);
        this.a(ol.f, (dwn)dlx.xE, 2).a(Character.valueOf('#'), dlx.tc).a(Character.valueOf('X'), dlx.pX).b(" # ").b("#X#").b(" # ").b("has_glowstone_dust", this.b(dlx.tc)).a(this.b);
        this.a(ol.e, (dwn)dlx.tb).a(Character.valueOf('#'), dlx.qe).a(Character.valueOf('X'), dlx.qi).b(" # ").b(" X ").b(" X ").b("has_amethyst_shard", this.b(dlx.qe)).a(this.b);
        this.a(ol.i, (dwn)dlx.qW, 4).a(Character.valueOf('#'), bdy.b).b("#").b("#").c("sticks").b("has_planks", this.a(bdy.b)).a(this.b);
        this.a(ol.i, (dwn)dlx.qW, 1).a(Character.valueOf('#'), dzs.nW).b("#").b("#").c("sticks").b("has_bamboo", this.b(dzs.nW)).a(this.b, "stick_from_bamboo_item");
        this.a(ol.c, (dwn)dzs.by).a(Character.valueOf('P'), dzs.bI).a(Character.valueOf('S'), dlx.sC).b("S").b("P").b("has_slime_ball", this.b(dlx.sC)).a(this.b);
        this.a(ol.a, (dwn)dzs.fn, 4).a(Character.valueOf('#'), dzs.b).b("##").b("##").b("has_stone", this.b(dzs.b)).a(this.b);
        this.a(ol.e, (dwn)dlx.qA).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("XX").b("X#").b(" #").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.a(ol.a, (dwn)dzs.kD, dqo.a((dwn)dzs.fn)).a("has_stone_bricks", this.a(bdy.c)).a(this.b);
        this.b((dwn)dzs.fS, dqo.a((dwn)dzs.fn)).a("has_stone_bricks", this.a(bdy.c)).a(this.b);
        this.a(ol.e, (dwn)dlx.qB).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("XX").b(" #").b(" #").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.a(ol.e, (dwn)dlx.qz).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("XXX").b(" # ").b(" # ").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.a(ol.e, (dwn)dlx.qy).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("X").b("#").b("#").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.c(ol.a, dzs.kx, dzs.kK);
        this.a(ol.f, (dwn)dlx.qx).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("X").b("X").b("#").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.a(ol.f, (dwn)dlx.xJ).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bw).b("  X").b(" # ").b("#  ").b("has_cobblestone", this.a(bdy.bw)).a(this.b);
        this.a(ol.a, (dwn)dzs.bK).a(Character.valueOf('#'), dlx.qY).b("##").b("##").b("has_string", this.b(dlx.qY)).a(this.b, ox.r(dzs.bK, dlx.qY));
        this.a((dwn)dlx.tE, (dwn)dzs.ev, "sugar");
        this.b(ol.i, (dwn)dlx.tE, 3).b(dlx.zi).b("sugar").b("has_honey_bottle", this.b(dlx.zi)).a(this.b, ox.r(dlx.tE, dlx.zi));
        this.a(ol.c, (dwn)dzs.qd).a(Character.valueOf('H'), dlx.iw).a(Character.valueOf('R'), dlx.mB).b(" R ").b("RHR").b(" R ").b("has_redstone", this.b(dlx.mB)).b("has_hay_block", this.b(dzs.jb)).a(this.b);
        this.a(ol.c, (dwn)dzs.cu).a(Character.valueOf('#'), dqo.a(dzs.L, dzs.N)).a(Character.valueOf('X'), dlx.ra).b("X#X").b("#X#").b("X#X").b("has_gunpowder", this.b(dlx.ra)).a(this.b);
        this.b(ol.d, (dwn)dlx.pl).b(dzs.cu).b(dlx.pi).b("has_minecart", this.b(dlx.pi)).a(this.b);
        this.a(ol.b, (dwn)dzs.cL, 4).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), dqo.a(dlx.pY, dlx.pZ)).b("X").b("#").b("has_stone_pickaxe", this.b(dlx.qz)).a(this.b);
        this.a(ol.b, (dwn)dzs.eD, 4).a(Character.valueOf('X'), dqo.a(dlx.pY, dlx.pZ)).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('S'), bdy.T).b("X").b("#").b("S").b("has_soul_sand", this.a(bdy.T)).a(this.b);
        this.a(ol.b, (dwn)dzs.eF, 4).a(Character.valueOf('X'), dqo.a(dlx.pY, dlx.pZ)).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('C'), dlx.xS).b("C").b("X").b("#").b("has_copper_nugget", this.b(dlx.xS)).a(this.b);
        this.a(ol.b, (dwn)dzs.pb).a(Character.valueOf('#'), dlx.fk).a(Character.valueOf('X'), dlx.xR).b("XXX").b("X#X").b("XXX").b("has_iron_nugget", this.b(dlx.xR)).b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.b, (dwn)dzs.pc).a(Character.valueOf('#'), dlx.gb).a(Character.valueOf('X'), dlx.xR).b("XXX").b("X#X").b("XXX").b("has_soul_torch", this.b(dlx.gb)).a(this.b);
        this.a(ol.b, (dwn)dzs.pd.d()).a(Character.valueOf('#'), dlx.gc).a(Character.valueOf('X'), dlx.xS).b("XXX").b("X#X").b("XXX").b("has_copper_torch", this.b(dlx.gc)).a(this.b);
        this.b(ol.c, (dwn)dzs.hM).b(dzs.cS).b(dzs.gw).b("has_tripwire_hook", this.b(dzs.gw)).a(this.b);
        this.a(ol.c, (dwn)dzs.gw, 2).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('S'), dlx.qW).a(Character.valueOf('I'), dlx.qg).b("I").b("S").b("#").b("has_string", this.b(dlx.qY)).a(this.b);
        this.a(ol.f, (dwn)dlx.pP).a(Character.valueOf('X'), dlx.pQ).b("XXX").b("X X").b("has_turtle_scute", this.b(dlx.pQ)).a(this.b);
        this.a(ol.f, (dwn)dlx.pS).a(Character.valueOf('X'), dlx.pR).b("X  ").b("XXX").b("X X").b("has_armadillo_scute", this.b(dlx.pR)).a(this.b);
        this.b(ol.i, (dwn)dlx.rc, 9).b(dzs.jb).b("has_hay_block", this.b(dzs.jb)).a(this.b);
        this.b(ol.i, (dwn)dlx.tm).b(dlx.tC).b("white_dye").b("has_bone_meal", this.b(dlx.tC)).a(this.b);
        this.a((dwn)dlx.tm, (dwn)dzs.co, "white_dye");
        this.a(ol.e, (dwn)dlx.qq).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("XX").b("X#").b(" #").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.e, (dwn)dlx.qr).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("XX").b(" #").b(" #").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.e, (dwn)dlx.qp).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("XXX").b(" # ").b(" # ").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.e, (dwn)dlx.qo).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("X").b("#").b("#").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.f, (dwn)dlx.qn).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("X").b("X").b("#").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.a(ol.f, (dwn)dlx.xI).a(Character.valueOf('#'), dlx.qW).a(Character.valueOf('X'), bdy.bv).b("  X").b(" # ").b("#  ").b("has_stick", this.b(dlx.qW)).a(this.b);
        this.b(ol.i, (dwn)dlx.wk).b(dlx.sB).b(dlx.tj).b(dlx.qZ).b("has_book", this.b(dlx.sB)).a(this.b);
        this.a((dwn)dlx.tq, (dwn)dzs.cb, "yellow_dye");
        this.a(dlx.tq, (dwn)dzs.jv, "yellow_dye", 2);
        this.a((dwn)dlx.tq, (dwn)dzs.tZ, "yellow_dye");
        this.a(ol.g, (dwn)dlx.ub, ol.a, dlx.sz);
        this.a(ol.i, (dwn)dzs.nU).a(Character.valueOf('#'), dlx.ys).a(Character.valueOf('X'), dlx.yy).b("###").b("#X#").b("###").b("has_nautilus_core", this.b(dlx.yy)).b("has_nautilus_shell", this.b(dlx.ys)).a(this.b);
        this.d(ol.b, dzs.oE, dzs.kh);
        this.d(ol.b, dzs.oH, dzs.fn);
        this.d(ol.b, dzs.oM, dzs.bc);
        this.b(ol.i, (dwn)dlx.yK).b(dlx.sA).b(dzs.ct).b("has_bricks", this.b(dzs.ct)).a(this.b);
        this.b(ol.i, (dwn)dlx.yL).b(dlx.sA).b(dzs.fN).b("has_vines", this.b(dzs.fN)).a(this.b);
        this.b(ol.i, (dwn)dlx.yD).b(dlx.sA).b(dlx.wB).b("has_creeper_head", this.b(dlx.wB)).a(this.b);
        this.b(ol.i, (dwn)dlx.yE).b(dlx.sA).b(dlx.wy).b("has_wither_skeleton_skull", this.b(dlx.wy)).a(this.b);
        this.b(ol.i, (dwn)dlx.yC).b(dlx.sA).b(dzs.cl).b("has_oxeye_daisy", this.b(dzs.cl)).a(this.b);
        this.b(ol.i, (dwn)dlx.yF).b(dlx.sA).b(dlx.rL).b("has_enchanted_golden_apple", this.b(dlx.rL)).a(this.b);
        this.a(ol.b, (dwn)dzs.oP, 6).a(Character.valueOf('~'), dlx.qY).a(Character.valueOf('I'), dzs.nW).b("I~I").b("I I").b("I I").b("has_bamboo", this.b(dzs.nW)).a(this.b);
        this.a(ol.b, (dwn)dzs.oW).a(Character.valueOf('I'), dlx.qW).a(Character.valueOf('-'), dzs.kw).a(Character.valueOf('#'), bdy.b).b("I-I").b("# #").b("has_stone_slab", this.b(dzs.kw)).a(this.b);
        this.a(ol.b, (dwn)dzs.oT).a(Character.valueOf('#'), dzs.kK).a(Character.valueOf('X'), dzs.da).a(Character.valueOf('I'), dlx.qg).b("III").b("IXI").b("###").b("has_smooth_stone", this.b(dzs.kK)).a(this.b);
        this.a(ol.b, (dwn)dzs.oS).a(Character.valueOf('#'), bdy.E).a(Character.valueOf('X'), dzs.da).b(" # ").b("#X#").b(" # ").b("has_furnace", this.b(dzs.da)).a(this.b);
        this.a(ol.b, (dwn)dzs.oU).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('@'), dlx.sA).b("@@").b("##").b("##").b("has_paper", this.b(dlx.sA)).a(this.b);
        this.a(ol.b, (dwn)dzs.oY).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('@'), dlx.qg).b("@@").b("##").b("##").b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.b, (dwn)dzs.oV).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('@'), dlx.rG).b("@@").b("##").b("##").b("has_flint", this.b(dlx.rG)).a(this.b);
        this.a(ol.b, (dwn)dzs.oZ).a(Character.valueOf('I'), dlx.qg).a(Character.valueOf('#'), dzs.b).b(" I ").b("###").b("has_stone", this.b(dzs.b)).a(this.b);
        this.a(ol.b, (dwn)dzs.qq).a(Character.valueOf('S'), dlx.go).a(Character.valueOf('#'), dlx.qg).b("SSS").b("S#S").b("SSS").b("has_iron_ingot", this.b(dlx.qg)).b("has_lodestone", this.b(dlx.zk)).a(this.b);
        this.b(ol.i, dlx.ql, ol.a, dlx.aQ, "netherite_ingot_from_netherite_block", "netherite_ingot");
        this.b(ol.i, (dwn)dlx.ql).a(dlx.qm, 4).a(dlx.qk, 4).b("netherite_ingot").b("has_netherite_scrap", this.b(dlx.qm)).a(this.b);
        this.a(ol.b, (dwn)dzs.ql).a(Character.valueOf('O'), dzs.qk).a(Character.valueOf('G'), dzs.eH).b("OOO").b("GGG").b("OOO").b("has_obsidian", this.b(dzs.qk)).a(this.b);
        this.a(ol.b, (dwn)dzs.fE).a(Character.valueOf('I'), dlx.qg).a(Character.valueOf('N'), dlx.xR).b("N").b("I").b("N").b("has_iron_nugget", this.b(dlx.xR)).b("has_iron_ingot", this.b(dlx.qg)).a(this.b);
        this.a(ol.b, (dwn)dzs.fF.d()).a(Character.valueOf('I'), dlx.qi).a(Character.valueOf('N'), dlx.xS).b("N").b("I").b("N").b("has_copper_nugget", this.b(dlx.xS)).b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.a, (dwn)dzs.rO, 2).a(Character.valueOf('G'), dzs.aX).a(Character.valueOf('S'), dlx.qe).b(" S ").b("SGS").b(" S ").b("has_amethyst_shard", this.b(dlx.qe)).a(this.b);
        this.a(ol.a, (dwn)dzs.rt, (dwn)dlx.qe);
        this.a(ol.e, (dwn)dlx.sH).a(Character.valueOf('C'), dlx.sG).a(Character.valueOf('S'), dlx.zZ).b("SSS").b("SCS").b("SSS").b("has_echo_shard", this.b(dlx.zZ)).a(this.b);
        this.a(ol.c, (dwn)dlx.nb).a(Character.valueOf('#'), dlx.qe).a(Character.valueOf('X'), dlx.na).b(" # ").b("#X#").b("has_amethyst_shard", this.b(dlx.qe)).a(this.b);
        this.b(ol.i, (dwn)dlx.ym, dlx.yq);
        ou.a(dpz::new).a(this.b, "armor_dye");
        ou.a(dqa::new).a(this.b, "banner_duplicate");
        ou.a(dqc::new).a(this.b, "book_cloning");
        ou.a(dql::new).a(this.b, "firework_rocket");
        ou.a(dqn::new).a(this.b, "firework_star");
        ou.a(dqm::new).a(this.b, "firework_star_fade");
        ou.a(dqp::new).a(this.b, "map_cloning");
        ou.a(dqq::new).a(this.b, "map_extending");
        ou.a(dre::new).a(this.b, "repair_item");
        ou.a(drj::new).a(this.b, "shield_decoration");
        ou.a(drt::new).a(this.b, "tipped_arrow");
        oq.c(dqo.a((dwn)dlx.ws), ol.g, dlx.wt, 0.35f, 200).b("has_potato", this.b(dlx.ws)).a(this.b);
        oq.c(dqo.a((dwn)dlx.sy), ol.i, dlx.sx, 0.3f, 200).b("has_clay_ball", this.b(dlx.sy)).a(this.b);
        oq.c(this.b(bdy.D), ol.i, dlx.pZ, 0.15f, 200).b("has_log", this.a(bdy.D)).a(this.b);
        oq.c(dqo.a((dwn)dlx.xv), ol.i, dlx.xw, 0.1f, 200).b("has_chorus_fruit", this.b(dlx.xv)).a(this.b);
        oq.c(dqo.a((dwn)dlx.ue), ol.g, dlx.uf, 0.35f, 200).b("has_beef", this.b(dlx.ue)).a(this.b);
        oq.c(dqo.a((dwn)dlx.ug), ol.g, dlx.uh, 0.35f, 200).b("has_chicken", this.b(dlx.ug)).a(this.b);
        oq.c(dqo.a((dwn)dlx.td), ol.g, dlx.th, 0.35f, 200).b("has_cod", this.b(dlx.td)).a(this.b);
        oq.c(dqo.a((dwn)dzs.mY), ol.g, dlx.ub, 0.1f, 200).b("has_kelp", this.b(dzs.mY)).a(this.b, ox.f(dlx.ub));
        oq.c(dqo.a((dwn)dlx.te), ol.g, dlx.ti, 0.35f, 200).b("has_salmon", this.b(dlx.te)).a(this.b);
        oq.c(dqo.a((dwn)dlx.xc), ol.g, dlx.xd, 0.35f, 200).b("has_mutton", this.b(dlx.xc)).a(this.b);
        oq.c(dqo.a((dwn)dlx.rH), ol.g, dlx.rI, 0.35f, 200).b("has_porkchop", this.b(dlx.rH)).a(this.b);
        oq.c(dqo.a((dwn)dlx.wN), ol.g, dlx.wO, 0.35f, 200).b("has_rabbit", this.b(dlx.wN)).a(this.b);
        this.a((List<dwn>)c, ol.i, dlx.pY, 0.1f, 200, "coal");
        this.a((List<dwn>)d, ol.i, dlx.qg, 0.7f, 200, "iron_ingot");
        this.a((List<dwn>)e, ol.i, dlx.qi, 0.7f, 200, "copper_ingot");
        this.a((List<dwn>)f, ol.i, dlx.qk, 1.0f, 200, "gold_ingot");
        this.a((List<dwn>)g, ol.i, dlx.qa, 1.0f, 200, "diamond");
        this.a((List<dwn>)h, ol.i, dlx.qc, 0.2f, 200, "lapis_lazuli");
        this.a((List<dwn>)i, ol.c, dlx.mB, 0.7f, 200, "redstone");
        this.a((List<dwn>)j, ol.i, dlx.qb, 1.0f, 200, "emerald");
        this.a(ol.i, (dwn)dlx.qf, ol.a, dlx.aG);
        this.a(ol.i, (dwn)dlx.qh, ol.a, dlx.aH);
        this.a(ol.i, (dwn)dlx.qj, ol.a, dlx.aI);
        oq.c(this.b(bdy.G), ol.a, dzs.aX.h(), 0.1f, 200).b("has_smelts_to_glass", this.a(bdy.G)).a(this.b);
        oq.c(dqo.a((dwn)dzs.nS), ol.i, dlx.tr, 0.1f, 200).b("has_sea_pickle", this.b(dzs.nS)).a(this.b, ox.f(dlx.tr));
        oq.c(dqo.a((dwn)dzs.es.h()), ol.i, dlx.tz, 1.0f, 200).b("has_cactus", this.b(dzs.es)).a(this.b);
        oq.c(dqo.a(dlx.qE, dlx.qD, dlx.qF, dlx.qG, dlx.qC, dlx.xM, dlx.ry, dlx.rz, dlx.rA, dlx.rB, dlx.wV, dlx.yu), ol.i, dlx.um, 0.1f, 200).b("has_golden_pickaxe", this.b(dlx.qE)).b("has_golden_shovel", this.b(dlx.qD)).b("has_golden_axe", this.b(dlx.qF)).b("has_golden_hoe", this.b(dlx.qG)).b("has_golden_sword", this.b(dlx.qC)).b("has_golden_spear", this.b(dlx.xM)).b("has_golden_helmet", this.b(dlx.ry)).b("has_golden_chestplate", this.b(dlx.rz)).b("has_golden_leggings", this.b(dlx.rA)).b("has_golden_boots", this.b(dlx.rB)).b("has_golden_horse_armor", this.b(dlx.wV)).b("has_golden_nautilus_armor", this.b(dlx.yu)).a(this.b, ox.f(dlx.um));
        oq.c(dqo.a(dlx.qu, dlx.qt, dlx.qv, dlx.qw, dlx.qs, dlx.xK, dlx.ri, dlx.rj, dlx.rk, dlx.rl, dlx.wT, dlx.yx), ol.i, dlx.xS, 0.1f, 200).b("has_copper_pickaxe", this.b(dlx.qu)).b("has_copper_shovel", this.b(dlx.qt)).b("has_copper_axe", this.b(dlx.qv)).b("has_copper_hoe", this.b(dlx.qw)).b("has_copper_sword", this.b(dlx.qs)).b("has_copper_spear", this.b(dlx.xK)).b("has_copper_helmet", this.b(dlx.ri)).b("has_copper_chestplate", this.b(dlx.rj)).b("has_copper_leggings", this.b(dlx.rk)).b("has_copper_boots", this.b(dlx.rl)).b("has_copper_horse_armor", this.b(dlx.wT)).b("has_copper_nautilus_armor", this.b(dlx.yx)).a(this.b, ox.f(dlx.xS));
        oq.c(dqo.a(dlx.qJ, dlx.qI, dlx.qK, dlx.qL, dlx.qH, dlx.xL, dlx.rq, dlx.rr, dlx.rs, dlx.rt, dlx.wU, dlx.rm, dlx.rn, dlx.ro, dlx.rp, dlx.yt), ol.i, dlx.xR, 0.1f, 200).b("has_iron_pickaxe", this.b(dlx.qJ)).b("has_iron_shovel", this.b(dlx.qI)).b("has_iron_axe", this.b(dlx.qK)).b("has_iron_hoe", this.b(dlx.qL)).b("has_iron_sword", this.b(dlx.qH)).b("has_iron_spear", this.b(dlx.xL)).b("has_iron_helmet", this.b(dlx.rq)).b("has_iron_chestplate", this.b(dlx.rr)).b("has_iron_leggings", this.b(dlx.rs)).b("has_iron_boots", this.b(dlx.rt)).b("has_iron_horse_armor", this.b(dlx.wU)).b("has_chainmail_helmet", this.b(dlx.rm)).b("has_chainmail_chestplate", this.b(dlx.rn)).b("has_chainmail_leggings", this.b(dlx.ro)).b("has_chainmail_boots", this.b(dlx.rp)).b("has_iron_nautilus_armor", this.b(dlx.yt)).a(this.b, ox.f(dlx.xR));
        oq.c(dqo.a((dwn)dzs.eu), ol.a, dzs.js.h(), 0.35f, 200).b("has_clay_block", this.b(dzs.eu)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ey), ol.i, dlx.wJ, 0.1f, 200).b("has_netherrack", this.b(dzs.ey)).a(this.b);
        oq.c(dqo.a((dwn)dlx.gI), ol.i, dlx.wK, 0.1f, 200).b("has_resin_clump", this.b(dzs.fP)).a(this.b);
        oq.c(dqo.a((dwn)dzs.hS), ol.i, dlx.qd, 0.2f, 200).b("has_nether_quartz_ore", this.b(dzs.hS)).a(this.b);
        oq.c(dqo.a((dwn)dzs.aW), ol.a, dzs.aV.h(), 0.15f, 200).b("has_wet_sponge", this.b(dzs.aW)).a(this.b);
        oq.c(dqo.a((dwn)dzs.m), ol.a, dzs.b.h(), 0.1f, 200).b("has_cobblestone", this.b(dzs.m)).a(this.b);
        oq.c(dqo.a((dwn)dzs.b), ol.a, dzs.kK.h(), 0.1f, 200).b("has_stone", this.b(dzs.b)).a(this.b);
        oq.c(dqo.a((dwn)dzs.bc), ol.a, dzs.kL.h(), 0.1f, 200).b("has_sandstone", this.b(dzs.bc)).a(this.b);
        oq.c(dqo.a((dwn)dzs.kh), ol.a, dzs.kN.h(), 0.1f, 200).b("has_red_sandstone", this.b(dzs.kh)).a(this.b);
        oq.c(dqo.a((dwn)dzs.hU), ol.a, dzs.kM.h(), 0.1f, 200).b("has_quartz_block", this.b(dzs.hU)).a(this.b);
        oq.c(dqo.a((dwn)dzs.fn), ol.a, dzs.fp.h(), 0.1f, 200).b("has_stone_bricks", this.b(dzs.fn)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ip), ol.b, dzs.mr.h(), 0.1f, 200).b("has_black_terracotta", this.b(dzs.ip)).a(this.b);
        oq.c(dqo.a((dwn)dzs.il), ol.b, dzs.mn.h(), 0.1f, 200).b("has_blue_terracotta", this.b(dzs.il)).a(this.b);
        oq.c(dqo.a((dwn)dzs.im), ol.b, dzs.mo.h(), 0.1f, 200).b("has_brown_terracotta", this.b(dzs.im)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ij), ol.b, dzs.ml.h(), 0.1f, 200).b("has_cyan_terracotta", this.b(dzs.ij)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ih), ol.b, dzs.mj.h(), 0.1f, 200).b("has_gray_terracotta", this.b(dzs.ih)).a(this.b);
        oq.c(dqo.a((dwn)dzs.in), ol.b, dzs.mp.h(), 0.1f, 200).b("has_green_terracotta", this.b(dzs.in)).a(this.b);
        oq.c(dqo.a((dwn)dzs.id), ol.b, dzs.mf.h(), 0.1f, 200).b("has_light_blue_terracotta", this.b(dzs.id)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ii), ol.b, dzs.mk.h(), 0.1f, 200).b("has_light_gray_terracotta", this.b(dzs.ii)).a(this.b);
        oq.c(dqo.a((dwn)dzs.if), ol.b, dzs.mh.h(), 0.1f, 200).b("has_lime_terracotta", this.b(dzs.if)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ic), ol.b, dzs.me.h(), 0.1f, 200).b("has_magenta_terracotta", this.b(dzs.ic)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ib), ol.b, dzs.md.h(), 0.1f, 200).b("has_orange_terracotta", this.b(dzs.ib)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ig), ol.b, dzs.mi.h(), 0.1f, 200).b("has_pink_terracotta", this.b(dzs.ig)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ik), ol.b, dzs.mm.h(), 0.1f, 200).b("has_purple_terracotta", this.b(dzs.ik)).a(this.b);
        oq.c(dqo.a((dwn)dzs.io), ol.b, dzs.mq.h(), 0.1f, 200).b("has_red_terracotta", this.b(dzs.io)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ia), ol.b, dzs.mc.h(), 0.1f, 200).b("has_white_terracotta", this.b(dzs.ia)).a(this.b);
        oq.c(dqo.a((dwn)dzs.ie), ol.b, dzs.mg.h(), 0.1f, 200).b("has_yellow_terracotta", this.b(dzs.ie)).a(this.b);
        oq.c(dqo.a((dwn)dzs.qj), ol.i, dlx.qm, 2.0f, 200).b("has_ancient_debris", this.b(dzs.qj)).a(this.b);
        oq.c(dqo.a((dwn)dzs.eB), ol.a, dzs.uD, 0.1f, 200).b("has_basalt", this.b(dzs.eB)).a(this.b);
        oq.c(dqo.a((dwn)dzs.uj), ol.a, dzs.ui, 0.1f, 200).b("has_cobbled_deepslate", this.b(dzs.uj)).a(this.b);
        oq.c(this.b(bdy.M), ol.i, dzs.ua, 0.1f, 200).b("has_leaves", this.a(bdy.M)).a(this.b);
        this.b((List<dwn>)c, ol.i, dlx.pY, 0.1f, 100, "coal");
        this.b((List<dwn>)d, ol.i, dlx.qg, 0.7f, 100, "iron_ingot");
        this.b((List<dwn>)e, ol.i, dlx.qi, 0.7f, 100, "copper_ingot");
        this.b((List<dwn>)f, ol.i, dlx.qk, 1.0f, 100, "gold_ingot");
        this.b((List<dwn>)g, ol.i, dlx.qa, 1.0f, 100, "diamond");
        this.b((List<dwn>)h, ol.i, dlx.qc, 0.2f, 100, "lapis_lazuli");
        this.b((List<dwn>)i, ol.c, dlx.mB, 0.7f, 100, "redstone");
        this.b((List<dwn>)j, ol.i, dlx.qb, 1.0f, 100, "emerald");
        oq.b(dqo.a((dwn)dzs.hS), ol.i, dlx.qd, 0.2f, 100).b("has_nether_quartz_ore", this.b(dzs.hS)).a(this.b, ox.g(dlx.qd));
        oq.b(dqo.a(dlx.qE, dlx.qD, dlx.qF, dlx.qG, dlx.qC, dlx.xM, dlx.ry, dlx.rz, dlx.rA, dlx.rB, dlx.wV, dlx.yu), ol.i, dlx.um, 0.1f, 100).b("has_golden_pickaxe", this.b(dlx.qE)).b("has_golden_shovel", this.b(dlx.qD)).b("has_golden_axe", this.b(dlx.qF)).b("has_golden_hoe", this.b(dlx.qG)).b("has_golden_sword", this.b(dlx.qC)).b("has_golden_spear", this.b(dlx.xM)).b("has_golden_helmet", this.b(dlx.ry)).b("has_golden_chestplate", this.b(dlx.rz)).b("has_golden_leggings", this.b(dlx.rA)).b("has_golden_boots", this.b(dlx.rB)).b("has_golden_horse_armor", this.b(dlx.wV)).b("has_golden_nautilus_armor", this.b(dlx.yu)).a(this.b, ox.g(dlx.um));
        oq.b(dqo.a(dlx.qu, dlx.qt, dlx.qv, dlx.qw, dlx.qs, dlx.xK, dlx.ri, dlx.rj, dlx.rk, dlx.rl, dlx.wT, dlx.yx), ol.i, dlx.xS, 0.1f, 100).b("has_copper_pickaxe", this.b(dlx.qu)).b("has_copper_shovel", this.b(dlx.qt)).b("has_copper_axe", this.b(dlx.qv)).b("has_copper_hoe", this.b(dlx.qw)).b("has_copper_sword", this.b(dlx.qs)).b("has_copper_spear", this.b(dlx.xK)).b("has_copper_helmet", this.b(dlx.ri)).b("has_copper_chestplate", this.b(dlx.rj)).b("has_copper_leggings", this.b(dlx.rk)).b("has_copper_boots", this.b(dlx.rl)).b("has_copper_horse_armor", this.b(dlx.wT)).b("has_copper_nautilus_armor", this.b(dlx.yx)).a(this.b, ox.g(dlx.xS));
        oq.b(dqo.a(dlx.qJ, dlx.qI, dlx.qK, dlx.qL, dlx.qH, dlx.xL, dlx.rq, dlx.rr, dlx.rs, dlx.rt, dlx.wU, dlx.yt, dlx.rm, dlx.rn, dlx.ro, dlx.rp), ol.i, dlx.xR, 0.1f, 100).b("has_iron_pickaxe", this.b(dlx.qJ)).b("has_iron_shovel", this.b(dlx.qI)).b("has_iron_axe", this.b(dlx.qK)).b("has_iron_hoe", this.b(dlx.qL)).b("has_iron_sword", this.b(dlx.qH)).b("has_iron_spear", this.b(dlx.xL)).b("has_iron_helmet", this.b(dlx.rq)).b("has_iron_chestplate", this.b(dlx.rr)).b("has_iron_leggings", this.b(dlx.rs)).b("has_iron_boots", this.b(dlx.rt)).b("has_iron_horse_armor", this.b(dlx.wU)).b("has_chainmail_helmet", this.b(dlx.rm)).b("has_chainmail_chestplate", this.b(dlx.rn)).b("has_chainmail_leggings", this.b(dlx.ro)).b("has_chainmail_boots", this.b(dlx.rp)).b("has_iron_nautilus_armor", this.b(dlx.yt)).a(this.b, ox.g(dlx.xR));
        oq.b(dqo.a((dwn)dzs.qj), ol.i, dlx.qm, 2.0f, 100).b("has_ancient_debris", this.b(dzs.qj)).a(this.b, ox.g(dlx.qm));
        this.a("smoking", drc.q, drr::new, 100);
        this.a("campfire_cooking", drc.r, dqd::new, 600);
        this.a(ol.a, (dwn)dzs.kw, (dwn)dzs.b, 2);
        this.i(ol.a, dzs.oh, dzs.b);
        this.i(ol.a, dzs.fn, dzs.b);
        this.a(ol.a, (dwn)dzs.kD, (dwn)dzs.b, 2);
        this.i(ol.a, dzs.fS, dzs.b);
        or.a(dqo.a((dwn)dzs.b), ol.a, dzs.fq).b("has_stone", this.b(dzs.b)).a(this.b, "chiseled_stone_bricks_stone_from_stonecutting");
        or.a(dqo.a((dwn)dzs.b), ol.b, dzs.oH).b("has_stone", this.b(dzs.b)).a(this.b, "stone_brick_walls_from_stone_stonecutting");
        this.i(ol.a, dzs.be, dzs.bc);
        this.a(ol.a, (dwn)dzs.ky, (dwn)dzs.bc, 2);
        this.a(ol.a, (dwn)dzs.kz, (dwn)dzs.bc, 2);
        this.a(ol.a, (dwn)dzs.kz, (dwn)dzs.be, 2);
        this.i(ol.a, dzs.gs, dzs.bc);
        this.i(ol.b, dzs.oM, dzs.bc);
        this.i(ol.a, dzs.bd, dzs.bc);
        this.i(ol.a, dzs.kj, dzs.kh);
        this.a(ol.a, (dwn)dzs.kH, (dwn)dzs.kh, 2);
        this.a(ol.a, (dwn)dzs.kI, (dwn)dzs.kh, 2);
        this.a(ol.a, (dwn)dzs.kI, (dwn)dzs.kj, 2);
        this.i(ol.a, dzs.kk, dzs.kh);
        this.i(ol.b, dzs.oE, dzs.kh);
        this.i(ol.a, dzs.ki, dzs.kh);
        or.a(dqo.a((dwn)dzs.hU), ol.a, dzs.kG, 2).b("has_quartz_block", this.b(dzs.hU)).a(this.b, "quartz_slab_from_stonecutting");
        this.i(ol.a, dzs.hX, dzs.hU);
        this.i(ol.a, dzs.hW, dzs.hU);
        this.i(ol.a, dzs.hV, dzs.hU);
        this.i(ol.a, dzs.qK, dzs.hU);
        this.i(ol.a, dzs.do, dzs.m);
        this.a(ol.a, (dwn)dzs.kB, (dwn)dzs.m, 2);
        this.i(ol.b, dzs.gE, dzs.m);
        this.a(ol.a, (dwn)dzs.kD, (dwn)dzs.fn, 2);
        this.i(ol.a, dzs.fS, dzs.fn);
        or.a(dqo.a((dwn)dzs.fn), ol.b, dzs.oH).b("has_stone_bricks", this.b(dzs.fn)).a(this.b, "stone_brick_wall_from_stone_bricks_stonecutting");
        this.i(ol.a, dzs.fq, dzs.fn);
        this.a(ol.a, (dwn)dzs.kC, (dwn)dzs.ct, 2);
        this.i(ol.a, dzs.fR, dzs.ct);
        this.i(ol.b, dzs.oC, dzs.ct);
        this.a(ol.a, (dwn)dzs.kE, (dwn)dzs.fs, 2);
        this.i(ol.a, dzs.fT, dzs.fs);
        this.i(ol.b, dzs.oI, dzs.fs);
        this.a(ol.a, (dwn)dzs.kF, (dwn)dzs.gc, 2);
        this.i(ol.a, dzs.ge, dzs.gc);
        this.i(ol.b, dzs.oJ, dzs.gc);
        this.i(ol.a, dzs.qI, dzs.gc);
        this.a(ol.a, (dwn)dzs.fZ, (dwn)dzs.fX, 2);
        this.i(ol.a, dzs.fY, dzs.fX);
        this.i(ol.b, dzs.ga, dzs.fX);
        this.i(ol.a, dzs.gb, dzs.fX);
        this.a(ol.a, (dwn)dzs.oz, (dwn)dzs.lH, 2);
        this.i(ol.a, dzs.om, dzs.lH);
        this.i(ol.b, dzs.oL, dzs.lH);
        this.a(ol.a, (dwn)dzs.kJ, (dwn)dzs.ls, 2);
        this.i(ol.a, dzs.lu, dzs.ls);
        this.i(ol.a, dzs.lt, dzs.ls);
        this.a(ol.a, (dwn)dzs.iX, (dwn)dzs.iR, 2);
        this.i(ol.a, dzs.iU, dzs.iR);
        this.i(ol.b, dzs.oD, dzs.iR);
        or.a(dqo.a((dwn)dzs.iS), ol.a, dzs.iY, 2).b("has_prismarine_brick", this.b(dzs.iS)).a(this.b, "prismarine_brick_slab_from_prismarine_stonecutting");
        or.a(dqo.a((dwn)dzs.iS), ol.a, dzs.iV).b("has_prismarine_brick", this.b(dzs.iS)).a(this.b, "prismarine_brick_stairs_from_prismarine_stonecutting");
        this.a(ol.a, (dwn)dzs.iZ, (dwn)dzs.iT, 2);
        this.i(ol.a, dzs.iW, dzs.iT);
        this.a(ol.a, (dwn)dzs.oy, (dwn)dzs.g, 2);
        this.i(ol.a, dzs.ol, dzs.g);
        this.i(ol.b, dzs.oK, dzs.g);
        this.i(ol.a, dzs.h, dzs.g);
        this.a(ol.a, (dwn)dzs.oA, (dwn)dzs.g, 2);
        this.i(ol.a, dzs.on, dzs.g);
        this.a(ol.a, (dwn)dzs.oA, (dwn)dzs.h, 2);
        this.i(ol.a, dzs.on, dzs.h);
        this.i(ol.a, dzs.eC, dzs.eB);
        this.a(ol.a, (dwn)dzs.ox, (dwn)dzs.c, 2);
        this.i(ol.a, dzs.ok, dzs.c);
        this.i(ol.b, dzs.oG, dzs.c);
        this.i(ol.a, dzs.d, dzs.c);
        this.a(ol.a, (dwn)dzs.op, (dwn)dzs.c, 2);
        this.i(ol.a, dzs.ob, dzs.c);
        this.a(ol.a, (dwn)dzs.op, (dwn)dzs.d, 2);
        this.i(ol.a, dzs.ob, dzs.d);
        this.a(ol.a, (dwn)dzs.oB, (dwn)dzs.e, 2);
        this.i(ol.a, dzs.oo, dzs.e);
        this.i(ol.b, dzs.oO, dzs.e);
        this.i(ol.a, dzs.f, dzs.e);
        this.a(ol.a, (dwn)dzs.os, (dwn)dzs.e, 2);
        this.i(ol.a, dzs.oe, dzs.e);
        this.a(ol.a, (dwn)dzs.os, (dwn)dzs.f, 2);
        this.i(ol.a, dzs.oe, dzs.f);
        or.a(dqo.a((dwn)dzs.fo), ol.a, dzs.or, 2).b("has_mossy_stone_bricks", this.b(dzs.fo)).a(this.b, "mossy_stone_brick_slab_from_mossy_stone_brick_stonecutting");
        or.a(dqo.a((dwn)dzs.fo), ol.a, dzs.od).b("has_mossy_stone_bricks", this.b(dzs.fo)).a(this.b, "mossy_stone_brick_stairs_from_mossy_stone_brick_stonecutting");
        or.a(dqo.a((dwn)dzs.fo), ol.b, dzs.oF).b("has_mossy_stone_bricks", this.b(dzs.fo)).a(this.b, "mossy_stone_brick_wall_from_mossy_stone_brick_stonecutting");
        this.a(ol.a, (dwn)dzs.ot, (dwn)dzs.cJ, 2);
        this.i(ol.a, dzs.of, dzs.cJ);
        this.i(ol.b, dzs.gF, dzs.cJ);
        this.a(ol.a, (dwn)dzs.ov, (dwn)dzs.kL, 2);
        this.i(ol.a, dzs.oi, dzs.kL);
        this.a(ol.a, (dwn)dzs.oq, (dwn)dzs.kN, 2);
        this.i(ol.a, dzs.oc, dzs.kN);
        this.a(ol.a, (dwn)dzs.ow, (dwn)dzs.kM, 2);
        this.i(ol.a, dzs.oj, dzs.kM);
        or.a(dqo.a((dwn)dzs.lv), ol.a, dzs.ou, 2).b("has_end_stone_brick", this.b(dzs.lv)).a(this.b, "end_stone_brick_slab_from_end_stone_brick_stonecutting");
        or.a(dqo.a((dwn)dzs.lv), ol.a, dzs.og).b("has_end_stone_brick", this.b(dzs.lv)).a(this.b, "end_stone_brick_stairs_from_end_stone_brick_stonecutting");
        or.a(dqo.a((dwn)dzs.lv), ol.b, dzs.oN).b("has_end_stone_brick", this.b(dzs.lv)).a(this.b, "end_stone_brick_wall_from_end_stone_brick_stonecutting");
        this.i(ol.a, dzs.lv, dzs.go);
        this.a(ol.a, (dwn)dzs.ou, (dwn)dzs.go, 2);
        this.i(ol.a, dzs.og, dzs.go);
        this.i(ol.b, dzs.oN, dzs.go);
        this.a(ol.a, (dwn)dzs.kx, (dwn)dzs.kK, 2);
        this.a(ol.a, (dwn)dzs.qu, (dwn)dzs.qr, 2);
        this.i(ol.a, dzs.qs, dzs.qr);
        this.i(ol.b, dzs.qt, dzs.qr);
        this.i(ol.a, dzs.qv, dzs.qr);
        this.i(ol.b, dzs.qH, dzs.qr);
        this.a(ol.a, (dwn)dzs.qE, (dwn)dzs.qr, 2);
        this.i(ol.a, dzs.qD, dzs.qr);
        this.i(ol.a, dzs.qy, dzs.qr);
        this.i(ol.a, dzs.qw, dzs.qr);
        this.a(ol.a, (dwn)dzs.qz, (dwn)dzs.qr, 2);
        this.i(ol.a, dzs.qA, dzs.qr);
        this.i(ol.b, dzs.qB, dzs.qr);
        this.a(ol.a, (dwn)dzs.qE, (dwn)dzs.qv, 2);
        this.i(ol.a, dzs.qD, dzs.qv);
        this.i(ol.a, dzs.qw, dzs.qv);
        this.i(ol.b, dzs.qH, dzs.qv);
        this.a(ol.a, (dwn)dzs.qz, (dwn)dzs.qv, 2);
        this.i(ol.a, dzs.qA, dzs.qv);
        this.i(ol.b, dzs.qB, dzs.qv);
        this.i(ol.a, dzs.qy, dzs.qv);
        this.a(ol.a, (dwn)dzs.qz, (dwn)dzs.qw, 2);
        this.i(ol.a, dzs.qA, dzs.qw);
        this.i(ol.b, dzs.qB, dzs.qw);
        this.a(ol.a, (dwn)dzs.sv, (dwn)dzs.sf, 2);
        this.i(ol.a, dzs.sr, dzs.sf);
        this.a(ol.a, (dwn)dzs.su, (dwn)dzs.se, 2);
        this.i(ol.a, dzs.sq, dzs.se);
        this.a(ol.a, (dwn)dzs.st, (dwn)dzs.sd, 2);
        this.i(ol.a, dzs.sp, dzs.sd);
        this.a(ol.a, (dwn)dzs.ss, (dwn)dzs.sc, 2);
        this.i(ol.a, dzs.so, dzs.sc);
        this.a(ol.a, (dwn)dzs.sL, (dwn)dzs.sD, 2);
        this.i(ol.a, dzs.sH, dzs.sD);
        this.a(ol.a, (dwn)dzs.sK, (dwn)dzs.sC, 2);
        this.i(ol.a, dzs.sG, dzs.sC);
        this.a(ol.a, (dwn)dzs.sJ, (dwn)dzs.sB, 2);
        this.i(ol.a, dzs.sF, dzs.sB);
        this.a(ol.a, (dwn)dzs.sI, (dwn)dzs.sA, 2);
        this.i(ol.a, dzs.sE, dzs.sA);
        this.a(ol.a, (dwn)dzs.sf, (dwn)dzs.rW, 4);
        this.a(ol.a, (dwn)dzs.sr, (dwn)dzs.rW, 4);
        this.a(ol.a, (dwn)dzs.sv, (dwn)dzs.rW, 8);
        this.a(ol.a, (dwn)dzs.se, (dwn)dzs.rX, 4);
        this.a(ol.a, (dwn)dzs.sq, (dwn)dzs.rX, 4);
        this.a(ol.a, (dwn)dzs.su, (dwn)dzs.rX, 8);
        this.a(ol.a, (dwn)dzs.sd, (dwn)dzs.rY, 4);
        this.a(ol.a, (dwn)dzs.sp, (dwn)dzs.rY, 4);
        this.a(ol.a, (dwn)dzs.st, (dwn)dzs.rY, 8);
        this.a(ol.a, (dwn)dzs.sc, (dwn)dzs.rZ, 4);
        this.a(ol.a, (dwn)dzs.so, (dwn)dzs.rZ, 4);
        this.a(ol.a, (dwn)dzs.ss, (dwn)dzs.rZ, 8);
        this.a(ol.a, (dwn)dzs.sD, (dwn)dzs.sw, 4);
        this.a(ol.a, (dwn)dzs.sH, (dwn)dzs.sw, 4);
        this.a(ol.a, (dwn)dzs.sL, (dwn)dzs.sw, 8);
        this.a(ol.a, (dwn)dzs.sC, (dwn)dzs.sy, 4);
        this.a(ol.a, (dwn)dzs.sG, (dwn)dzs.sy, 4);
        this.a(ol.a, (dwn)dzs.sK, (dwn)dzs.sy, 8);
        this.a(ol.a, (dwn)dzs.sB, (dwn)dzs.sx, 4);
        this.a(ol.a, (dwn)dzs.sF, (dwn)dzs.sx, 4);
        this.a(ol.a, (dwn)dzs.sJ, (dwn)dzs.sx, 8);
        this.a(ol.a, (dwn)dzs.sA, (dwn)dzs.sz, 4);
        this.a(ol.a, (dwn)dzs.sE, (dwn)dzs.sz, 4);
        this.a(ol.a, (dwn)dzs.sI, (dwn)dzs.sz, 8);
        this.a(ol.a, (dwn)dzs.ul, (dwn)dzs.uj, 2);
        this.i(ol.a, dzs.uk, dzs.uj);
        this.i(ol.b, dzs.um, dzs.uj);
        this.i(ol.a, dzs.uz, dzs.uj);
        this.i(ol.a, dzs.un, dzs.uj);
        this.a(ol.a, (dwn)dzs.up, (dwn)dzs.uj, 2);
        this.i(ol.a, dzs.uo, dzs.uj);
        this.i(ol.b, dzs.uq, dzs.uj);
        this.i(ol.a, dzs.uv, dzs.uj);
        this.a(ol.a, (dwn)dzs.ux, (dwn)dzs.uj, 2);
        this.i(ol.a, dzs.uw, dzs.uj);
        this.i(ol.b, dzs.uy, dzs.uj);
        this.i(ol.a, dzs.ur, dzs.uj);
        this.a(ol.a, (dwn)dzs.ut, (dwn)dzs.uj, 2);
        this.i(ol.a, dzs.us, dzs.uj);
        this.i(ol.b, dzs.uu, dzs.uj);
        this.a(ol.a, (dwn)dzs.up, (dwn)dzs.un, 2);
        this.i(ol.a, dzs.uo, dzs.un);
        this.i(ol.b, dzs.uq, dzs.un);
        this.i(ol.a, dzs.uv, dzs.un);
        this.a(ol.a, (dwn)dzs.ux, (dwn)dzs.un, 2);
        this.i(ol.a, dzs.uw, dzs.un);
        this.i(ol.b, dzs.uy, dzs.un);
        this.i(ol.a, dzs.ur, dzs.un);
        this.a(ol.a, (dwn)dzs.ut, (dwn)dzs.un, 2);
        this.i(ol.a, dzs.us, dzs.un);
        this.i(ol.b, dzs.uu, dzs.un);
        this.a(ol.a, (dwn)dzs.ux, (dwn)dzs.uv, 2);
        this.i(ol.a, dzs.uw, dzs.uv);
        this.i(ol.b, dzs.uy, dzs.uv);
        this.i(ol.a, dzs.ur, dzs.uv);
        this.a(ol.a, (dwn)dzs.ut, (dwn)dzs.uv, 2);
        this.i(ol.a, dzs.us, dzs.uv);
        this.i(ol.b, dzs.uu, dzs.uv);
        this.a(ol.a, (dwn)dzs.ut, (dwn)dzs.ur, 2);
        this.i(ol.a, dzs.us, dzs.ur);
        this.i(ol.b, dzs.uu, dzs.ur);
        ox.b().forEach($$0 -> this.a($$0.a(), $$0.b(), $$0.c()));
        this.a(dlx.rv, ol.f, dlx.rD);
        this.a(dlx.rw, ol.f, dlx.rE);
        this.a(dlx.ru, ol.f, dlx.rC);
        this.a(dlx.rx, ol.f, dlx.rF);
        this.a(dlx.yv, ol.f, dlx.yw);
        this.a(dlx.wW, ol.f, dlx.wX);
        this.a(dlx.qM, ol.f, dlx.qR);
        this.a(dlx.xN, ol.f, dlx.xO);
        this.a(dlx.qP, ol.e, dlx.qU);
        this.a(dlx.qO, ol.e, dlx.qT);
        this.a(dlx.qQ, ol.e, dlx.qV);
        this.a(dlx.qN, ol.e, dlx.qS);
        this.q(dlx.Ab, dlx.fV);
        this.q(dlx.Ac, dlx.J);
        this.q(dlx.Ad, dlx.cQ);
        this.q(dlx.Ae, dlx.J);
        this.q(dlx.Af, dlx.fi);
        this.q(dlx.Ag, dlx.j);
        this.q(dlx.Ah, dlx.hf);
        this.q(dlx.Ai, dlx.J);
        this.q(dlx.Aj, dlx.jC);
        this.q(dlx.Ak, dlx.zm);
        this.q(dlx.Al, dlx.fV);
        this.q(dlx.Am, dlx.fo);
        this.q(dlx.Ap, dlx.j);
        this.q(dlx.An, dlx.iN);
        this.q(dlx.Ao, dlx.iN);
        this.q(dlx.Aq, dlx.iN);
        this.q(dlx.Ar, dlx.iN);
        this.q(dlx.As, dlx.wm);
        this.d((dwn)dlx.At, dqo.a(dlx.aN, dlx.bk));
        this.b(ol.a, (dwn)dzs.ai, dlx.ej);
        this.b(dzs.x, bdy.q, 2);
        this.h(ol.b, dzs.y, dzs.ku);
        this.b((dwn)dlx.pJ, (dwn)dzs.x);
        this.c((dwn)dlx.pK, dlx.pJ);
        this.f(dlx.rY, dzs.aq);
        this.f(dlx.rZ, dzs.aj);
        this.f(dlx.sa, dzs.ak);
        this.f(dlx.sb, dzs.al);
        this.f(dlx.sc, dzs.am);
        this.f(dlx.sd, dzs.an);
        this.f(dlx.se, dzs.ao);
        this.f(dlx.sf, dzs.ap);
        this.f(dlx.sg, dzs.ar);
        this.f(dlx.sh, dlx.co);
        this.f(dlx.si, dzs.pr);
        this.f(dlx.sj, dzs.pi);
        this.a(ol.a, (dwn)dzs.cw).a(Character.valueOf('#'), bdy.b).a(Character.valueOf('X'), bdy.j).b("###").b("XXX").b("###").b("has_book", this.b(dlx.sB)).a(this.b);
        this.a((dwn)dlx.tn, (dwn)dzs.cc, "orange_dye");
        this.a(dlx.tv, (dwn)dzs.ly, "cyan_dye", 2);
        this.a((dwn)dzs.s, bdy.z, 4);
        this.a((dwn)dzs.ay, (dwn)dzs.ac);
        this.a((dwn)dzs.aG, (dwn)dzs.an);
        this.b((dwn)dlx.pB, (dwn)dzs.s);
        this.c((dwn)dlx.pC, dlx.pB);
        this.a(dlx.ts, (dwn)dlx.dY, "pink_dye", 1);
        this.a(ol.e, (dwn)dlx.Aa).a(Character.valueOf('X'), dlx.qZ).a(Character.valueOf('#'), dlx.qi).a(Character.valueOf('I'), dlx.qW).b("X").b("#").b("I").b("has_copper_ingot", this.b(dlx.qi)).a(this.b);
        this.a(ol.b, (dwn)dlx.fh).a(Character.valueOf('#'), dlx.sx).b(" # ").b("# #").b(" # ").b("has_brick", this.a(bdy.bZ)).a(this.b, "decorated_pot_simple");
        ou.a(dqj::new).a(this.b, "decorated_pot");
        this.a(ol.c, (dwn)dzs.uP).a(Character.valueOf('#'), dlx.qg).a(Character.valueOf('C'), dlx.fu).a(Character.valueOf('R'), dlx.mB).a(Character.valueOf('D'), dlx.mN).b("###").b("#C#").b("RDR").b("has_dropper", this.b(dlx.mN)).a(this.b);
        this.a(ol.a, (dwn)dzs.rA, (dwn)dzs.rz, 2);
        this.i(ol.a, dzs.rB, dzs.rz);
        this.i(ol.b, dzs.rC, dzs.rz);
        this.i(ol.a, dzs.rH, dzs.rz);
        this.i(ol.a, dzs.rD, dzs.rz);
        this.a(ol.a, (dwn)dzs.rE, (dwn)dzs.rz, 2);
        this.i(ol.a, dzs.rF, dzs.rz);
        this.i(ol.b, dzs.rG, dzs.rz);
        this.i(ol.a, dzs.rI, dzs.rz);
        this.a(ol.a, (dwn)dzs.rJ, (dwn)dzs.rz, 2);
        this.i(ol.a, dzs.rK, dzs.rz);
        this.i(ol.b, dzs.rL, dzs.rz);
        this.i(ol.a, dzs.rM, dzs.rz);
        this.a(ol.a, (dwn)dzs.rE, (dwn)dzs.rD, 2);
        this.i(ol.a, dzs.rF, dzs.rD);
        this.i(ol.b, dzs.rG, dzs.rD);
        this.i(ol.a, dzs.rI, dzs.rD);
        this.a(ol.a, (dwn)dzs.rJ, (dwn)dzs.rD, 2);
        this.i(ol.a, dzs.rK, dzs.rD);
        this.i(ol.b, dzs.rL, dzs.rD);
        this.i(ol.a, dzs.rM, dzs.rD);
        this.a(ol.a, (dwn)dzs.rJ, (dwn)dzs.rI, 2);
        this.i(ol.a, dzs.rK, dzs.rI);
        this.i(ol.b, dzs.rL, dzs.rI);
        this.i(ol.a, dzs.rM, dzs.rI);
        this.a(ol.a, (dwn)dzs.sj, (dwn)dzs.rW, 4);
        this.a(ol.a, (dwn)dzs.si, (dwn)dzs.rX, 4);
        this.a(ol.a, (dwn)dzs.sh, (dwn)dzs.rY, 4);
        this.a(ol.a, (dwn)dzs.sg, (dwn)dzs.rZ, 4);
        this.a(ol.a, (dwn)dzs.sn, (dwn)dzs.sw, 4);
        this.a(ol.a, (dwn)dzs.sm, (dwn)dzs.sy, 4);
        this.a(ol.a, (dwn)dzs.sl, (dwn)dzs.sx, 4);
        this.a(ol.a, (dwn)dzs.sk, (dwn)dzs.sz, 4);
        this.a(ol.a, (dwn)dzs.sj, (dwn)dzs.sf, 1);
        this.a(ol.a, (dwn)dzs.si, (dwn)dzs.se, 1);
        this.a(ol.a, (dwn)dzs.sh, (dwn)dzs.sd, 1);
        this.a(ol.a, (dwn)dzs.sg, (dwn)dzs.sc, 1);
        this.a(ol.a, (dwn)dzs.sn, (dwn)dzs.sD, 1);
        this.a(ol.a, (dwn)dzs.sm, (dwn)dzs.sC, 1);
        this.a(ol.a, (dwn)dzs.sl, (dwn)dzs.sB, 1);
        this.a(ol.a, (dwn)dzs.sk, (dwn)dzs.sA, 1);
        this.a(dzs.tc, dzs.rW);
        this.a(dzs.td, dzs.rX);
        this.a(dzs.te, dzs.rY);
        this.a(dzs.tf, dzs.rZ);
        this.a(dzs.tg, dzs.sw);
        this.a(dzs.th, dzs.sy);
        this.a(dzs.ti, dzs.sx);
        this.a(dzs.tj, dzs.sz);
        this.b(dzs.tk, dzs.rW);
        this.b(dzs.tl, dzs.rX);
        this.b(dzs.tm, dzs.rY);
        this.b(dzs.tn, dzs.rZ);
        this.b(dzs.to, dzs.sw);
        this.b(dzs.tp, dzs.sy);
        this.b(dzs.tq, dzs.sx);
        this.b(dzs.tr, dzs.sz);
        this.c(dzs.sn, dzs.sL);
        this.c(dzs.sm, dzs.sK);
        this.c(dzs.sl, dzs.sJ);
        this.c(dzs.sk, dzs.sI);
        this.a(ol.a, (dwn)dzs.tc, (dwn)dzs.rW, 4);
        this.a(ol.a, (dwn)dzs.td, (dwn)dzs.rX, 4);
        this.a(ol.a, (dwn)dzs.te, (dwn)dzs.rY, 4);
        this.a(ol.a, (dwn)dzs.tf, (dwn)dzs.rZ, 4);
        this.a(ol.a, (dwn)dzs.tg, (dwn)dzs.sw, 4);
        this.a(ol.a, (dwn)dzs.th, (dwn)dzs.sy, 4);
        this.a(ol.a, (dwn)dzs.ti, (dwn)dzs.sx, 4);
        this.a(ol.a, (dwn)dzs.tj, (dwn)dzs.sz, 4);
        this.b(ol.i, (dwn)dlx.wj, 4).b(dlx.wm).b("has_breeze_rod", this.b(dlx.wm)).a(this.b);
        this.a(ol.f, (dwn)dlx.wn, 1).a(Character.valueOf('I'), dlx.wm).a(Character.valueOf('#'), dzs.uS).b(" # ").b(" I ").b("has_breeze_rod", this.b(dlx.wm)).b("has_heavy_core", this.b(dzs.uS)).a(this.b);
        this.a((dwn)dzs.sM, dqo.a((dwn)dlx.qi)).a(ox.c(dlx.qi), this.b(dlx.qi)).a(this.b);
        this.a(ol.c, (dwn)dzs.sU, (dwn)dlx.qi);
        this.a(ol.e, (dwn)dlx.sI).a(Character.valueOf('-'), dlx.qY).a(Character.valueOf('#'), dlx.sp).b("-").b("#").b("has_string", this.b(dlx.qY)).a(this.b);
        this.d();
    }

    public static Stream<b> b() {
        return Stream.of(Pair.of((Object)dlx.At, duu.r), Pair.of((Object)dlx.Ae, duu.c), Pair.of((Object)dlx.Ad, duu.b), Pair.of((Object)dlx.Ah, duu.f), Pair.of((Object)dlx.As, duu.q), Pair.of((Object)dlx.Ar, duu.p), Pair.of((Object)dlx.Aq, duu.o), Pair.of((Object)dlx.Al, duu.j), Pair.of((Object)dlx.Ac, duu.a), Pair.of((Object)dlx.Ao, duu.m), Pair.of((Object)dlx.Ap, duu.n), Pair.of((Object)dlx.Ak, duu.i), Pair.of((Object)dlx.Am, duu.k), Pair.of((Object)dlx.Aj, duu.h), Pair.of((Object)dlx.Ai, duu.g), Pair.of((Object)dlx.Ag, duu.e), Pair.of((Object)dlx.An, duu.l), Pair.of((Object)dlx.Af, duu.d)).map($$0 -> {
            dlp $$1 = (dlp)$$0.getFirst();
            amt $$2 = (amt)$$0.getSecond();
            amt<dqs<?>> $$3 = amt.a(mj.bK, amo.b(ox.d($$1) + "_smithing_trim"));
            return new b($$1, $$2, $$3);
        });
    }

    private void c() {
        dqo $$0 = this.b(bdy.ah);
        for (dkr $$1 : dkr.values()) {
            ov.a(ol.b, $$0, dqo.a((dwn)dks.a($$1)), ehd.a($$1).h()).b("shulker_box_dye").b("has_shulker_box", this.a(bdy.ah)).a(this.b);
        }
    }

    private void d() {
        dqo $$0 = this.b(bdy.cl);
        for (dkr $$1 : dkr.values()) {
            dks $$2 = dks.a($$1);
            ov.a(ol.e, $$0, dqo.a((dwn)$$2), dki.a($$1)).b("bundle_dye").b(ox.c($$2), this.b($$2)).a(this.b);
        }
    }

    public record b(dlp a, amt<dut> b, amt<dqs<?>> c) {
        @Override
        public final String toString() {
            return ObjectMethods.bootstrap("toString", new MethodHandle[]{b.class, "template;patternId;recipeId", "a", "b", "c"}, this);
        }

        @Override
        public final int hashCode() {
            return (int)ObjectMethods.bootstrap("hashCode", new MethodHandle[]{b.class, "template;patternId;recipeId", "a", "b", "c"}, this);
        }

        @Override
        public final boolean equals(Object $$0) {
            return (boolean)ObjectMethods.bootstrap("equals", new MethodHandle[]{b.class, "template;patternId;recipeId", "a", "b", "c"}, this, $$0);
        }
    }

    public static class a
    extends on.b {
        public a(ms $$0, CompletableFuture<jf.a> $$1) {
            super($$0, $$1);
        }

        @Override
        protected on a(jf.a $$0, om $$1) {
            return new ox($$0, $$1);
        }

        @Override
        public String a() {
            return "Vanilla Recipes";
        }
    }
}

