/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class qj {
    public static void a(qr<fgy> $$0) {
        je<fes> $$1 = $$0.a(mj.bp);
        jd.c<fes> $$2 = $$1.b(sc.s);
        je<fjo> $$3 = $$0.a(mj.bq);
        jd.c<fjo> $$4 = $$3.b(qz.H);
        jd.c<fjo> $$5 = $$3.b(qz.I);
        je<fgy> $$6 = $$0.a(mj.bt);
        jd.c<fgy> $$7 = $$6.b(qy.a);
        qy.a($$0, "ancient_city/structures", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.i(), (Object)7), (Object)Pair.of(fgw.b("ancient_city/structures/barracks", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/chamber_1", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/chamber_2", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/chamber_3", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/sauna_1", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/small_statue", $$4), (Object)4), (Object)Pair.of(fgw.b("ancient_city/structures/large_ruin_1", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/structures/tall_ruin_1", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/structures/tall_ruin_2", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/structures/tall_ruin_3", $$4), (Object)2), (Object)Pair.of(fgw.b("ancient_city/structures/tall_ruin_4", $$4), (Object)2), (Object[])new Pair[]{Pair.of(fgw.b((List<Function<fgy.a, ? extends fgw>>)ImmutableList.of(fgw.b("ancient_city/structures/camp_1", $$4), fgw.b("ancient_city/structures/camp_2", $$4), fgw.b("ancient_city/structures/camp_3", $$4))), (Object)1), Pair.of(fgw.b("ancient_city/structures/medium_ruin_1", $$4), (Object)1), Pair.of(fgw.b("ancient_city/structures/medium_ruin_2", $$4), (Object)1), Pair.of(fgw.b("ancient_city/structures/small_ruin_1", $$4), (Object)1), Pair.of(fgw.b("ancient_city/structures/small_ruin_2", $$4), (Object)1), Pair.of(fgw.b("ancient_city/structures/large_pillar_1", $$4), (Object)1), Pair.of(fgw.b("ancient_city/structures/medium_pillar_1", $$4), (Object)1), Pair.of(fgw.b((List<Function<fgy.a, ? extends fgw>>)ImmutableList.of(fgw.b("ancient_city/structures/ice_box_1"))), (Object)1)}), fgy.a.b));
        qy.a($$0, "ancient_city/sculk", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a($$2), (Object)6), (Object)Pair.of(fgw.i(), (Object)1)), fgy.a.b));
        qy.a($$0, "ancient_city/walls", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.b("ancient_city/walls/intact_corner_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_intersection_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_lshape_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_2", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_2", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_3", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_4", $$5), (Object)4), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_passage_1", $$5), (Object)3), (Object)Pair.of(fgw.b("ancient_city/walls/ruined_corner_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/ruined_corner_wall_2", $$5), (Object)1), (Object[])new Pair[]{Pair.of(fgw.b("ancient_city/walls/ruined_horizontal_wall_stairs_1", $$5), (Object)2), Pair.of(fgw.b("ancient_city/walls/ruined_horizontal_wall_stairs_2", $$5), (Object)2), Pair.of(fgw.b("ancient_city/walls/ruined_horizontal_wall_stairs_3", $$5), (Object)3), Pair.of(fgw.b("ancient_city/walls/ruined_horizontal_wall_stairs_4", $$5), (Object)3)}), fgy.a.b));
        qy.a($$0, "ancient_city/walls/no_corners", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_2", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_1", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_2", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_3", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_4", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_stairs_5", $$5), (Object)1), (Object)Pair.of(fgw.b("ancient_city/walls/intact_horizontal_wall_bridge", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "ancient_city/city_center/walls", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.b("ancient_city/city_center/walls/bottom_1", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/bottom_2", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/bottom_left_corner", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/bottom_right_corner_1", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/bottom_right_corner_2", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/left", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/right", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/top", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/top_right_corner", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city_center/walls/top_left_corner", $$4), (Object)1)), fgy.a.b));
        qy.a($$0, "ancient_city/city/entrance", new fgy($$7, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_connector", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_path_1", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_path_2", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_path_3", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_path_4", $$4), (Object)1), (Object)Pair.of(fgw.b("ancient_city/city/entrance/entrance_path_5", $$4), (Object)1)), fgy.a.b));
    }
}

