/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class ra {
    public static final amt<fgy> a = qy.a("village/savanna/town_centers");
    private static final amt<fgy> b = qy.a("village/savanna/terminators");
    private static final amt<fgy> c = qy.a("village/savanna/zombie/terminators");

    public static void a(qr<fgy> $$0) {
        je<fes> $$1 = $$0.a(mj.bp);
        jd.c<fes> $$2 = $$1.b(sk.g);
        jd.c<fes> $$3 = $$1.b(sk.a);
        jd.c<fes> $$4 = $$1.b(sk.b);
        je<fjo> $$5 = $$0.a(mj.bq);
        jd.c<fjo> $$6 = $$5.b(qz.b);
        jd.c<fjo> $$7 = $$5.b(qz.j);
        jd.c<fjo> $$8 = $$5.b(qz.m);
        je<fgy> $$9 = $$0.a(mj.bt);
        jd.c<fgy> $$10 = $$9.b(qy.a);
        jd.c<fgy> $$11 = $$9.b(b);
        jd.c<fgy> $$12 = $$9.b(c);
        $$0.a(a, new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/town_centers/savanna_meeting_point_1"), (Object)100), (Object)Pair.of(fgw.a("village/savanna/town_centers/savanna_meeting_point_2"), (Object)50), (Object)Pair.of(fgw.a("village/savanna/town_centers/savanna_meeting_point_3"), (Object)150), (Object)Pair.of(fgw.a("village/savanna/town_centers/savanna_meeting_point_4"), (Object)150), (Object)Pair.of(fgw.a("village/savanna/zombie/town_centers/savanna_meeting_point_1", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/town_centers/savanna_meeting_point_2", $$6), (Object)1), (Object)Pair.of(fgw.a("village/savanna/zombie/town_centers/savanna_meeting_point_3", $$6), (Object)3), (Object)Pair.of(fgw.a("village/savanna/zombie/town_centers/savanna_meeting_point_4", $$6), (Object)3)), fgy.a.b));
        qy.a($$0, "village/savanna/streets", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/streets/corner_01", $$7), (Object)2), (Object)Pair.of(fgw.a("village/savanna/streets/corner_03", $$7), (Object)2), (Object)Pair.of(fgw.a("village/savanna/streets/straight_02", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/straight_04", $$7), (Object)7), (Object)Pair.of(fgw.a("village/savanna/streets/straight_05", $$7), (Object)3), (Object)Pair.of(fgw.a("village/savanna/streets/straight_06", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/straight_08", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/straight_09", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/straight_10", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/straight_11", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/streets/crossroad_02", $$7), (Object)1), (Object)Pair.of(fgw.a("village/savanna/streets/crossroad_03", $$7), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/savanna/streets/crossroad_04", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/crossroad_05", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/crossroad_06", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/crossroad_07", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/split_01", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/split_02", $$7), (Object)2), Pair.of(fgw.a("village/savanna/streets/turn_01", $$7), (Object)3)}), fgy.a.a));
        qy.a($$0, "village/savanna/zombie/streets", new fgy($$12, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/zombie/streets/corner_01", $$7), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/corner_03", $$7), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_02", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_04", $$7), (Object)7), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_05", $$7), (Object)3), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_06", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_08", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_09", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_10", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/straight_11", $$7), (Object)4), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_02", $$7), (Object)1), (Object)Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_03", $$7), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_04", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_05", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_06", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/crossroad_07", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/split_01", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/split_02", $$7), (Object)2), Pair.of(fgw.a("village/savanna/zombie/streets/turn_01", $$7), (Object)3)}), fgy.a.a));
        qy.a($$0, "village/savanna/houses", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_1"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_2"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_3"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_4"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_5"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_6"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_7"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_small_house_8"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_medium_house_1"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_medium_house_2"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_butchers_shop_1"), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_butchers_shop_2"), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/savanna/houses/savanna_tool_smith_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_fletcher_house_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_shepherd_1"), (Object)7), Pair.of(fgw.a("village/savanna/houses/savanna_armorer_1"), (Object)1), Pair.of(fgw.a("village/savanna/houses/savanna_fisher_cottage_1"), (Object)3), Pair.of(fgw.a("village/savanna/houses/savanna_tannery_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_cartographer_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_library_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_mason_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_weaponsmith_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_weaponsmith_2"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_temple_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_temple_2"), (Object)3), Pair.of(fgw.a("village/savanna/houses/savanna_large_farm_1", $$8), (Object)4), Pair.of(fgw.a("village/savanna/houses/savanna_large_farm_2", $$8), (Object)6), Pair.of(fgw.a("village/savanna/houses/savanna_small_farm", $$8), (Object)4), Pair.of(fgw.a("village/savanna/houses/savanna_animal_pen_1"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_animal_pen_2"), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_animal_pen_3"), (Object)2), Pair.of(fgw.i(), (Object)5)}), fgy.a.b));
        qy.a($$0, "village/savanna/zombie/houses", new fgy($$12, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_1", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_2", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_3", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_4", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_5", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_6", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_7", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_small_house_8", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_medium_house_1", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/zombie/houses/savanna_medium_house_2", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_butchers_shop_1", $$6), (Object)2), (Object)Pair.of(fgw.a("village/savanna/houses/savanna_butchers_shop_2", $$6), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/savanna/houses/savanna_tool_smith_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_fletcher_house_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_shepherd_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_armorer_1", $$6), (Object)1), Pair.of(fgw.a("village/savanna/houses/savanna_fisher_cottage_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_tannery_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_cartographer_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_library_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_mason_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_weaponsmith_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_weaponsmith_2", $$6), (Object)2), Pair.of(fgw.a("village/savanna/houses/savanna_temple_1", $$6), (Object)1), Pair.of(fgw.a("village/savanna/houses/savanna_temple_2", $$6), (Object)3), Pair.of(fgw.a("village/savanna/houses/savanna_large_farm_1", $$6), (Object)4), Pair.of(fgw.a("village/savanna/zombie/houses/savanna_large_farm_2", $$6), (Object)4), Pair.of(fgw.a("village/savanna/houses/savanna_small_farm", $$6), (Object)4), Pair.of(fgw.a("village/savanna/houses/savanna_animal_pen_1", $$6), (Object)2), Pair.of(fgw.a("village/savanna/zombie/houses/savanna_animal_pen_2", $$6), (Object)2), Pair.of(fgw.a("village/savanna/zombie/houses/savanna_animal_pen_3", $$6), (Object)2), Pair.of(fgw.i(), (Object)5)}), fgy.a.b));
        $$0.a(b, new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/plains/terminators/terminator_01", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_02", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_03", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_04", $$7), (Object)1), (Object)Pair.of(fgw.a("village/savanna/terminators/terminator_05", $$7), (Object)1)), fgy.a.a));
        $$0.a(c, new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/plains/terminators/terminator_01", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_02", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_03", $$7), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_04", $$7), (Object)1), (Object)Pair.of(fgw.a("village/savanna/zombie/terminators/terminator_05", $$7), (Object)1)), fgy.a.a));
        qy.a($$0, "village/savanna/trees", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a($$2), (Object)1)), fgy.a.b));
        qy.a($$0, "village/savanna/decor", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/savanna_lamp_post_01"), (Object)4), (Object)Pair.of(fgw.a($$2), (Object)4), (Object)Pair.of(fgw.a($$3), (Object)4), (Object)Pair.of(fgw.a($$4), (Object)1), (Object)Pair.of(fgw.i(), (Object)4)), fgy.a.b));
        qy.a($$0, "village/savanna/zombie/decor", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/savanna_lamp_post_01", $$6), (Object)4), (Object)Pair.of(fgw.a($$2), (Object)4), (Object)Pair.of(fgw.a($$3), (Object)4), (Object)Pair.of(fgw.a($$4), (Object)1), (Object)Pair.of(fgw.i(), (Object)4)), fgy.a.b));
        qy.a($$0, "village/savanna/villagers", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/villagers/nitwit"), (Object)1), (Object)Pair.of(fgw.a("village/savanna/villagers/baby"), (Object)1), (Object)Pair.of(fgw.a("village/savanna/villagers/unemployed"), (Object)10)), fgy.a.b));
        qy.a($$0, "village/savanna/zombie/villagers", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/savanna/zombie/villagers/nitwit"), (Object)1), (Object)Pair.of(fgw.a("village/savanna/zombie/villagers/unemployed"), (Object)10)), fgy.a.b));
    }
}

