/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;

public class rb {
    public static final amt<fgy> a = qy.a("village/snowy/town_centers");
    private static final amt<fgy> b = qy.a("village/snowy/terminators");

    public static void a(qr<fgy> $$0) {
        je<fes> $$1 = $$0.a(mj.bp);
        jd.c<fes> $$2 = $$1.b(sk.h);
        jd.c<fes> $$3 = $$1.b(sk.c);
        jd.c<fes> $$4 = $$1.b(sk.d);
        je<fjo> $$5 = $$0.a(mj.bq);
        jd.c<fjo> $$6 = $$5.b(qz.k);
        jd.c<fjo> $$7 = $$5.b(qz.n);
        jd.c<fjo> $$8 = $$5.b(qz.c);
        je<fgy> $$9 = $$0.a(mj.bt);
        jd.c<fgy> $$10 = $$9.b(qy.a);
        jd.c<fgy> $$11 = $$9.b(b);
        $$0.a(a, new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/town_centers/snowy_meeting_point_1"), (Object)100), (Object)Pair.of(fgw.a("village/snowy/town_centers/snowy_meeting_point_2"), (Object)50), (Object)Pair.of(fgw.a("village/snowy/town_centers/snowy_meeting_point_3"), (Object)150), (Object)Pair.of(fgw.a("village/snowy/zombie/town_centers/snowy_meeting_point_1"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/town_centers/snowy_meeting_point_2"), (Object)1), (Object)Pair.of(fgw.a("village/snowy/zombie/town_centers/snowy_meeting_point_3"), (Object)3)), fgy.a.b));
        qy.a($$0, "village/snowy/streets", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/streets/corner_01", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/streets/corner_02", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/streets/corner_03", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/streets/square_01", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/streets/straight_01", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/streets/straight_02", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/streets/straight_03", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/streets/straight_04", $$6), (Object)7), (Object)Pair.of(fgw.a("village/snowy/streets/straight_06", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/streets/straight_08", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/streets/crossroad_02", $$6), (Object)1), (Object)Pair.of(fgw.a("village/snowy/streets/crossroad_03", $$6), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/snowy/streets/crossroad_04", $$6), (Object)2), Pair.of(fgw.a("village/snowy/streets/crossroad_05", $$6), (Object)2), Pair.of(fgw.a("village/snowy/streets/crossroad_06", $$6), (Object)2), Pair.of(fgw.a("village/snowy/streets/turn_01", $$6), (Object)3)}), fgy.a.a));
        qy.a($$0, "village/snowy/zombie/streets", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/zombie/streets/corner_01", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/corner_02", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/corner_03", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/square_01", $$6), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_01", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_02", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_03", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_04", $$6), (Object)7), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_06", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/straight_08", $$6), (Object)4), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/crossroad_02", $$6), (Object)1), (Object)Pair.of(fgw.a("village/snowy/zombie/streets/crossroad_03", $$6), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/snowy/zombie/streets/crossroad_04", $$6), (Object)2), Pair.of(fgw.a("village/snowy/zombie/streets/crossroad_05", $$6), (Object)2), Pair.of(fgw.a("village/snowy/zombie/streets/crossroad_06", $$6), (Object)2), Pair.of(fgw.a("village/snowy/zombie/streets/turn_01", $$6), (Object)3)}), fgy.a.a));
        qy.a($$0, "village/snowy/houses", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_1"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_2"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_3"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_4"), (Object)3), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_5"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_6"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_7"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_small_house_8"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_medium_house_1"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_medium_house_2"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_medium_house_3"), (Object)2), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_butchers_shop_1"), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/snowy/houses/snowy_butchers_shop_2"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_tool_smith_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_fletcher_house_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_shepherds_house_1"), (Object)3), Pair.of(fgw.a("village/snowy/houses/snowy_armorer_house_1"), (Object)1), Pair.of(fgw.a("village/snowy/houses/snowy_armorer_house_2"), (Object)1), Pair.of(fgw.a("village/snowy/houses/snowy_fisher_cottage"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_tannery_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_cartographer_house_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_library_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_masons_house_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_masons_house_2"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_weapon_smith_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_temple_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_farm_1", $$7), (Object)3), Pair.of(fgw.a("village/snowy/houses/snowy_farm_2", $$7), (Object)3), Pair.of(fgw.a("village/snowy/houses/snowy_animal_pen_1"), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_animal_pen_2"), (Object)2), Pair.of(fgw.i(), (Object)6)}), fgy.a.b));
        qy.a($$0, "village/snowy/zombie/houses", new fgy($$11, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_1", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_2", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_3", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_4", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_5", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_6", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_7", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_small_house_8", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_medium_house_1", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_medium_house_2", $$8), (Object)2), (Object)Pair.of(fgw.a("village/snowy/zombie/houses/snowy_medium_house_3", $$8), (Object)1), (Object)Pair.of(fgw.a("village/snowy/houses/snowy_butchers_shop_1", $$8), (Object)2), (Object[])new Pair[]{Pair.of(fgw.a("village/snowy/houses/snowy_butchers_shop_2", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_tool_smith_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_fletcher_house_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_shepherds_house_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_armorer_house_1", $$8), (Object)1), Pair.of(fgw.a("village/snowy/houses/snowy_armorer_house_2", $$8), (Object)1), Pair.of(fgw.a("village/snowy/houses/snowy_fisher_cottage", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_tannery_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_cartographer_house_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_library_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_masons_house_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_masons_house_2", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_weapon_smith_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_temple_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_farm_1", $$8), (Object)3), Pair.of(fgw.a("village/snowy/houses/snowy_farm_2", $$8), (Object)3), Pair.of(fgw.a("village/snowy/houses/snowy_animal_pen_1", $$8), (Object)2), Pair.of(fgw.a("village/snowy/houses/snowy_animal_pen_2", $$8), (Object)2), Pair.of(fgw.i(), (Object)6)}), fgy.a.b));
        $$0.a(b, new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/plains/terminators/terminator_01", $$6), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_02", $$6), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_03", $$6), (Object)1), (Object)Pair.of(fgw.a("village/plains/terminators/terminator_04", $$6), (Object)1)), fgy.a.a));
        qy.a($$0, "village/snowy/trees", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a($$2), (Object)1)), fgy.a.b));
        qy.a($$0, "village/snowy/decor", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_01"), (Object)4), (Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_02"), (Object)4), (Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_03"), (Object)1), (Object)Pair.of(fgw.a($$2), (Object)4), (Object)Pair.of(fgw.a($$3), (Object)4), (Object)Pair.of(fgw.a($$4), (Object)1), (Object)Pair.of(fgw.i(), (Object)9)), fgy.a.b));
        qy.a($$0, "village/snowy/zombie/decor", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_01", $$8), (Object)1), (Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_02", $$8), (Object)1), (Object)Pair.of(fgw.a("village/snowy/snowy_lamp_post_03", $$8), (Object)1), (Object)Pair.of(fgw.a($$2), (Object)4), (Object)Pair.of(fgw.a($$3), (Object)4), (Object)Pair.of(fgw.a($$4), (Object)4), (Object)Pair.of(fgw.i(), (Object)7)), fgy.a.b));
        qy.a($$0, "village/snowy/villagers", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/villagers/nitwit"), (Object)1), (Object)Pair.of(fgw.a("village/snowy/villagers/baby"), (Object)1), (Object)Pair.of(fgw.a("village/snowy/villagers/unemployed"), (Object)10)), fgy.a.b));
        qy.a($$0, "village/snowy/zombie/villagers", new fgy($$10, (List<Pair<Function<fgy.a, ? extends fgw>, Integer>>)ImmutableList.of((Object)Pair.of(fgw.a("village/snowy/zombie/villagers/nitwit"), (Object)1), (Object)Pair.of(fgw.a("village/snowy/zombie/villagers/unemployed"), (Object)10)), fgy.a.b));
    }
}

