/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;

public class ri {
    public static final amt<fgy> a = qy.a("trial_chambers/chamber/end");
    public static final amt<fgy> b = qy.a("trial_chambers/hallway/fallback");
    public static final List<fha> c = ImmutableList.builder().add((Object)fha.a(cbn.b().a(List.of(fha.a(ri.a("contents/ranged"), ri.a("ranged/skeleton")), fha.a(ri.a("contents/slow_ranged"), ri.a("slow_ranged/skeleton")))).a(List.of(fha.a(ri.a("contents/ranged"), ri.a("ranged/stray")), fha.a(ri.a("contents/slow_ranged"), ri.a("slow_ranged/stray")))).a(List.of(fha.a(ri.a("contents/ranged"), ri.a("ranged/poison_skeleton")), fha.a(ri.a("contents/slow_ranged"), ri.a("slow_ranged/poison_skeleton")))).a())).add((Object)fha.a(ri.a("contents/melee"), cbn.b().a(ri.a("melee/zombie")).a(ri.a("melee/husk")).a(ri.a("melee/spider")).a())).add((Object)fha.a(ri.a("contents/small_melee"), cbn.b().a(ri.a("small_melee/slime")).a(ri.a("small_melee/cave_spider")).a(ri.a("small_melee/silverfish")).a(ri.a("small_melee/baby_zombie")).a())).build();

    public static String a(String $$0) {
        return "trial_chambers/spawner/" + $$0;
    }

    public static void a(qr<fgy> $$0) {
        je<fgy> $$1 = $$0.a(mj.bt);
        jd.c<fgy> $$2 = $$1.b(qy.a);
        jd.c<fgy> $$3 = $$1.b(b);
        je<fjo> $$4 = $$0.a(mj.bq);
        jd.c<fjo> $$5 = $$4.b(qz.M);
        $$0.a(a, new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/corridor/end_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/end_2", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/entrance_cap", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/entrance_cap", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chambers/end", new fgy($$3, List.of(Pair.of(fgw.b("trial_chambers/chamber/chamber_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/corridor", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/corridor/second_plate"), (Object)1), Pair.of(fgw.b("trial_chambers/intersection/intersection_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/intersection/intersection_2", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/intersection/intersection_3", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/first_plate"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/entrance_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/entrance_2", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/entrance_3", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/addon", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/addon/full_stacked_walkway"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/full_stacked_walkway_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/full_corner_column"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/grate_bridge"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/hanging_platform"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/short_grate_platform"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/short_platform"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/lower_staircase_down"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/walkway_with_bridge_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/addon/c1_breeze"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/assembly", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/assembly/full_column"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_1"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_2"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_3"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_4"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_5"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_6"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/cover_7"), (Object)5), Pair.of(fgw.b("trial_chambers/chamber/assembly/platform_1"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/spawner_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/hanging_1"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/hanging_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/hanging_3"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/hanging_4"), (Object)2), Pair.of(fgw.b("trial_chambers/chamber/assembly/hanging_5"), (Object)4), Pair.of(fgw.b("trial_chambers/chamber/assembly/left_staircase_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/left_staircase_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/left_staircase_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/right_staircase_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/right_staircase_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/assembly/right_staircase_3"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/eruption", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/eruption/center_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/breeze_slice_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/slice_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/slice_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/slice_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/quadrant_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/quadrant_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/quadrant_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/quadrant_4"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/eruption/quadrant_5"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/slanted", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/slanted/center"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/hallway_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/hallway_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/hallway_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_4"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/ramp_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/ramp_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/ramp_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/ramp_4"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/ominous_upper_arm_1"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chamber/pedestal", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chamber/pedestal/center_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/pedestal/slice_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/pedestal/slice_2"), (Object)3), Pair.of(fgw.b("trial_chambers/chamber/pedestal/slice_3"), (Object)3), Pair.of(fgw.b("trial_chambers/chamber/pedestal/slice_4"), (Object)3), Pair.of(fgw.b("trial_chambers/chamber/pedestal/slice_5"), (Object)3), Pair.of(fgw.b("trial_chambers/chamber/pedestal/ominous_slice_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/pedestal/quadrant_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/pedestal/quadrant_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/pedestal/quadrant_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_1"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_2"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_3"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/slanted/quadrant_4"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/corridor/slices", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/corridor/straight_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/straight_2", $$5), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/straight_3", $$5), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/straight_4", $$5), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/straight_5", $$5), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/straight_6", $$5), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/straight_7", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/straight_8", $$5), (Object)2)), fgy.a.b));
        $$0.a(b, new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/hallway/rubble"), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/rubble_chamber"), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/rubble_thin"), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/rubble_chamber_thin"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/hallway", new fgy($$3, List.of(Pair.of(fgw.b("trial_chambers/hallway/corridor_connector_1"), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/upper_hallway_connector", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/lower_hallway_connector", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/rubble"), (Object)1), Pair.of(fgw.b("trial_chambers/chamber/chamber_1", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/chamber_2", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/chamber_4", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/chamber_8", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/assembly", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/eruption", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/slanted", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/chamber/pedestal", $$5), (Object)150), Pair.of(fgw.b("trial_chambers/hallway/rubble_chamber", $$5), (Object)10), Pair.of(fgw.b("trial_chambers/hallway/rubble_chamber_thin", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/cache_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/left_corner", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/right_corner", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/corner_staircase", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/corner_staircase_down", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/long_straight_staircase", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/long_straight_staircase_down", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/straight", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/straight_staircase", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/straight_staircase_down", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/trapped_staircase", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/encounter_1", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/encounter_2", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/encounter_3", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/encounter_4", $$5), (Object)1), Pair.of(fgw.b("trial_chambers/hallway/encounter_5", $$5), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/corridors/addon/lower", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)8), Pair.of(fgw.b("trial_chambers/corridor/addon/staircase"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/wall"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/ladder_to_middle"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/arrow_dispenser"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/bridge_lower"), (Object)2)), fgy.a.b));
        qy.a($$0, "trial_chambers/corridors/addon/middle", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)8), Pair.of(fgw.b("trial_chambers/corridor/addon/open_walkway"), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/addon/walled_walkway"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/corridors/addon/middle_upper", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)6), Pair.of(fgw.b("trial_chambers/corridor/addon/open_walkway_upper"), (Object)2), Pair.of(fgw.b("trial_chambers/corridor/addon/chandelier_upper"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/decoration_upper"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/head_upper"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/reward_upper"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/atrium", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/corridor/atrium/bogged_relief"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/breeze_relief"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/spiral_relief"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/spider_relief"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/grand_staircase_1"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/grand_staircase_2"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/atrium/grand_staircase_3"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/decor", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)22), Pair.of(fgw.b("trial_chambers/decor/empty_pot"), (Object)2), Pair.of(fgw.b("trial_chambers/decor/dead_bush_pot"), (Object)2), Pair.of(fgw.b("trial_chambers/decor/undecorated_pot"), (Object)10), Pair.of(fgw.b("trial_chambers/decor/flow_pot"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/guster_pot"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/scrape_pot"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/candle_1"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/candle_2"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/candle_3"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/candle_4"), (Object)1), Pair.of(fgw.b("trial_chambers/decor/barrel"), (Object)2)), fgy.a.b));
        qy.a($$0, "trial_chambers/decor/disposal", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/decor/disposal"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/decor/bed", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/decor/white_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/light_gray_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/gray_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/black_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/brown_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/red_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/orange_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/yellow_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/lime_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/green_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/cyan_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/light_blue_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/blue_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/purple_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/magenta_bed"), (Object)3), Pair.of(fgw.b("trial_chambers/decor/pink_bed"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/entrance", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/corridor/addon/display_1"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/display_2"), (Object)1), Pair.of(fgw.b("trial_chambers/corridor/addon/display_3"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/decor/chamber", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)4), Pair.of(fgw.b("trial_chambers/decor/undecorated_pot"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/reward/all", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/reward/vault"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/reward/ominous_vault", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/reward/ominous_vault"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/reward/contents/default", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/reward/vault"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chests/supply", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chests/connectors/supply"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/chests/contents/supply", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/chests/supply"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/ranged", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/ranged"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/slow_ranged", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/slow_ranged"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/melee", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/melee"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/small_melee", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/small_melee"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/breeze", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/breeze"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/all", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/connectors/ranged"), (Object)1), Pair.of(fgw.b("trial_chambers/spawner/connectors/melee"), (Object)1), Pair.of(fgw.b("trial_chambers/spawner/connectors/small_melee"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/spawner/contents/breeze", new fgy($$2, List.of(Pair.of(fgw.b("trial_chambers/spawner/breeze/breeze"), (Object)1)), fgy.a.b));
        qy.a($$0, "trial_chambers/dispensers/chamber", new fgy($$2, List.of(Pair.of(fgw.i(), (Object)1), Pair.of(fgw.b("trial_chambers/dispensers/chamber"), (Object)1), Pair.of(fgw.b("trial_chambers/dispensers/wall_dispenser"), (Object)1), Pair.of(fgw.b("trial_chambers/dispensers/floor_dispenser"), (Object)1)), fgy.a.b));
        fhb.a($$0, $$2, c);
    }
}

