/*
 * Decompiled with CFR 0.152.
 */
import java.util.List;

public class si {
    public static final amt<fes> a = sh.a("crimson_fungi");
    public static final amt<fes> b = sh.a("warped_fungi");
    public static final amt<fes> c = sh.a("oak_checked");
    public static final amt<fes> d = sh.a("dark_oak_checked");
    public static final amt<fes> e = sh.a("pale_oak_checked");
    public static final amt<fes> f = sh.a("pale_oak_creaking_checked");
    public static final amt<fes> g = sh.a("birch_checked");
    public static final amt<fes> h = sh.a("acacia_checked");
    public static final amt<fes> i = sh.a("spruce_checked");
    public static final amt<fes> j = sh.a("mangrove_checked");
    public static final amt<fes> k = sh.a("cherry_checked");
    public static final amt<fes> l = sh.a("pine_on_snow");
    public static final amt<fes> m = sh.a("spruce_on_snow");
    public static final amt<fes> n = sh.a("pine_checked");
    public static final amt<fes> o = sh.a("jungle_tree");
    public static final amt<fes> p = sh.a("fancy_oak_checked");
    public static final amt<fes> q = sh.a("mega_jungle_tree_checked");
    public static final amt<fes> r = sh.a("mega_spruce_checked");
    public static final amt<fes> s = sh.a("mega_pine_checked");
    public static final amt<fes> t = sh.a("tall_mangrove_checked");
    public static final amt<fes> u = sh.a("jungle_bush");
    public static final amt<fes> v = sh.a("super_birch_bees_0002");
    public static final amt<fes> w = sh.a("super_birch_bees");
    public static final amt<fes> x = sh.a("oak_bees_0002_leaf_litter");
    public static final amt<fes> y = sh.a("oak_bees_002");
    public static final amt<fes> z = sh.a("birch_bees_0002");
    public static final amt<fes> A = sh.a("birch_bees_0002_leaf_litter");
    public static final amt<fes> B = sh.a("birch_bees_002");
    public static final amt<fes> C = sh.a("fancy_oak_bees_0002_leaf_litter");
    public static final amt<fes> D = sh.a("fancy_oak_bees_002");
    public static final amt<fes> E = sh.a("fancy_oak_bees");
    public static final amt<fes> F = sh.a("cherry_bees_005");
    public static final amt<fes> G = sh.a("oak_leaf_litter");
    public static final amt<fes> H = sh.a("dark_oak_leaf_litter");
    public static final amt<fes> I = sh.a("birch_leaf_litter");
    public static final amt<fes> J = sh.a("fancy_oak_leaf_litter");
    public static final amt<fes> K = sh.a("fallen_oak_tree");
    public static final amt<fes> L = sh.a("fallen_birch_tree");
    public static final amt<fes> M = sh.a("fallen_super_birch_tree");
    public static final amt<fes> N = sh.a("fallen_spruce_tree");
    public static final amt<fes> O = sh.a("fallen_jungle_tree");

    public static void a(qr<fes> $$0) {
        je<exi<?, ?>> $$1 = $$0.a(mj.aY);
        jd.c<exi<?, ?>> $$2 = $$1.b(rx.a);
        jd.c<exi<?, ?>> $$3 = $$1.b(rx.c);
        jd.c<exi<?, ?>> $$4 = $$1.b(rx.g);
        jd.c<exi<?, ?>> $$5 = $$1.b(rx.h);
        jd.c<exi<?, ?>> $$6 = $$1.b(rx.i);
        jd.c<exi<?, ?>> $$7 = $$1.b(rx.k);
        jd.c<exi<?, ?>> $$8 = $$1.b(rx.l);
        jd.c<exi<?, ?>> $$9 = $$1.b(rx.m);
        jd.c<exi<?, ?>> $$10 = $$1.b(rx.n);
        jd.c<exi<?, ?>> $$11 = $$1.b(rx.A);
        jd.c<exi<?, ?>> $$12 = $$1.b(rx.C);
        jd.c<exi<?, ?>> $$13 = $$1.b(rx.o);
        jd.c<exi<?, ?>> $$14 = $$1.b(rx.p);
        jd.c<exi<?, ?>> $$15 = $$1.b(rx.q);
        jd.c<exi<?, ?>> $$16 = $$1.b(rx.s);
        jd.c<exi<?, ?>> $$17 = $$1.b(rx.t);
        jd.c<exi<?, ?>> $$18 = $$1.b(rx.u);
        jd.c<exi<?, ?>> $$19 = $$1.b(rx.B);
        jd.c<exi<?, ?>> $$20 = $$1.b(rx.y);
        jd.c<exi<?, ?>> $$21 = $$1.b(rx.v);
        jd.c<exi<?, ?>> $$22 = $$1.b(rx.w);
        jd.c<exi<?, ?>> $$23 = $$1.b(rx.D);
        jd.c<exi<?, ?>> $$24 = $$1.b(rx.E);
        jd.c<exi<?, ?>> $$25 = $$1.b(rx.G);
        jd.c<exi<?, ?>> $$26 = $$1.b(rx.H);
        jd.c<exi<?, ?>> $$27 = $$1.b(rx.I);
        jd.c<exi<?, ?>> $$28 = $$1.b(rx.K);
        jd.c<exi<?, ?>> $$29 = $$1.b(rx.L);
        jd.c<exi<?, ?>> $$30 = $$1.b(rx.N);
        jd.c<exi<?, ?>> $$31 = $$1.b(rx.O);
        jd.c<exi<?, ?>> $$32 = $$1.b(rx.P);
        jd.c<exi<?, ?>> $$33 = $$1.b(rx.Q);
        jd.c<exi<?, ?>> $$34 = $$1.b(rx.R);
        jd.c<exi<?, ?>> $$35 = $$1.b(rx.S);
        jd.c<exi<?, ?>> $$36 = $$1.b(rx.T);
        jd.c<exi<?, ?>> $$37 = $$1.b(rx.W);
        jd.c<exi<?, ?>> $$38 = $$1.b(rx.X);
        jd.c<exi<?, ?>> $$39 = $$1.b(rx.V);
        jd.c<exi<?, ?>> $$40 = $$1.b(rx.U);
        sh.a($$0, a, $$2, fej.a(8), feg.a());
        sh.a($$0, b, $$3, fej.a(8), feg.a());
        sh.a($$0, c, $$4, sh.a(dzs.z));
        sh.a($$0, d, $$5, sh.a(dzs.F));
        sh.a($$0, e, $$6, sh.a(dzs.G));
        sh.a($$0, f, $$7, sh.a(dzs.G));
        sh.a($$0, g, $$8, sh.a(dzs.B));
        sh.a($$0, h, $$9, sh.a(dzs.D));
        sh.a($$0, i, $$10, sh.a(dzs.A));
        sh.a($$0, j, $$11, sh.a(dzs.H));
        sh.a($$0, k, $$12, sh.a(dzs.E));
        evx $$41 = evx.a(iz.a.q(), dzs.er, dzs.rP);
        List<fev> $$42 = List.of(fel.a(iz.b, evx.a(evx.a(dzs.rP)), 8), feh.a($$41));
        sh.a($$0, l, $$13, $$42);
        sh.a($$0, m, $$10, $$42);
        sh.a($$0, n, $$13, sh.a(dzs.A));
        sh.a($$0, o, $$14, sh.a(dzs.C));
        sh.a($$0, p, $$15, sh.a(dzs.z));
        sh.a($$0, q, $$16, sh.a(dzs.C));
        sh.a($$0, r, $$17, sh.a(dzs.A));
        sh.a($$0, s, $$18, sh.a(dzs.A));
        sh.a($$0, t, $$19, sh.a(dzs.H));
        sh.a($$0, u, $$20, sh.a(dzs.z));
        sh.a($$0, v, $$21, sh.a(dzs.B));
        sh.a($$0, w, $$22, sh.a(dzs.B));
        sh.a($$0, x, $$23, sh.a(dzs.z));
        sh.a($$0, y, $$24, sh.a(dzs.z));
        sh.a($$0, z, $$25, sh.a(dzs.B));
        sh.a($$0, A, $$26, sh.a(dzs.B));
        sh.a($$0, B, $$27, sh.a(dzs.B));
        sh.a($$0, C, $$28, sh.a(dzs.z));
        sh.a($$0, D, $$29, sh.a(dzs.z));
        sh.a($$0, E, $$30, sh.a(dzs.z));
        sh.a($$0, F, $$31, sh.a(dzs.E));
        sh.a($$0, G, $$32, sh.a(dzs.z));
        sh.a($$0, H, $$33, sh.a(dzs.F));
        sh.a($$0, I, $$34, sh.a(dzs.B));
        sh.a($$0, J, $$35, sh.a(dzs.z));
        sh.a($$0, K, $$36, sh.a(dzs.z));
        sh.a($$0, L, $$37, sh.a(dzs.B));
        sh.a($$0, M, $$38, sh.a(dzs.B));
        sh.a($$0, N, $$39, sh.a(dzs.A));
        sh.a($$0, O, $$40, sh.a(dzs.C));
    }
}

